SELECT DISTINCT en.[P-SYS-ID],
		prv.[P-ID]
      ,en.[P-TY-CD]
	  ,prv.[P-ID]
	  ,pt.Long AS ProviderType
	  ,prv.[P-BLNG-CD]
	  , CASE WHEN 
	  EXISTS(
		SELECT [P-GROUP-SYS-ID] 
		FROM dbo.[DT_PAFFILTB_STG] aff 
		WHERE aff.[P-GROUP-SYS-ID] = en.[P-SYS-ID] AND 
		CASE WHEN ISDATE(aff.[P-AFFL-END-DT]) = 1 THEN aff.[P-AFFL-END-DT] ELSE '1/1/1753' END > '12/31/2015')
		THEN 'Y' ELSE 'N' END AS [GROUP (Y/N)]
	,  CASE WHEN 
	  EXISTS(
		SELECT [P-GROUP-SYS-ID] 
		FROM dbo.[DT_PAFFILTB_STG] aff 
		WHERE aff.[P-MEMBER-SYS-ID] = en.[P-SYS-ID] AND 
		CASE WHEN ISDATE(aff.[P-AFFL-END-DT]) = 1 THEN aff.[P-AFFL-END-DT] ELSE '1/1/1753' END > '12/31/2015')
		THEN 'Y' ELSE 'N' END AS [MEMBER (Y/N)]
  FROM [dbo].[DT_PENROLTB_STG] en
  INNER JOIN [dbo].[DT_PROVDRTB_STG] prv ON prv.[P-SYS-ID] = en.[P-SYS-ID] 
  LEFT OUTER JOIN [dbo].[LKUP_PROVIDER_TYPE_CODE] pt ON pt.[P-TY-CD] = en.[P-TY-CD]
  WHERE en.[P-ENROL-STAT-TY-CD] = '00' AND prv.[P-REC-TY-CD] = 'P' AND en.[P-STAT-END-DT] IS NOT NULL AND
  CASE WHEN ISDATE(en.[P-STAT-END-DT]) = 1 THEN CAST(en.[P-STAT-END-DT] AS datetime) ELSE '1/1/1753' END > '12/31/2015'​;
