using MAXIMUS.Core.Libraries;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using Workflow;
using CON = MAXIMUS.Core.Libraries.Constants;


namespace PDMSWorkflow
{
    public class WFEmailMMISErrors : BaseWorkflowTask, IWorkflowTask
    {
        private string nextStep;

        public WFEmailMMISErrors(int processID, int stepID)
            : base(processID, stepID)
        {
            //
            // TODO: Add constructor logic here
            //
        }

        override public bool ProcessTask()
        {
            string logMsg = String.Format(Constants.LogString.MethodSignature, MethodBase.GetCurrentMethod().DeclaringType.Name, MethodBase.GetCurrentMethod().Name);
            Logging log = new Logging(LogThreadID, logMsg);

            Dictionary<string, object> fields = new Dictionary<string, object>();
            List<SqlParameter> parameters;
            string subject = string.Empty;
            string templateName = "MMISProviderErrors.txt";
            string templatesDirectory = string.Empty;
            string partyID = GetProcessParameter(CON.ProcessParameter.PartyID);
            string serviceLocationID = GetProcessParameter(CON.ProcessParameter.ServiceLocationID);
            string transQueueID = GetProcessParameter(CON.ProcessParameter.TransactionQueueID);

            bool result = false;

            try
            {
                // generated by sp_Admin_StoredProcBuilder on Oct 18 2013  4:47PM
                // create parameters objects and fill with values
                parameters = new List<SqlParameter>();
 
                parameters.Add(SqlParms.CreateParameter("PARTY_ID", DbType.Int32, partyID, true));
                parameters.Add(SqlParms.CreateParameter("MEDICAID_PK", DbType.Int32, serviceLocationID, true));
                parameters.Add(SqlParms.CreateParameter("TRANSACTION_QUEUE_ID", DbType.Int32, transQueueID, true));
 
                DataSet ds = DataAccess.ExecuteStoredProcedure("usp_SelectMMISErrors", parameters, "Errors");

                templatesDirectory = AppSettings.Get("PDMS_SVC_TemplatesPath", string.Empty);
                string emailErrorText = string.Empty;
                DataTable errors = ds.Tables[0];
                foreach (DataRow error in errors.Rows)
                {
                    emailErrorText += Methods.GetStringValue(error["MMIS_ERROR_CODE"]) + " - ";
                    emailErrorText += Methods.GetStringValue(error["MMIS_ERROR_DESC"]) + System.Environment.NewLine;
                }

                // if errors were returned
                if (emailErrorText.Length > 0)
                {
                    // generated by sp_Admin_StoredProcBuilder on Oct 18 2013  5:34PM
                    // create parameters objects and fill with values
                    parameters = new List<SqlParameter>();

                    parameters.Add(SqlParms.CreateParameter("PartyID", DbType.Int32, partyID, true));

                    DataSet provider = DataAccess.ExecuteStoredProcedure("usp_SelectProvider", parameters, "Provider");

                    string firstName = Methods.GetStringValue(provider.Tables[0].Rows[0]["FirstName"]);
                    string lastName = Methods.GetStringValue(provider.Tables[0].Rows[0]["LastName"]);
                    string NPI = Methods.GetStringValue(provider.Tables[0].Rows[0]["NPI"]);
                    string organizationName = Methods.GetStringValue(provider.Tables[0].Rows[0]["OrganizationName"]);
                    string providerType = Methods.GetStringValue(provider.Tables[0].Rows[0]["RoleType"]);
                    string name = string.Empty;

                    if (organizationName.Length == 0)
                    {
                        name = firstName + " " + lastName;
                    }
                    else
                    {
                        name = organizationName;
                    }

                    fields.Add("PROVIDERNAME", name);
                    fields.Add("PROVIDERTYPE", providerType);
                    fields.Add("CURRENTDATE", DateTime.Now.ToString("MM/dd/yyyy"));
                    fields.Add("NPI", NPI);
                    fields.Add("MMISERRORS", emailErrorText);

                    string recipients = AppSettings.Get("Workflow-Email-Admin", "OHPNMCodeJunkies@maximus.com");

                    EMailNotification notify = new EMailNotification( string.Empty, "MMIS Errors From Submission", recipients, LogThreadID );
                    string templateFullName = templatesDirectory + "\\" + templateName;
                    notify.SendNotification(templateFullName,fields, false);
                }
                result = true;
            }
            catch(Exception ex)
            {
                CoreException.ThrowException(LogThreadID, ex, logMsg);
            }
            return result;
        }

        override public string NextStep()
        {
            return nextStep;
        }
    }
}
