using MAXIMUS.Controllers.PDMS;
using MAXIMUS.Core.Libraries;
using System;
using System.Data;
using System.Reflection;
using Workflow;
using CON = MAXIMUS.Core.Libraries.Constants;

namespace PDMSWorkflow
{
    /// <summary>
    /// Summary description for WFRequiresReview
    /// </summary>
    public class WFReceiveMedicaidID : BaseWorkflowTask, IWorkflowTask
    {
        private string nextStep;

        public WFReceiveMedicaidID(int processID, int stepID)
            : base(processID, stepID)
        {
            //
            // TODO: Add constructor logic here
            //
        }

        override public bool ProcessTask()
        {
            string logMsg = String.Format(Constants.LogString.MethodSignature, MethodBase.GetCurrentMethod().DeclaringType.Name, MethodBase.GetCurrentMethod().Name);
            Logging log = new Logging(LogThreadID, logMsg);

            bool returnVal = false;
            string partyID = GetProcessParameter(CON.ProcessParameter.PartyID);
            string serviceLocationID = GetProcessParameter(CON.ProcessParameter.ServiceLocationID);
            string tqId = GetProcessParameter(CON.ProcessParameter.TransactionQueueID);
            //int hasId = 0;

            try
            {
				//TODO REGTOLIVE
                //if (tqId.Length == 0 || tqId == "-1") { tqId = "0"; }

                // verify if medicaid ids have been received for party based on processed transactions
                // generated by sp_Admin_StoredProcBuilder on Oct 18 2013  1:34PM
                // create parameters objects and fill with values
                //List<SqlParameter> parameters = new List<SqlParameter>();

                //parameters.Add(SqlParms.CreateParameter("PARTY_ID", DbType.Int32, partyID, true));
                //parameters.Add(SqlParms.CreateParameter("MEDICAID_PK", DbType.Int32, serviceLocationID, true));
                //parameters.Add(SqlParms.CreateParameter("TRANSACTION_QUEUE_ID", DbType.Int32, tqId, true));

                //hasId = Methods.GetIntValue(DataAccess.ExecuteScalar("usp_ValidateMedicaidIds", parameters));

                //if (hasId == (int)Constants.MMISStatusType.Processed)
                //{
                    returnVal = true;
                    nextStep = "Next";
                //}
                //else if (hasId == (int)Constants.MMISStatusType.Errors)
                //{
                //    returnVal = true;
                //    nextStep = "Error";
                //}
            }
            catch (Exception ex)
            {
                throw CoreException.ThrowException(LogThreadID, ex, logMsg);
            }
            return returnVal;
        }

        override public string NextStep()
        {
            return nextStep;
        }

        private bool IsPreviousStepCompleted(string partyId, string serviceLocationID)
        {
            bool toReturn = false;
            int pId;
            int sId;

            if(int.TryParse(partyId, out pId) && int.TryParse(serviceLocationID, out sId))
            {
                Process p = new Process(ProcessID);
                DataSet ds = TransactionController.SelectTransactionQueue(1, pId, sId);
                if (ObjectControllerHelper.HasRows(ds))
                {
                    string str = ds.Tables[0].Rows[0]["PROCESS_DATE_TIME"].ToString();
                    if (!string.IsNullOrEmpty(str))
                    {
                        DateTime date;
                        toReturn = DateTime.TryParse(str, out date);
                    }
                }
            }
            return toReturn;
        }
    }
}
