using MAXIMUS.Core.Libraries;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using Workflow;

namespace PDMSWorkflow
{
    /// <summary>
    /// Summary description for WFRequiresReview
    /// </summary>
    public class WFRequestMedicaidID : BaseWorkflowTask, IWorkflowTask
    {
        public WFRequestMedicaidID(int processID, int stepID)
            : base(processID, stepID)
        {
            //
            // TODO: Add constructor logic here
            //
        }

        override public bool ProcessTask()
        {
            // proc to add (if applicable) transaction records for Group Medicaid Id and Base Medicaid Id
            //  1) [Base Medicaid Id] if no pending transactions and affiliation Status = Pending Confirmation
            //                          and no Medicaid Id
            //  2) [Group Medicaid Id] if no pending transactions and no Medicaid Id

            string logMsg = String.Format(Constants.LogString.MethodSignature, MethodBase.GetCurrentMethod().DeclaringType.Name, MethodBase.GetCurrentMethod().Name);
            Logging log = new Logging(LogThreadID, logMsg);

            bool returnValue = false;
            int registrationId = 0;
            Process p = new Process(ProcessID);

            try
            {
                if (int.TryParse(p.GetProcessParameter(Constants.ProcessParameter.RegistrationID)
                    , out registrationId))
                {
                    // generated by sp_Admin_StoredProcBuilder on Aug 12 2013 12:11PM
                    // create parameters objects and fill with values
                    List<SqlParameter> parameters = new List<SqlParameter>();

                    parameters.Add(SqlParms.CreateParameter("REG_ID", DbType.Int32, registrationId, true));
                    parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, DateTime.Now, true));
                    parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, Constants.appWorkflowUserId, true));

                    DataAccess.ExecuteStoredProcedure("usp_UpdateGroupAffiliations", parameters);

                    returnValue = true;
                }
            }
            catch (Exception ex)
            {
                if (System.Diagnostics.Debugger.IsAttached) System.Diagnostics.Debugger.Break();
                string msg = String.Format(Constants.LogString.WorkflowTaskFailed, "Process Id: " + ProcessID.ToString(),
                    "Registration Id: " + registrationId.ToString() + ", Task Id: " + TaskID.ToString(), ex.Message);
                Exception newEx = new Exception(msg, ex.InnerException);
                throw CoreException.ThrowException(LogThreadID, newEx, logMsg);
            }
            return returnValue;
        }
    }
}
