using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.IO;
using System.Net;
using System.Xml;
using System.Xml.Linq;
using Microsoft.Extensions.Configuration;
using System.Security.Cryptography;

namespace TibcoDocImportNetCore
{
    public class SubmitOnBaseDocument
    {
        public string RequestID;
        public string FileTypeID;
        public string Tax_ID;
        public string Request_Type;
        public string Provider_ID;
        public string NPI;
        public string Taxonomy;
        public string Zip5;
        public string Extended_Zip;
        public string PDMS_Reg_ID;
        public string Document_Type;
        public string Application_Type;
        public byte[] Image_Blob;
    }

    public class SubmitOnBaseDocumentOnly
    {
        public string RequestID;
        public string FileTypeID;
        public byte[] Image_Blob;
    }

    public class OnBaseInterface
    {
        public string errMessage = "";
        public string RJkey = "";
        public string RJiv = "";
        public string WorkDir = "";
        public string UploadURL = "";
        public string cnString = "";

        public int SubmitFile(int docID, byte[] fileBytes, string fileName)
        {
            
            string localPath = Path.Combine(this.WorkDir, "onbase");
            Int32 unixTimestamp = (Int32)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
            string connString = this.cnString;
            try
            {
                fileBytes = EncryptRijndael(fileBytes);

                SubmitOnBaseDocumentOnly request = new SubmitOnBaseDocumentOnly()
                {
                    RequestID = docID.ToString(),
                    FileTypeID = "16",
                    Image_Blob = fileBytes
                };

                // serialize the object to xml 
                //string obj = Methods.SerializeObjectToXml(request);
                string obj = ToXMLDoc(request);
                fileName = Path.GetFileNameWithoutExtension(fileName) + ".xml";

                // Write the object to file
                Methods.WriteStringToFile(localPath, fileName, obj, false);

                string fullFilePath = localPath + fileName;
                // Send to OnBase and get response back                
                WebClient webClient = new WebClient();
                byte[] responseBytes = webClient.UploadFile(this.UploadURL, fullFilePath);                    

                // Return value example                 
                // <RequestID>98756432</RequestID>
                // <Result>Success</Result>
                // <ErrorMessage> </ErrorMessage>
                // <OnBaseDocumentID>1444230</ OnBaseDocumentID >
                // Get the XML tags
                XmlDocument xmlDoc = new XmlDocument();
                xmlDoc.LoadXml(Encoding.UTF8.GetString(responseBytes));

                int documentID = Convert.ToInt32(xmlDoc.GetElementsByTagName("RequestID")[0].InnerText);
                string result = xmlDoc.GetElementsByTagName("Result")[0].InnerText;
                string errorMessage = xmlDoc.GetElementsByTagName("ErrorMessage")[0].InnerText;
                int onBaseDocumentID = Convert.ToInt32(xmlDoc.GetElementsByTagName("OnBaseDocumentID")[0].InnerText);

                if (result.ToUpper() == Constants.OnBaseSuccess)
                {
                    // Ingest the OnBase document id
                    // generated by sp_Admin_StoredProcBuilder on Jul 21 2015  2:35PM
                    // create parameters objects and fill with values
                    List<SqlParameter> sqlParams = new List<SqlParameter>();

                    sqlParams.Add(SqlParms.CreateParameter("DOCUMENT_ID", DbType.Int32, documentID, true));
                    sqlParams.Add(SqlParms.CreateParameter("ONBASE_DOCUMENT_ID", DbType.Int32, onBaseDocumentID, true));

                    DataAccess.ExecuteStoredProcedure("usp_SetOnBaseDocumentID", sqlParams, connString);
                }
                else
                {
                    return 0;
                }

                webClient.Dispose();
                File.Delete(fullFilePath);  // cleanup file
                return onBaseDocumentID;
            
            }
            catch (Exception ex)
            {
                string msg = "";
                string problemFileDir = Path.Combine(this.WorkDir, "problems");
                string fname = Path.Combine(problemFileDir, "onbase-err-" + unixTimestamp.ToString() + "-msg.txt");
                fname = string.Concat(fname.Split(Path.GetInvalidFileNameChars()));

                // Console.WriteLine("writing error to file: " + fname + "  \n");
                msg = "ERROR UPLOADING DOCUMENT: " + ex.Message + " STACK TRACE: " + ex.StackTrace;
                File.WriteAllText(fname, msg);

                
                return 0;   
            }
        }

 
        public string ToXMLDoc(SubmitOnBaseDocumentOnly request)
        {
            XDocument xDoc = new XDocument(new XDeclaration("1.0", "utf-8", null));

            XElement docs = new XElement("Documents");
            docs.Add(new XAttribute("Count", "1"));

            XElement doc = new XElement("Document");
            doc.Add(new XElement("RequestID", request.RequestID.ToString()));
            doc.Add(new XElement("FileTypeID", request.FileTypeID.ToString()));


            doc.Add(new XElement("Image_Blob", Convert.ToBase64String(request.Image_Blob)));
            docs.Add(doc);
            xDoc.Add(docs);

            return xDoc.Declaration.ToString() + xDoc.ToString(SaveOptions.None);
        }

        public string ToXML(SubmitOnBaseDocument request)
        {
            XDocument xDoc = new XDocument(new XDeclaration("1.0", "utf-8", null));

            XElement docs = new XElement("Documents");
            docs.Add(new XAttribute("Count", "1"));

            XElement doc = new XElement("Document");
            doc.Add(new XElement("RequestID", request.RequestID.ToString()));
            doc.Add(new XElement("FileTypeID", request.FileTypeID.ToString()));

            XElement kwList = new XElement("KWList");
            XElement kwTaxID = new XElement("keyword", request.Tax_ID.ToString());
            kwTaxID.Add(new XAttribute("ID", "Tax_ID-NP"));
            kwList.Add(kwTaxID);

            XElement kwRequestType = new XElement("keyword", request.Request_Type.ToString());
            kwRequestType.Add(new XAttribute("ID", "Request_Type-NP"));
            kwList.Add(kwRequestType);

            XElement kwProviderID = new XElement("keyword", request.Provider_ID.ToString());
            kwProviderID.Add(new XAttribute("ID", "Provider_ID-NP"));
            kwList.Add(kwProviderID);

            XElement kwNPI = new XElement("keyword", request.NPI.ToString());
            kwNPI.Add(new XAttribute("ID", "NPI-NP"));
            kwList.Add(kwNPI);

            XElement kwTaxonomy = new XElement("keyword", request.Taxonomy.ToString());
            kwTaxonomy.Add(new XAttribute("ID", "Taxonomy-NP"));
            kwList.Add(kwTaxonomy);

            XElement kwZip5 = new XElement("keyword", request.Zip5.ToString());
            kwZip5.Add(new XAttribute("ID", "Zip5-NP"));
            kwList.Add(kwZip5);

            XElement kwExtZip = new XElement("keyword", request.Extended_Zip.ToString());
            kwExtZip.Add(new XAttribute("ID", "Extended_Zip-NP"));
            kwList.Add(kwExtZip);

            XElement kwRegID = new XElement("keyword", request.PDMS_Reg_ID.ToString());
            kwRegID.Add(new XAttribute("ID", "PDMS_Reg_ID-NP"));
            kwList.Add(kwRegID);

            XElement kwDocType = new XElement("keyword", request.Document_Type.ToString());
            kwDocType.Add(new XAttribute("ID", "Document_Type-NP"));
            kwList.Add(kwDocType);

            XElement kwAppType = new XElement("keyword", request.Application_Type.ToString());
            kwAppType.Add(new XAttribute("ID", "Application_Type-NP"));
            kwList.Add(kwAppType);

            doc.Add(kwList);
            doc.Add(new XElement("Image_Blob", Convert.ToBase64String(request.Image_Blob)));
            docs.Add(doc);
            xDoc.Add(docs);

            return xDoc.Declaration.ToString() + xDoc.ToString(SaveOptions.None);
        }

        public byte[] EncryptRijndael(byte[] data)
        {
            byte[] encryptedData;
            SymmetricAlgorithm algorithm; 

            RijndaelManaged RijndaelEncryptor = new RijndaelManaged();
            RijndaelEncryptor.Key = StringToHex(this.RJkey);
            RijndaelEncryptor.IV = StringToHex(this.RJiv);
            algorithm = RijndaelEncryptor;

            try
            {

                using (ICryptoTransform encryptor = algorithm.CreateEncryptor())
                {
                    // Create the streams used for encryption. 
                    using (MemoryStream msFile = new MemoryStream(data))
                    {
                        using (MemoryStream msEncrypt = new MemoryStream())
                        {
                            using (CryptoStream csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                            {
                                using (StreamWriter swEncrypt = new StreamWriter(csEncrypt))
                                {
                                    byte[] bytearrayinput = new byte[msFile.Length];
                                    msFile.Read(bytearrayinput, 0, bytearrayinput.Length);
                                    csEncrypt.Write(bytearrayinput, 0, bytearrayinput.Length);
                                    //Write all data to the stream.

                                }
                                encryptedData = msEncrypt.ToArray();
                            }
                        }
                    }
                }
                return encryptedData;
            }
            catch (Exception ex)
            {
                /// Handle exception
                return null;
            }
        }

        public byte[] StringToHex(string str)
        {
            int NumberChars = str.Length;
            byte[] bytes = new byte[NumberChars / 2];
            for (int i = 0; i < NumberChars; i += 2)
            {
                bytes[i / 2] = Convert.ToByte(str.Substring(i, 2), 16);
            }
            return bytes;
        }

    }
}
