using MAXIMUS.Core.Libraries;
using MAXIMUS.DataExchange.PDMS.MMISInterface;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;

namespace MAXIMUS.DataExchange.PDMS
{
	public interface IMMISPostProcess<TRequest>
		where TRequest : MMISRequest
	{
		void PostProcess(TRequest request, TransactionData taskData, MMISShared ms, DateTime now, Logging log);
	}


	public abstract class Send835EmailNotificationBase<TRequest> : MMISTransactionStep, IMMISPostProcess<TRequest>
		where TRequest : MMISRequest
	{
		#region Private Members

        EMailNotification _notify;
		string _templateName;
		string _templatesDirectory;
		string _templateFullName;


		#endregion

		#region Constructors

		public Send835EmailNotificationBase(Guid threadID)
			: base(threadID)
		{
			SetUpTemplate();
		}

		#endregion

		
		public abstract void PostProcess(TRequest request, TransactionData taskData, MMISShared ms, DateTime now, Logging log);
		
		#region Helper Methods


		private void SetUpTemplate()
		{
			_templateName = "MMIS835Notification.txt";
			_templatesDirectory = AppSettings.Get("PDMS_SVC_TemplatesPath", string.Empty);
			_templateFullName = _templatesDirectory + "\\" + _templateName;

			
		}


		protected void SendEmailNotification(string organizationName, string medicaidID, DateTime effectiveDate, Logging log)
		{
			try
			{

				Dictionary<string, object> fields = new Dictionary<string, object>();
				fields.Add("PROVIDERNAME", organizationName);
				fields.Add("MEDICAIDID", medicaidID);
				fields.Add("EFFECTIVEDATE", effectiveDate);

				string recipients = AppSettings.Get("MMIS-835-Notification-Email", "AndyHinz@maximus.com");

                _notify = new EMailNotification(_templateFullName, "Provider Requests 835 Setup", recipients, ThreadID);
                _notify.SendNotification(_templateFullName, fields, false);
				//_notify.SendNotification(_templateFullName, string.Empty, "Provider Requests 835 Setup", recipients, fields, false);
			}
			catch (Exception ex)
			{
				string message = string.Format("Error sending 835 Notification Email: {0}", ex);
				log.CreateLogEntry(message, Logging.LogPriority.Error);
			}
		}

		#endregion
	}
}

namespace MAXIMUS.DataExchange.PDMS.MMISPostProcess.IndividualSubmit
{
	public class UpdateStagingAndProvider : MMISTransactionStep, IMMISPostProcess<SubmitWaiverProvider>
	{
		#region Constructors

		public UpdateStagingAndProvider(Guid threadID)
			: base(threadID)
		{

		}

		#endregion

		#region IMMISPostProcess Methods


		public void PostProcess(SubmitWaiverProvider request, TransactionData taskData, MMISShared ms, DateTime now, Logging log)
		{
			// generated by sp_Admin_StoredProcBuilder on Aug 20 2012  1:44PM
			// create parameters objects and fill with values
			List<SqlParameter> parameters = new List<SqlParameter>();

			parameters.Add(SqlParms.CreateParameter("PROVIDER_STAGING_PK", DbType.Int32, taskData.PrimaryKey, true));
            parameters.Add(SqlParms.CreateParameter("PDMS_STATUS_TYPE_ID", DbType.Int32, taskData.PDMSStatus, true));
            parameters.Add(SqlParms.CreateParameter("PROVIDER_STATUS_CHANGE_TYPE_ID", DbType.Int32, Enumerations.ProviderStatusChangeTypeId.MMIS, true));
            parameters.Add(SqlParms.CreateParameter("SAK_TRANS", DbType.String, taskData.SakTransID, true));
            parameters.Add(SqlParms.CreateParameter("CORRELATION_ID", DbType.String, "Submitted", true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, now, false));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, Constants.appPDMSDataExchangeUserId, false));

            DataAccess.ExecuteStoredProcedure("usp_UpdatePDMSToMMISExportRecords", parameters);
		}

		#endregion
	}
}


namespace MAXIMUS.DataExchange.PDMS.MMISPostProcess.WaiverServicesSubmit
{
    public class UpdateStagingAndProvider : MMISTransactionStep, IMMISPostProcess<SubmitWaiverServices>
    {
        #region Constructors

        public UpdateStagingAndProvider(Guid threadID)
            : base(threadID)
        {

        }

        #endregion

        #region IMMISPostProcess Methods


        public void PostProcess(SubmitWaiverServices request, TransactionData taskData, MMISShared ms, DateTime now, Logging log)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();

            parameters.Add(SqlParms.CreateParameter("MMIS_STAGING_WAIVER_SERVICES_ID", DbType.Int32, taskData.PrimaryKey, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, DateTime.Now, false));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, Constants.appPDMSDataExchangeUserId, false));
            parameters.Add(SqlParms.CreateParameter("SAK_TRANS", DbType.String, taskData.SakTransID, true));

            DataAccess.ExecuteStoredProcedure("usp_UpdateMMISStagingWaiverService", parameters);
        }

        #endregion
    }
}

namespace MAXIMUS.DataExchange.PDMS.MMISPostProcess.GroupSubmit
{
	public class UpdateStagingAndProvider : MMISTransactionStep, IMMISPostProcess<SubmitWaiverProvider>
	{
		#region Constructors

		public UpdateStagingAndProvider(Guid threadID)
			: base(threadID)
		{

		}

		#endregion

		#region IMMISPostProcess Methods


		public void PostProcess(SubmitWaiverProvider request, TransactionData taskData, MMISShared ms, DateTime now, Logging log)
		{
            // generated by sp_Admin_StoredProcBuilder on Sep 12 2013 11:07AM
            // create parameters objects and fill with values
            List<SqlParameter> parameters = new List<SqlParameter>();

            parameters.Add(SqlParms.CreateParameter("MMIS_STAGING_GROUP_PK", DbType.Int32, taskData.PrimaryKey, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, DateTime.Now, false));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, Constants.appPDMSDataExchangeUserId, false));
            parameters.Add(SqlParms.CreateParameter("SAK_TRANS", DbType.String, taskData.SakTransID, true));
            parameters.Add(SqlParms.CreateParameter("CORRELATION_ID", DbType.String, string.Empty, true));

            DataAccess.ExecuteStoredProcedure("usp_UpdateMMISStagingGroup", parameters);
		}

		#endregion
	}
}

namespace MAXIMUS.DataExchange.PDMS.MMISPostProcess.IndividualRetrieve
{
	public class UpdateStagingAndProvider : MMISTransactionStep, IMMISPostProcess<RetrieveWaiverProvider>
	{
		#region Constructors

		public UpdateStagingAndProvider(Guid threadID)
			: base(threadID)
		{

		}

		#endregion

		#region IMMISPostProcess Methods


        public void PostProcess(RetrieveWaiverProvider request, TransactionData taskData, MMISShared ms, DateTime now, Logging log)
		{ 
            int pdmsStatus = Constants.PDMSStatusType.Processed;
            string statusCode = Constants.MMISStatusType.Processed.ToString();

            if (AppSettings.Get("MMIS-InterfaceTesting", bool.TrueString).ToLower() == bool.FalseString.ToLower())
            {
                if (!string.IsNullOrEmpty(request.StatusCode))
                {
                    pdmsStatus = Constants.PDMSStatusType.Errors;
                    statusCode = Constants.MMISStatusType.Errors.ToString();
                }
            }
            else
            {
                pdmsStatus = Constants.PDMSStatusType.Processed;
                statusCode = AppSettings.Get("MMIS-TestGroupStatus", Constants.MMISStatusType.Processed.ToString());
            }

            UpdateProvider(Convert.ToInt32(taskData.PrimaryKey), pdmsStatus,request.OrganizationId
                                   ,request.pdmsProviderId, statusCode);
		}

		private void UpdateProvider(int providerStagingPk, int pdmsStatusTypeId, string medicaidId, string providerId, string statusCode)
		{
			// create log object
			string logMsg = String.Format(Constants.LogString.MethodSignature, MethodBase.GetCurrentMethod().DeclaringType.Name, MethodBase.GetCurrentMethod().Name);
			Logging log = new Logging(this.ThreadID, logMsg);

			try
			{
                // generated by sp_Admin_StoredProcBuilder on Aug 14 2012  9:56AM
                // create parameters objects and fill with values
                List<SqlParameter> parameters = new List<SqlParameter>();

                parameters.Add(SqlParms.CreateParameter("PROVIDER_STAGING_PK", DbType.Int32, providerStagingPk, false));
                parameters.Add(SqlParms.CreateParameter("PDMS_STATUS_TYPE_ID", DbType.Int32, pdmsStatusTypeId, false));
                parameters.Add(SqlParms.CreateParameter("PROVIDER_STATUS_CHANGE_TYPE_ID", DbType.Int32, Enumerations.ProviderStatusChangeTypeId.MMIS, false));
                parameters.Add(SqlParms.CreateParameter("MEDICARE_ID", DbType.String, medicaidId.Trim(), true));
                parameters.Add(SqlParms.CreateParameter("STATUS_CODE", DbType.String, statusCode.Trim(), true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, DateTime.Now, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, Constants.appPDMSDataExchangeUserId, true));

                DataAccess.ExecuteStoredProcedure("usp_UpdatePDMSToMMISExportedRecords", parameters);
			}
			catch (Exception ex)
			{
				throw CoreException.ThrowException(this.ThreadID, ex);
			}
		}

		#endregion
	}
}

namespace MAXIMUS.DataExchange.PDMS.MMISPostProcess.GroupRetrieve
{
	public class UpdateStagingAndProvider : MMISTransactionStep, IMMISPostProcess<RetrieveWaiverProvider>
	{
		#region Constructors

		public UpdateStagingAndProvider(Guid threadID)
			: base(threadID)
		{

		}

		#endregion

		#region IMMISPostProcess Methods


		public void PostProcess(RetrieveWaiverProvider request, TransactionData taskData, MMISShared ms, DateTime now, Logging log)
		{
		    List<SqlParameter> parameters = new List<SqlParameter>();
            string errorCode = string.Empty;
            string statusCode = Constants.MMISStatusType.Processed.ToString();

            if (AppSettings.Get("MMIS-InterfaceTesting", bool.TrueString).ToLower() == bool.FalseString.ToLower())
            {
                if (!string.IsNullOrEmpty(request.StatusCode))
                {
                    statusCode = Constants.MMISStatusType.Errors.ToString();
                    errorCode = request.StatusCode.Split(',').FirstOrDefault();
                }
            }
            else
            {
                errorCode = AppSettings.Get("MMIS-TestGroupErrors", string.Empty);
                statusCode = AppSettings.Get("MMIS-TestGroupStatus", Constants.MMISStatusType.Processed.ToString());
            }

            parameters.Add(SqlParms.CreateParameter("mmis_staging_group_pk", DbType.Int32, taskData.PrimaryKey, true));
            parameters.Add(SqlParms.CreateParameter("medicaid_id", DbType.String, request.OrganizationId, true));
            parameters.Add(SqlParms.CreateParameter("last_modified_date_time", DbType.DateTime, now, false));
            parameters.Add(SqlParms.CreateParameter("last_modified_user", DbType.Guid, Constants.appPDMSDataExchangeUserId, false));
            parameters.Add(SqlParms.CreateParameter("STATUS_CODE", DbType.Int32, statusCode, true));
            parameters.Add(SqlParms.CreateParameter("SAK_TRANS", DbType.String, taskData.SakTransID, true));
            parameters.Add(SqlParms.CreateParameter("ERROR_CODE", DbType.String, errorCode, true));

            DataAccess.ExecuteStoredProcedure("usp_updatemmisstaginggroup", parameters);
		}
		#endregion
	}
}

namespace MAXIMUS.DataExchange.PDMS.MMISPostProcess.WaiverServicesRetrieve
{
    public class UpdateStagingAndProvider : MMISTransactionStep, IMMISPostProcess<RetrieveWaiverServices>
    {
        #region Constructors

        public UpdateStagingAndProvider(Guid threadID)
            : base(threadID)
        {

        }

        #endregion

        #region IMMISPostProcess Methods

        public void PostProcess(RetrieveWaiverServices request, TransactionData taskData, MMISShared ms, DateTime now, Logging log)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            string errorCode = string.Empty;
            string statusCode = Constants.MMISStatusType.Processed.ToString();
            string medicaidid = string.Empty;

            try
            {
                if (AppSettings.Get("MMIS-InterfaceTesting", bool.TrueString).ToLower() == bool.FalseString.ToLower())
                {
                    if (!string.IsNullOrEmpty(request.StatusCode))
                    {
                        statusCode = Constants.MMISStatusType.Errors.ToString();
                        errorCode = request.StatusCode.Split(',').FirstOrDefault();
                    }
                }
                else
                {
                    errorCode = AppSettings.Get("MMIS-TestGroupErrors", string.Empty);
                    statusCode = AppSettings.Get("MMIS-TestGroupStatus", Constants.MMISStatusType.Processed.ToString());
                }

                parameters.Add(SqlParms.CreateParameter("MMIS_STAGING_WAIVER_SERVICES_ID", DbType.Int32, taskData.PrimaryKey, true));
                parameters.Add(SqlParms.CreateParameter("ORGANIZATION_ID", DbType.String, request.OrganizationId, true));
                parameters.Add(SqlParms.CreateParameter("last_modified_date_time", DbType.DateTime, now, false));
                parameters.Add(SqlParms.CreateParameter("last_modified_user", DbType.Guid, Constants.appPDMSDataExchangeUserId, false));
                parameters.Add(SqlParms.CreateParameter("STATUS_CODE", DbType.Int32, statusCode.Trim(), true));
                parameters.Add(SqlParms.CreateParameter("SAK_TRANS", DbType.String, taskData.SakTransID, true));
                // todo fill the following after we get error codes from nfocus
                parameters.Add(SqlParms.CreateParameter("ERROR_CODE", DbType.String, errorCode, true));

                DataAccess.ExecuteStoredProcedure("usp_UpdateMMISStagingWaiverService", parameters);
            }
            catch (Exception ex)
            {
                throw CoreException.ThrowException(this.ThreadID, ex);
            }
        }

        #endregion
    }
}