using MAXIMUS.Core.Libraries;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;


namespace MAXIMUS.DataExchange.PDMS
{
	public interface IMMISLoadDataSet
	{
		DataSet LoadDataSet();
		int GetRowCount(DataSet ds);
	}

}
namespace MAXIMUS.DataExchange.PDMS.MMISLoadDataSet
{
	public class IndividualPendingStagingRecords : MMISTransactionStep, IMMISLoadDataSet
	{
		#region Constants

		const string TABLE_NAME_PROVIDERS = "PROVIDER_STAGING";
		const string dbtAddr = "ADDRESS_STAGING";
		const string dbrProv2Addrs = TABLE_NAME_PROVIDERS + "2" + dbtAddr;
		const string dbfPK = "PROVIDER_STAGING_PK";

		#endregion

		#region Properties

		public int TransactionTypeID { get; set; }

		#endregion

		#region Constructors

		public IndividualPendingStagingRecords(Guid threadID, int transactionTypeID)
			: base(threadID)
		{
			this.TransactionTypeID = transactionTypeID;
		}

		#endregion

		#region IMMISLoadDataSet Methods

		public DataSet LoadDataSet()
		{
			DataSet ds = new DataSet();

			List<SqlParameter> lstParams = new List<SqlParameter>();

			if (this.TransactionTypeID == Constants.TransactionType.SendDIDDAddProviderUpdatetoMMIS ||
				this.TransactionTypeID == Constants.TransactionType.SendDIDDTerminateProviderUpdatetoMMIS)
			{
				lstParams.Add(SqlParms.CreateParameter("GET_DIDD_TRANSACTIONS", DbType.Boolean, true, true));
				lstParams.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, this.TransactionTypeID, true));
			}
			else if (this.TransactionTypeID == Constants.TransactionType.SendDCSAddProviderUpdatetoMMIS ||
				this.TransactionTypeID == Constants.TransactionType.SendDCSTerminateProviderUpdatetoMMIS)
			{
				lstParams.Add(SqlParms.CreateParameter("GET_DCS_TRANSACTIONS", DbType.Boolean, true, true));
				lstParams.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, this.TransactionTypeID, true));
			}

			ds = DataAccess.ExecuteStoredProcedure("usp_SelectPDMSToMMISExportRecords", lstParams, (TABLE_NAME_PROVIDERS + Constants.pluralEnding));

			ds.Tables[0].TableName = TABLE_NAME_PROVIDERS;
			ds.Tables[1].TableName = dbtAddr;

			DataRelation relation;
			relation = new DataRelation(dbrProv2Addrs, ds.Tables[TABLE_NAME_PROVIDERS].Columns[dbfPK]
				, ds.Tables[dbtAddr].Columns[dbfPK]);
			ds.Relations.Add(relation);


			return ds;
		}

		public int GetRowCount(DataSet ds)
		{
			if (ds == null || !ds.Tables.Contains(TABLE_NAME_PROVIDERS))
			{
				throw new Exception("Invalid DataSet in GetRowCount().");
			}

			return ds.Tables[TABLE_NAME_PROVIDERS].Rows.Count;
		}

		#endregion
	}

	public class GroupStagingRecords : MMISTransactionStep, IMMISLoadDataSet
	{
		#region Constants

		internal const string TABLE_NAME_GROUPS = "Groups";
		internal const string TABLE_NAME_ADDRESSES = "Addresses";
		internal const string TABLE_NAME_AFFILIATES = "Affiliates";
		internal const string RELATION_NAME_GROUPS_TO_ADDRESSES = TABLE_NAME_GROUPS + "2" + TABLE_NAME_ADDRESSES;
		internal const string RELATION_NAME_GROUPS_TO_AFFILIATES = TABLE_NAME_GROUPS + "2" + TABLE_NAME_AFFILIATES;
		internal const string PRIMARY_KEY_NAME_STAGING_GROUP = "MMIS_STAGING_GROUP_PK";


		#endregion

		#region Properties

		public int TransactionTypeID { get; set; }
		public bool GetSubmittedRecords { get; set; }

		#endregion

		#region Constructors

		public GroupStagingRecords(Guid threadID, int transactionTypeID, bool getSubmittedRecords) : base(threadID)
		{
			this.TransactionTypeID = transactionTypeID;
			this.GetSubmittedRecords = getSubmittedRecords;
		}

		#endregion

		#region IMMISLoadDataSet Members

		public DataSet LoadDataSet()
		{
			string logProcessName = String.Format(Constants.LogString.MethodSignature, MethodBase.GetCurrentMethod().DeclaringType.Name, MethodBase.GetCurrentMethod().Name);
			DataSet ds;

			try
			{
				if (TransactionTypeID == Constants.TransactionType.ResendAffiliationNotifications)
				{
					ds = DataAccess.ExecuteStoredProcedure("usp_ReprocessAffiliationEmails", "Groups");
				}
				else
				{
					// generated by sp_Admin_StoredProcBuilder on Sep  9 2013  1:09PM
					// create parameters objects and fill with values
					List<SqlParameter> parameters = new List<SqlParameter>();

					parameters.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, TransactionTypeID, true));
					parameters.Add(SqlParms.CreateParameter("SUBMITTED", DbType.Boolean, GetSubmittedRecords, true));

					ds = DataAccess.ExecuteStoredProcedure("usp_SelectMMISStagingGroups", parameters, "Groups");
				}

				ds.Tables[0].TableName = TABLE_NAME_GROUPS;
				ds.Tables[1].TableName = TABLE_NAME_ADDRESSES;	
				ds.Tables[2].TableName = TABLE_NAME_AFFILIATES;

				DataRelation relation;
				relation = new DataRelation(RELATION_NAME_GROUPS_TO_ADDRESSES, ds.Tables[TABLE_NAME_GROUPS].Columns[PRIMARY_KEY_NAME_STAGING_GROUP]
					, ds.Tables[TABLE_NAME_ADDRESSES].Columns[PRIMARY_KEY_NAME_STAGING_GROUP]);
				ds.Relations.Add(relation);
				relation = new DataRelation(RELATION_NAME_GROUPS_TO_AFFILIATES, ds.Tables[TABLE_NAME_GROUPS].Columns[PRIMARY_KEY_NAME_STAGING_GROUP]
					, ds.Tables[TABLE_NAME_AFFILIATES].Columns[PRIMARY_KEY_NAME_STAGING_GROUP]);
				ds.Relations.Add(relation);
			}
			catch (Exception ex)
			{
				throw CoreException.ThrowException(this.ThreadID, ex, logProcessName);
			}
			return ds;
		}

		#endregion


		public int GetRowCount(DataSet ds)
		{
			if (ds == null || !ds.Tables.Contains(TABLE_NAME_GROUPS))
			{
				throw new Exception("Invalid DataSet in GetRowCount().");
			}

			return ds.Tables[TABLE_NAME_GROUPS].Rows.Count;
		}
	}

    public class WaiverServicesStagingRecords : MMISTransactionStep, IMMISLoadDataSet
    {
        #region Constants

        const string dbfPK = "MMIS_STAGING_WAIVER_SERVICES_ID";
        const string TABLE_NAME = "MMIS_STAGING_WAIVER_SERVICES";
		
        #endregion

        #region Properties

        public int TransactionTypeID { get; set; }
        public bool SubmittedRecords { get; set; }

        #endregion

        #region Constructors

        public WaiverServicesStagingRecords(Guid threadID, int transactionTypeID, bool submittedRecords)
            : base(threadID)
        {
            this.TransactionTypeID = transactionTypeID;
            this.SubmittedRecords = submittedRecords;
        }

        #endregion

        #region IMMISLoadDataSet Methods

        public DataSet LoadDataSet()
        {
            DataSet ds = new DataSet();

            List<SqlParameter> lstParams = new List<SqlParameter>();

            lstParams.Add(SqlParms.CreateParameter("SUBMITTED", DbType.Boolean, SubmittedRecords, true));
            lstParams.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, this.TransactionTypeID, true));

            ds = DataAccess.ExecuteStoredProcedure("usp_SelectMMISStagingWaiverServices", lstParams, TABLE_NAME);

            ds.Tables[0].TableName = TABLE_NAME;
				
            return ds;
        }

        public int GetRowCount(DataSet ds)
        {
            if (ds == null || !ds.Tables.Contains(TABLE_NAME))
            {
                throw new Exception("Invalid DataSet in GetRowCount().");
            }

            return ds.Tables[TABLE_NAME].Rows.Count;
        }

        #endregion
    }

	public class DCSDIDDAffiliationStagingRecords : MMISTransactionStep, IMMISLoadDataSet
	{
		#region Constants

		internal const string DATASET_NAME_GROUPS = "Groups";
		internal const string TABLE_NAME_GROUPS = "Groups";
		internal const string TABLE_NAME_AFFILIATES = "Affiliates";
		internal const string RELATION_NAME_GROUPS_TO_AFFILIATES = TABLE_NAME_GROUPS + "2" + TABLE_NAME_AFFILIATES;
		internal const string PRIMARY_KEY_NAME_STAGING_GROUP = "MMIS_STAGING_GROUP_PK";


		#endregion

		#region Properties

		public int TransactionTypeID { get; set; }
		public bool GetSubmittedRecords { get; set; }

		#endregion

		#region Constructors

		public DCSDIDDAffiliationStagingRecords(Guid threadID, int transactionTypeID, bool getSubmittedRecords)
			: base(threadID)
		{
			this.TransactionTypeID = transactionTypeID;
			this.GetSubmittedRecords = getSubmittedRecords;
		}

		#endregion

		#region IMMISLoadDataSet Members

		public DataSet LoadDataSet()
		{
			string logProcessName = String.Format(Constants.LogString.MethodSignature, MethodBase.GetCurrentMethod().DeclaringType.Name, MethodBase.GetCurrentMethod().Name);
			DataSet ds;

			try
			{
				
					// generated by sp_Admin_StoredProcBuilder on Sep  9 2013  1:09PM
					// create parameters objects and fill with values
					List<SqlParameter> parameters = new List<SqlParameter>();

					parameters.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, TransactionTypeID, true));
					parameters.Add(SqlParms.CreateParameter("SUBMITTED", DbType.Boolean, GetSubmittedRecords, true));

					ds = DataAccess.ExecuteStoredProcedure("usp_SelectMMISStagingEligibilityGroups", parameters, DATASET_NAME_GROUPS);
				

				ds.Tables[0].TableName = TABLE_NAME_GROUPS;
				ds.Tables[1].TableName = TABLE_NAME_AFFILIATES;

				DataRelation relation;
				relation = new DataRelation(RELATION_NAME_GROUPS_TO_AFFILIATES, ds.Tables[TABLE_NAME_GROUPS].Columns[PRIMARY_KEY_NAME_STAGING_GROUP]
					, ds.Tables[TABLE_NAME_AFFILIATES].Columns[PRIMARY_KEY_NAME_STAGING_GROUP]);
				ds.Relations.Add(relation);
			}
			catch (Exception ex)
			{
				throw CoreException.ThrowException(this.ThreadID, ex, logProcessName);
			}
			return ds;
		}

		#endregion


		public int GetRowCount(DataSet ds)
		{
			if (ds == null || !ds.Tables.Contains(TABLE_NAME_GROUPS))
			{
				throw new Exception("Invalid DataSet in GetRowCount().");
			}

			return ds.Tables[TABLE_NAME_GROUPS].Rows.Count;
		}
	}

	public class IndividualSubmittedStagingRecords : MMISTransactionStep, IMMISLoadDataSet
	{
		#region Constants

		const string TABLE_NAME_PROVIDERS = "PROVIDER_STAGING";
		const string dbtAddr = "ADDRESS_STAGING";
		const string dbrProv2Addrs = TABLE_NAME_PROVIDERS + "2" + dbtAddr;
		const string dbfPK = "PROVIDER_STAGING_PK";

		#endregion

		#region Properties

		public int TransactionTypeID { get; set; }

		#endregion

		#region Constructors

		public IndividualSubmittedStagingRecords(Guid threadID, int transactionTypeID)
			: base(threadID)
		{
			this.TransactionTypeID = transactionTypeID;
		}

		#endregion

		#region IMMISLoadDataSet Methods

		public DataSet LoadDataSet()
		{
			DataSet ds = new DataSet();


			List<SqlParameter> lstParams = new List<SqlParameter>();

			if (this.TransactionTypeID == Constants.TransactionType.SendDIDDAddProviderUpdatetoMMIS ||
				this.TransactionTypeID == Constants.TransactionType.SendDIDDTerminateProviderUpdatetoMMIS)
			{
				lstParams.Add(SqlParms.CreateParameter("GET_DIDD_TRANSACTIONS", DbType.Boolean, true, true));
				lstParams.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, TransactionTypeID, true));
			}
			else if (this.TransactionTypeID == Constants.TransactionType.SendDCSAddProviderUpdatetoMMIS ||
				this.TransactionTypeID == Constants.TransactionType.SendDCSTerminateProviderUpdatetoMMIS)
			{
				lstParams.Add(SqlParms.CreateParameter("GET_DCS_TRANSACTIONS", DbType.Boolean, true, true));
				lstParams.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, TransactionTypeID, true));
			}

			ds = DataAccess.ExecuteStoredProcedure("usp_SelectPDMSToMMISExportedRecords", lstParams, (TABLE_NAME_PROVIDERS + Constants.pluralEnding));

			ds.Tables[0].TableName = TABLE_NAME_PROVIDERS;

			return ds;
		}

		public int GetRowCount(DataSet ds)
		{
			if (ds == null || !ds.Tables.Contains(TABLE_NAME_PROVIDERS))
			{
				throw new Exception("Invalid DataSet in GetRowCount().");
			}

			return ds.Tables[TABLE_NAME_PROVIDERS].Rows.Count;
		}

		#endregion
	}
}
