<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>panda_face.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="panda_face.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\" />
    <Folder Include="DatabaseScripts\" />
    <Folder Include="ShellScripts\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ShellScripts\CheckoutDEVP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CheckoutDEVP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CheckoutUATP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CheckoutUATP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CommitVersionChangeP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CommitVersionChangeP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateBranchUATP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateBranchUATP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateDocumentation.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateDocumentationMain.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateDocumentationP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateDocumentationP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateDocumentationSub.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateDocumentationSubP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateDocumentationSubP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateFinalTagP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateFinalTagP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateInitialTagP3.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\CreateInitialTagP4.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\GitScript.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ShellScripts\GitScriptMain.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	<None Update="DatabaseScripts\dbo.AppInformation.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
