IF ISNULL(OBJECTPROPERTY(object_id('CLAIM_UNITSOFMEASUREMENT'), N'IsTable'),0) = 0
BEGIN

	SET ANSI_NULLS ON

	SET QUOTED_IDENTIFIER ON

	SET ANSI_PADDING ON
	
	CREATE TABLE [dbo].[CLAIM_UNITSOFMEASUREMENT](
		[CLAIM_UNITSOFMEASUREMENT_ID] [int] IDENTITY(1,1) NOT NULL,
		[CLAIM_UNITSOFMEASUREMENT_CODE] [varchar](15) NULL,
		[CLAIM_UNITSOFMEASUREMENT_DESC] [varchar](258) NULL,
		[LAST_MODIFIED_DATE_TIME] [datetime] NOT NULL,
		[LAST_MODIFIED_USER] [uniqueidentifier] NOT NULL,
	 CONSTRAINT [PK_CLAIM_UNITSOFMEASUREMENT_ID] PRIMARY KEY CLUSTERED 
	(
		[CLAIM_UNITSOFMEASUREMENT_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]


	ALTER TABLE [dbo].[CLAIM_UNITSOFMEASUREMENT] ADD  CONSTRAINT [DF_CLAIM_UNITSOFMEASUREMENT_LAST_MODIFIED_DATE_TIME]  DEFAULT (getdate()) FOR [LAST_MODIFIED_DATE_TIME]
	
  EXEC sp_AutoGenerateAuditTableAndTrigger 'CLAIM_UNITSOFMEASUREMENT'
END