/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulatePROVIDER_CATEGORY_TYPE]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulatePROVIDER_CATEGORY_TYPE]','P') is not null
DROP PROCEDURE [dbo].DCConv_LkUp_PopulatePROVIDER_CATEGORY_TYPE
GO
/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulatePROVIDER_CATEGORY_TYPE]    Script Date: 8/1/2016 3:13:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the PROVIDER_CATEGORY_TYPE
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulatePROVIDER_CATEGORY_TYPE] 
	@pin_run_reference_time datetime
AS
BEGIN
 -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DELETE FROM [dbo].[PROVIDER_CATEGORY_TYPE];

	INSERT [dbo].[PROVIDER_CATEGORY_TYPE] ([PROVIDER_CATEGORY_TYPE_ID], [PROVIDER_CATEGORY_TYPE_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [IsActive_PHASEII], [MMIS_PROVIDER_CATEGORY_TYPE_ID]) VALUES (0, N'No Match', CAST(0x0000A4B900000000 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 1, NULL)
INSERT [dbo].[PROVIDER_CATEGORY_TYPE] ([PROVIDER_CATEGORY_TYPE_ID], [PROVIDER_CATEGORY_TYPE_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [IsActive_PHASEII], [MMIS_PROVIDER_CATEGORY_TYPE_ID]) VALUES (1, N'Individual/Solo', CAST(0x0000A4800115C1DE AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 1, N'I')
INSERT [dbo].[PROVIDER_CATEGORY_TYPE] ([PROVIDER_CATEGORY_TYPE_ID], [PROVIDER_CATEGORY_TYPE_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [IsActive_PHASEII], [MMIS_PROVIDER_CATEGORY_TYPE_ID]) VALUES (2, N'Group/Institution', CAST(0x0000A4800115C1DE AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 1, N'G')
INSERT [dbo].[PROVIDER_CATEGORY_TYPE] ([PROVIDER_CATEGORY_TYPE_ID], [PROVIDER_CATEGORY_TYPE_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [IsActive_PHASEII], [MMIS_PROVIDER_CATEGORY_TYPE_ID]) VALUES (3, N'Facility', CAST(0x0000A4800115C1DE AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 1, N'F')
INSERT [dbo].[PROVIDER_CATEGORY_TYPE] ([PROVIDER_CATEGORY_TYPE_ID], [PROVIDER_CATEGORY_TYPE_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [IsActive_PHASEII], [MMIS_PROVIDER_CATEGORY_TYPE_ID]) VALUES (4, N'Non-Medical Provider', CAST(0x0000A4800115C1DE AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 1, NULL)
INSERT [dbo].[PROVIDER_CATEGORY_TYPE] ([PROVIDER_CATEGORY_TYPE_ID], [PROVIDER_CATEGORY_TYPE_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [IsActive_PHASEII], [MMIS_PROVIDER_CATEGORY_TYPE_ID]) VALUES (5, N'Pharmacy', CAST(0x0000A4800115C1DE AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 1, N'P')
INSERT [dbo].[PROVIDER_CATEGORY_TYPE] ([PROVIDER_CATEGORY_TYPE_ID], [PROVIDER_CATEGORY_TYPE_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [IsActive_PHASEII], [MMIS_PROVIDER_CATEGORY_TYPE_ID]) VALUES (6, N'Group Member Profile', CAST(0x0000A4B900DDA76A AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 1, N'I')


END

GO
