/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE]','P') is not null
DROP PROCEDURE [dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] 
	@pin_run_reference_time datetime
AS
BEGIN
 -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DELETE FROM [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE];

	SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ON 

INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (1, 1, 1, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (2, 1, 1, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (3, 2, 1, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (4, 2, 1, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (5, 3, 1, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (6, 3, 1, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (7, 4, 1, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (8, 4, 1, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (9, 5, 1, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (10, 5, 1, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (11, 1, 6, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (12, 1, 6, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (13, 2, 6, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (14, 2, 6, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (15, 3, 6, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (16, 3, 6, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (17, 4, 6, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (18, 4, 6, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (19, 5, 6, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (20, 5, 6, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A4B900DDD651 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (21, 1, 5, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A5320182BAB0 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (22, 1, 5, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A5320182BAB0 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (27, 4, 5, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A5320182BAB0 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (28, 4, 5, 3, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A5320182BAB0 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (29, 1, 1, 2, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (30, 1, 1, 3, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (31, 2, 1, 2, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (32, 2, 1, 3, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
--INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (33, 3, 1, 2, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0) // per Dhivya
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (34, 3, 1, 3, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (35, 4, 1, 2, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (36, 4, 1, 3, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (37, 5, 1, 2, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (38, 5, 1, 3, 21, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (39, 1, 1, 2, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (40, 1, 1, 3, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (41, 2, 1, 2, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (42, 2, 1, 3, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (43, 3, 1, 2, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (44, 3, 1, 3, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (45, 4, 1, 2, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (46, 4, 1, 3, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (47, 5, 1, 2, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (48, 5, 1, 3, 22, 3, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)



IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	(SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID, PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, 
	IS_GROUP_ACTIVITY,
	 IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES 
	(49, 3, 15, 3, 22, 2, 1, 1, 0, 0, 11, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END


IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 15 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 15 AND PROVIDER_RISK_LEVEL_ID = 3
END

IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 15 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] 
	([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) 
	VALUES 
	(50, 3, 15, 2, 15, 3, 1, 1, 0, 0, 1, CAST(0x0000A64100DD8F36 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] OFF;



-- Remove some records just inserted
DELETE FROM  SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_RISK_LEVEL_ID = 2 AND SCREENING_ACTIVITY_TYPE_ID = 21;

-- More from Diwakar DeltaafterRun.sql script
UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE SET SCREENING_ACTIVITY_STATUS_ID = 2 WHERE SCREENING_ACTIVITY_TYPE_ID = 22; -- Site visit

DELETE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3 and PROVIDER_CATEGORY_TYPE_ID != 1; -- Background check

DELETE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3;

-- SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ON;

-- INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (60, 1, 1, 2, 8, 3, 1, 0, 0, 1, 11, CAST(N'2016-08-12 03:35:24.150' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0);
-- INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (61, 2, 1, 2, 8, 3, 1, 0, 0, 1, 11, CAST(N'2016-08-12 03:35:24.150' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0);
-- INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] ([SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [PROVIDER_RISK_LEVEL_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [IS_GROUP_ACTIVITY], [IS_INDIVIDUAL_ACTIVITY], [IS_OWNER_ACTIVITY], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID]) VALUES (62, 3, 1, 2, 8, 3, 1, 0, 0, 1, 11, CAST(N'2016-08-12 03:35:24.150' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0);

-- SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE] OFF;



	--@pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d'
-- From Ben 10/24 Start

/**********CRIMINAL BACKGROUND CHECK**********/

/* 
 * Insert Criminal Background Check Verification for Individual, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check for Moderate Risk providers
 */

IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2
END

/* 
 * Insert Criminal Background Check Verification for Individual, High Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Added Background check verification for only Individual High Risk providers
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (1, 1, 3, 21, 2, 1, 0, 1, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Delete Criminal Background Check Verification for Group, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check for Moderate Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2
END

/* 
 * Insert Criminal Background Check Verification for Group, High Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1596 - Removed Background check verification for GROUP High Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3
END

/* 
 * Delete Criminal Background Check Verification for Facility, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check verification for Moderate Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2
END

/* 
 * Insert Criminal Background Check Verification for Facility, High Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check verification for FACILITY High Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3
END

/* 
 * Delete Criminal Background Check Verification for Non-Medical, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check for Moderate Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2
END

/* 
 * Insert Criminal Background Check Verification for Non-Medical, High Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check verification for NON-MEDICAL High Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3
END

/* 
 * Delete Criminal Background Check Verification for Pharmacy, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check for Moderate Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 2
END

/* 
 * Insert Criminal Background Check Verification for Pharmacy, High Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed Background check verification for NON-MEDICAL High Risk providers
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 21 AND PROVIDER_RISK_LEVEL_ID = 3
END

/********SITE VISIT**********/
/* 
 * Insert Site Visit Verification for Individual, Moderate Risk provider, new reg workflow
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	SET SCREENING_ACTIVITY_STATUS_ID = 2
	WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2
END
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (1, 1, 2, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Individual, High Risk provider, new reg workflow
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (1, 1, 3, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Group, Moderate Risk provider, new reg workflow
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	SET SCREENING_ACTIVITY_STATUS_ID = 2
	WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2
END
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (2, 1, 2, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Group, High Risk provider, new reg workflow
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (2, 1, 3, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Facility, Moderate Risk provider, new reg workflow
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	SET SCREENING_ACTIVITY_STATUS_ID = 2
	WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2
END
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (3, 1, 2, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Facility, High Risk provider, new reg workflow
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (3, 1, 3, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Non-Medical, Moderate Risk provider, new reg workflow
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	SET SCREENING_ACTIVITY_STATUS_ID = 2
	WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2
END
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (4, 1, 2, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Non-Medical, High Risk provider, new reg workflow
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 4 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (4, 1, 3, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Pharmacy, Moderate Risk provider, new reg workflow
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	SET SCREENING_ACTIVITY_STATUS_ID = 2
	WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2
END
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (5, 1, 2, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Pharmacy, High Risk provider, new reg workflow
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (5, 1, 3, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Facility, Moderate Risk provider, EPD workflow
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	SET SCREENING_ACTIVITY_STATUS_ID = 2
	WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2
END
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (3, 15, 2, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/* 
 * Insert Site Visit Verification for Facility, High Risk provider, EPD workflow
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 22 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (3, 15, 3, 22, 2, 1, 1, 0, 0, 11, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/**********PECOS VERIFICATION**********/
/*
 * Change category from 1 (Individual provider) to 15 (Individual owner)
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 15 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 8 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	UPDATE SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE
	SET PROVIDER_CATEGORY_TYPE_ID = 1
	WHERE PROVIDER_CATEGORY_TYPE_ID = 15
	AND WORKFLOW_ID = 1 
	AND SCREENING_ACTIVITY_TYPE_ID = 8 
	AND PROVIDER_RISK_LEVEL_ID = 2
END

/* 
 * Delete PECOS Verification for Individual, Owner, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed PECOS check for owner screening
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 8 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE 
	WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 8 AND PROVIDER_RISK_LEVEL_ID = 2

END

/* 
 * Delete PECOS Verification for Group, Owner, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed PECOS check for owner screening
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 8 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE 
	WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 8 AND PROVIDER_RISK_LEVEL_ID = 2

END

/* 
 * Delete PECOS Verification for Facility, Owner, Moderate Risk provider, new reg workflow
 * 10/12/2016 - BO - DCPDMS-1577 - Removed PECOS check for owner screening
 */
IF EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 8 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	DELETE FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE 
	WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 1 AND SCREENING_ACTIVITY_TYPE_ID = 8 AND PROVIDER_RISK_LEVEL_ID = 2

END

/*SITE VISIT*/
/*
 * Insert Site Visit for EPD workflow (Medium Risk)
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 15 AND PROVIDER_RISK_LEVEL_ID = 2)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (3, 15, 2, 15, 3, 1, 1, 0, 0, 1, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END

/*
 * Insert Site Visit for EPD workflow (High Risk)
 */
IF NOT EXISTS (SELECT * FROM SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND WORKFLOW_ID = 15 AND SCREENING_ACTIVITY_TYPE_ID = 15 AND PROVIDER_RISK_LEVEL_ID = 3)
BEGIN
	INSERT INTO SCREENING_ACTIVITY_RISK_LEVEL_TEMPLATE(PROVIDER_CATEGORY_TYPE_ID, WORKFLOW_ID, PROVIDER_RISK_LEVEL_ID, SCREENING_ACTIVITY_TYPE_ID, SCREENING_ACTIVITY_STATUS_ID, IS_ACTIVE, IS_GROUP_ACTIVITY, IS_INDIVIDUAL_ACTIVITY, IS_OWNER_ACTIVITY, DISPLAY_ORDER, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, REFERRAL_REQUIRED, SCREENING_EVENT_TYPE_ID)
	VALUES (3, 15, 3, 15, 3, 1, 1, 0, 0, 1, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0)
END
-- From Ben 10/24 End

END

GO
