
/****** Object:  StoredProcedure [dbo].[DCConv_Add_TAXONOMY_TYPE]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_Add_TAXONOMY_TYPE]','P') is not null
DROP PROCEDURE [dbo].[DCConv_Add_TAXONOMY_TYPE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Andrew Zovistoski
-- Create date: 08/29/2016
-- Description:	Loads additional taxonomy types as needed
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_Add_TAXONOMY_TYPE] 
(
	@pin_conv_run_time datetime	
)
AS
BEGIN

-- From Khan  RETIRED
--SELECT PROVIDER_TYPE_ID, PROVIDER_TYPE_ABBREVIATION, PROVIDER_CATEGORY_TYPE_ID
--INTO #tmp
--FROM PROVIDER_TYPE
--WHERE PROVIDER_TYPE_ID NOT IN (SELECT DISTINCT PROVIDER_TYPE_ID FROM TAXONOMY_TYPE)
--AND APPLICATION_TYPE_ID != 1

 
--INSERT TAXONOMY_TYPE
--SELECT  x.SPECIALTY_TYPE_ID,
--        t.PROVIDER_TYPE_ID,
--        x.TAXONOMY_CODE,
--        x.TAXONOMY_NAME,
--        x.EXPIRATION_DATE,
--        x.LAST_MODIFIED_DATE_TIME,
--        x.LAST_MODIFIED_USER,
--        x.MMIS_SPECIALTY_TYPE_ID,
--        x.NPI_REQUIRED
--FROM #TMP t JOIN (SELECT PROVIDER_TYPE_ABBREVIATION, MAX(PROVIDER_TYPE_ID) PROVIDER_TYPE_ID
--				  FROM PROVIDER_TYPE
--				  WHERE PROVIDER_TYPE_ID NOT IN (SELECT PROVIDER_TYPE_ID FROM #TMP)
--				  GROUP BY PROVIDER_TYPE_ABBREVIATION) AS m 
--ON t.PROVIDER_TYPE_ABBREVIATION = m.PROVIDER_TYPE_ABBREVIATION
--JOIN TAXONOMY_TYPE x ON x.PROVIDER_TYPE_ID = m.PROVIDER_TYPE_ID;

WITH baseList AS 
(	select distinct b.MMIS_Provider_Type_ID, a.Specialty_Type_ID, a.Taxonomy_Code, a.Taxonomy_Name, a.MMIS_Specialty_Type_ID, a.NPI_Required
	from TAXONOMY_TYPE a
	join PROVIDER_TYPE b on a.Provider_Type_ID = b.Provider_Type_ID
	where b.Application_Type_ID = 1
	)
INSERT TAXONOMY_TYPE 
 ([SPECIALTY_TYPE_ID], [PROVIDER_TYPE_ID], [TAXONOMY_CODE], [TAXONOMY_NAME], [EXPIRATION_DATE],
  [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [MMIS_SPECIALTY_TYPE_ID], [NPI_REQUIRED])
SELECT a.SPECIALTY_TYPE_ID, b.[PROVIDER_TYPE_ID], a.[TAXONOMY_CODE], a.[TAXONOMY_NAME], '12/31/9999' AS [EXPIRATION_DATE]
		, @pin_conv_run_time as [LAST_MODIFIED_DATE_TIME], dbo.fn_GetUniqueGUID(2) AS [LAST_MODIFIED_USER], a.[MMIS_SPECIALTY_TYPE_ID]
		,a.[NPI_REQUIRED]
FROM baseList a
JOIN PROVIDER_TYPE b on a.MMIS_Provider_Type_ID = b.MMIS_Provider_Type_ID
WHERE b.Application_Type_ID <> 1
EXCEPT
SELECT [SPECIALTY_TYPE_ID]
		,[PROVIDER_TYPE_ID]
		,[TAXONOMY_CODE]
		,[TAXONOMY_NAME]
		,[EXPIRATION_DATE]
		,[LAST_MODIFIED_DATE_TIME]
		,[LAST_MODIFIED_USER]
		,[MMIS_SPECIALTY_TYPE_ID]
		,[NPI_REQUIRED]
FROM [TAXONOMY_TYPE]


DECLARE @MMIS_SPECIALTY_TYPE_ID varchar(10) = NULL,
		@SPECIALTY_TYPE_ID int = NULL,
		@MMIS_PROVIDER_TYPE_ID varchar(10) = NULL;

/* Provider 'Ambulance, Private' Specialty 'Emergency Medicine' */
SET @MMIS_SPECIALTY_TYPE_ID = '043';
SET @MMIS_PROVIDER_TYPE_ID = 'J00';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT TAXONOMY_TYPE_ID FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Pharmacy, Retail' Specialty 'General Preventive Medicine' */
SET @MMIS_SPECIALTY_TYPE_ID = '013';
SET @MMIS_PROVIDER_TYPE_ID = 'H00';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT TAXONOMY_TYPE_ID FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Hearing Aid Dealer' Specialty 'Oxygen and Accessories' */
SET @MMIS_SPECIALTY_TYPE_ID = '120';
SET @MMIS_PROVIDER_TYPE_ID = 'M01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT TAXONOMY_TYPE_ID FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Optician/Optical Dispensary' Specialty 'Opthalmology' */
SET @MMIS_SPECIALTY_TYPE_ID = '015';
SET @MMIS_PROVIDER_TYPE_ID = 'N01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
SELECT @SPECIALTY_TYPE_ID, p.PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 
FROM PROVIDER_TYPE p
	LEFT OUTER JOIN 
	(
		SELECT * FROM TAXONOMY_TYPE 
		WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID
	) t ON p.PROVIDER_TYPE_ID = t.PROVIDER_TYPE_ID
WHERE p.MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
	AND ISNULL(t.SPECIALTY_TYPE_ID, 0) = 0

/* Provider 'Nurse Midwives' Specialty 'Pediatrics' */
SET @MMIS_SPECIALTY_TYPE_ID = '004';
SET @MMIS_PROVIDER_TYPE_ID = 'S01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
SELECT @SPECIALTY_TYPE_ID, p.PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 
FROM PROVIDER_TYPE p
	LEFT OUTER JOIN 
	(
		SELECT * FROM TAXONOMY_TYPE 
		WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID
	) t ON p.PROVIDER_TYPE_ID = t.PROVIDER_TYPE_ID
WHERE p.MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
	AND ISNULL(t.SPECIALTY_TYPE_ID, 0) = 0

/* Provider 'Nurse Midwives' Specialty 'OB-GYN' */
SET @MMIS_SPECIALTY_TYPE_ID = '006';
SET @MMIS_PROVIDER_TYPE_ID = 'S01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
SELECT @SPECIALTY_TYPE_ID, p.PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 
FROM PROVIDER_TYPE p
	LEFT OUTER JOIN 
	(
		SELECT * FROM TAXONOMY_TYPE 
		WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID
	) t ON p.PROVIDER_TYPE_ID = t.PROVIDER_TYPE_ID
WHERE p.MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
	AND ISNULL(t.SPECIALTY_TYPE_ID, 0) = 0

/* Provider 'Nurse Midwives' Specialty 'General Surgery' */
SET @MMIS_SPECIALTY_TYPE_ID = '007';
SET @MMIS_PROVIDER_TYPE_ID = 'S01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
SELECT @SPECIALTY_TYPE_ID, p.PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 
FROM PROVIDER_TYPE p
	LEFT OUTER JOIN 
	(
		SELECT * FROM TAXONOMY_TYPE 
		WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID
	) t ON p.PROVIDER_TYPE_ID = t.PROVIDER_TYPE_ID
WHERE p.MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
	AND ISNULL(t.SPECIALTY_TYPE_ID, 0) = 0

/* Provider 'Nurse Midwives' Specialty 'General Preventative Medicine' */
SET @MMIS_SPECIALTY_TYPE_ID = '013';
SET @MMIS_PROVIDER_TYPE_ID = 'S01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
SELECT @SPECIALTY_TYPE_ID, p.PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 
FROM PROVIDER_TYPE p
	LEFT OUTER JOIN 
	(
		SELECT * FROM TAXONOMY_TYPE 
		WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID
	) t ON p.PROVIDER_TYPE_ID = t.PROVIDER_TYPE_ID
WHERE p.MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
	AND ISNULL(t.SPECIALTY_TYPE_ID, 0) = 0

/* Provider 'Nurse Midwives' Specialty 'Family Practice' */
SET @MMIS_SPECIALTY_TYPE_ID = '031';
SET @MMIS_PROVIDER_TYPE_ID = 'S01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
SELECT @SPECIALTY_TYPE_ID, p.PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 
FROM PROVIDER_TYPE p
	LEFT OUTER JOIN 
	(
		SELECT * FROM TAXONOMY_TYPE 
		WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID
	) t ON p.PROVIDER_TYPE_ID = t.PROVIDER_TYPE_ID
WHERE p.MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
	AND ISNULL(t.SPECIALTY_TYPE_ID, 0) = 0



/* Provider 'Clinic, Dental' Specialty 'General Surgery' */
SET @MMIS_SPECIALTY_TYPE_ID = '007';
SET @MMIS_PROVIDER_TYPE_ID = 'X01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Clinic, Dental' Specialty 'General Dentistry' */
SET @MMIS_SPECIALTY_TYPE_ID = '033';
SET @MMIS_PROVIDER_TYPE_ID = 'X01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Clinic, Dental' Specialty 'Orthodontics' */
SET @MMIS_SPECIALTY_TYPE_ID = '034';
SET @MMIS_PROVIDER_TYPE_ID = 'X01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Clinic, Dental' Specialty 'Pediatric Dentistry' */
SET @MMIS_SPECIALTY_TYPE_ID = '035';
SET @MMIS_PROVIDER_TYPE_ID = 'X01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Clinic, Dental' Specialty 'Oral and Maxillofacial Surgery' */
SET @MMIS_SPECIALTY_TYPE_ID = '036';
SET @MMIS_PROVIDER_TYPE_ID = 'X01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Clinic, Dental' Specialty 'Endodontics' */
SET @MMIS_SPECIALTY_TYPE_ID = '037';
SET @MMIS_PROVIDER_TYPE_ID = 'X01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Clinic, Dental' Specialty 'Periodontics' */
SET @MMIS_SPECIALTY_TYPE_ID = '038';
SET @MMIS_PROVIDER_TYPE_ID = 'X01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

/* Provider 'Radiation Therapy Center' Specialty 'Radiology' */
SET @MMIS_SPECIALTY_TYPE_ID = '002';
SET @MMIS_PROVIDER_TYPE_ID = 'E00';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END


/* Provider '' Specialty '' */
SET @MMIS_SPECIALTY_TYPE_ID = '742';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '713';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '711';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '703';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '739';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '714';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '710';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '712';
SET @MMIS_PROVIDER_TYPE_ID = 'W04';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END



-- Provider 'Pharmacy, Institutional', Specialty 'General Preventative Medicine'  
SET @MMIS_SPECIALTY_TYPE_ID = '013';
SET @MMIS_PROVIDER_TYPE_ID = 'H01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

-- Provider 'Pharmacy, ADAP', Specialty 'General Preventative Medicine'  
SET @MMIS_SPECIALTY_TYPE_ID = '013';
SET @MMIS_PROVIDER_TYPE_ID = 'H02';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

-- Provider 'Pharmacy, Alliance', Specialty 'General Preventative Medicine'  
SET @MMIS_SPECIALTY_TYPE_ID = '013';
SET @MMIS_PROVIDER_TYPE_ID = 'H03';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END


-- Provider 'Ambulance, Public', Specialty 'Emergency Medicine'
SET @MMIS_SPECIALTY_TYPE_ID = '043';
SET @MMIS_PROVIDER_TYPE_ID = 'J01';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END


-- Provider 'Hemodialysis, Hospital Based', Specialties 'Cardiology', Nephrology' and Neurology'
SET @MMIS_SPECIALTY_TYPE_ID = '001';
SET @MMIS_PROVIDER_TYPE_ID = 'Q02';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '030';
SET @MMIS_PROVIDER_TYPE_ID = 'Q02';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '092';
SET @MMIS_PROVIDER_TYPE_ID = 'Q02';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END


-- Provider Office State Superinten of Ed, specialties 'Psychiatry', 'Family Practice', 'Case Management' 
SET @MMIS_SPECIALTY_TYPE_ID = '005';
SET @MMIS_PROVIDER_TYPE_ID = 'P02';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '031';
SET @MMIS_PROVIDER_TYPE_ID = 'P02';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END

SET @MMIS_SPECIALTY_TYPE_ID = '711';
SET @MMIS_PROVIDER_TYPE_ID = 'P02';
SELECT @SPECIALTY_TYPE_ID = SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID;
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
END


-- Provider Hospital, LTAC , same specialties used with Hospital, General
SET @MMIS_PROVIDER_TYPE_ID = 'D01';
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE SPECIALTY_TYPE_ID <> 0 AND PROVIDER_TYPE_ID in (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT distinct b.SPECIALTY_TYPE_ID, a.PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', b.MMIS_SPECIALTY_TYPE_ID, 1 
	FROM PROVIDER_TYPE a, SPECIALTY_TYPE b
	WHERE a.MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID
	AND b.SPECIALTY_TYPE_ID IN
	 (SELECT DISTINCT SPECIALTY_TYPE_ID 
	  FROM TAXONOMY_TYPE a 
	  JOIN PROVIDER_TYPE b ON a.PROVIDER_TYPE_ID = b.PROVIDER_TYPE_ID 
	  WHERE b.MMIS_PROVIDER_TYPE_ID = 'D00' AND a.SPECIALTY_TYPE_ID <> 0)
END


-- Independent X-Ray, Standard Application, Group
IF (SELECT count(PROVIDER_TYPE_ID) FROM PROVIDER_TYPE WHERE MMIS_Provider_Type_ID = 'C00' AND Application_Type_ID = 1 AND PROVIDER_CATEGORY_TYPE_ID = 2) = 0
AND (SELECT count(PROVIDER_TYPE_ID) FROM PROVIDER_TYPE WHERE MMIS_Provider_Type_ID = 'C00' AND Application_Type_ID = 1 AND PROVIDER_CATEGORY_TYPE_ID = 3) > 1
UPDATE dbo.PROVIDER_TYPE 
SET PROVIDER_CATEGORY_TYPE_ID = 2
WHERE PROVIDER_TYPE_ID = (SELECT min(PROVIDER_TYPE_ID) FROM PROVIDER_TYPE WHERE MMIS_Provider_Type_ID = 'C00' AND Application_Type_ID = 1 AND PROVIDER_CATEGORY_TYPE_ID = 3);


/* Provider 'Clinic, Dental' Taxonomy 'General Practice' */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE TAXONOMY_CODE = '1223G0001X' AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'X01'))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT 0, PROVIDER_TYPE_ID, '1223G0001X', 'General Practice', '12/31/9999', GETDATE(), '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', '', 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'X01'
END

/* Provider 'Clinic, Dental' Taxonomy 'Dental' */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE TAXONOMY_CODE = '261QD0000X' AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'X01'))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT 0, PROVIDER_TYPE_ID, '261QD0000X', 'Dental', '12/31/9999', GETDATE(), '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', '', 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'X01'
END

/* Provider 'Clinic, Dental' Taxonomy 'Federally Qualified Health Center' */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE TAXONOMY_CODE = '261QF0400X' AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'X01'))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT 0, PROVIDER_TYPE_ID, '261QF0400X', 'Federally Qualified Health Center', '12/31/9999', GETDATE(), '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', '', 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'X01'
END

/* Provider 'Radiation Therapy Center' Taxonomy 'Oncology, Radiation' */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE TAXONOMY_CODE = '261QX0203X' AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'E00'))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT 0, PROVIDER_TYPE_ID, '261QX0203X', 'Oncology, Radiation', '12/31/9999', GETDATE(), '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', '', 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'E00'
END

/* Provider 'Radiation Therapy Center' Taxonomy 'Radiology' */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE TAXONOMY_CODE = '2085R0202X' AND PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'E00'))
BEGIN
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT 0, PROVIDER_TYPE_ID, '2085R0202X', 'Diagnostic Radiology', '12/31/9999', GETDATE(), '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', '', 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = 'E00'
END


/* IDDD */
SET @MMIS_PROVIDER_TYPE_ID = 'W01'

/* Link Specialty 111 Diabetic Footwear to all IDDD Provider Types */
SET @MMIS_SPECIALTY_TYPE_ID = '111'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
/* Link to Individual IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1

/* Link to Group IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2

/* Link to Facility IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3

/* Link Specialty 111 to Category 'Other' */
IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID)
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	VALUES (@SPECIALTY_TYPE_ID, 17, 'Diabetic Footwear', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D')

/* Link Specialty 707 Supportive Employment to all IDDD Provider Types */
SET @MMIS_SPECIALTY_TYPE_ID = '707'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
/* Link to Individual IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1

/* Link to Group IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2

/* Link to Facility IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3

/* Link Specialty 707 to Category 'Other' */
IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID)
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	VALUES (@SPECIALTY_TYPE_ID, 17, 'Supportive Employment', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D')

/* Link Specialty 730 Case Management to all IDDD Provider Types */
SET @MMIS_SPECIALTY_TYPE_ID = '730'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
/* Remove Link to Individual IDDD provider */
IF EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	DELETE FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID

/* Remove Link to Group IDDD provider */
IF EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	DELETE FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID

/* Remove Link to Facility IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	DELETE FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID

/* Remove Link Specialty 730 to Category 'Other' */
IF EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID)
	DELETE FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID

/* Link Specialty 803 Companion Services to all IDDD Provider Types */
SET @MMIS_SPECIALTY_TYPE_ID = '803'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
/* Link to Individual IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 1

/* Link to Group IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 2

/* Link to Facility IDDD provider */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID AND PROVIDER_CATEGORY_TYPE_ID = 3

/* Link Specialty 707 to Category 'Other' */
IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID)
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	VALUES (@SPECIALTY_TYPE_ID, 17, 'Companion Services', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D')


/* EPD */
SET @MMIS_PROVIDER_TYPE_ID = 'W02'
/* Link EPD Specialties to EPD Waiver */
/* Link Specialty 044 Geriatrict Medicine */
SET @MMIS_SPECIALTY_TYPE_ID = '044'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	DELETE FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID

SET @MMIS_SPECIALTY_TYPE_ID = '701'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
/* Remove 'MRDD' from 701 */
IF EXISTS (SELECT * FROM SPECIALTY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND SPECIALTY_TYPE_NAME LIKE '%MRDD%')
	UPDATE SPECIALTY_TYPE SET SPECIALTY_TYPE_NAME = 'Speech, Hearing, Language' WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID

/* Link Specialty 701 Speech, Hearing, Language */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

SET @MMIS_SPECIALTY_TYPE_ID = '704'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
/* Remove 'MRDD' from 704 */
IF EXISTS (SELECT * FROM SPECIALTY_TYPE WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID AND SPECIALTY_TYPE_NAME LIKE '%MRDD%')
	UPDATE SPECIALTY_TYPE SET SPECIALTY_TYPE_NAME = 'Respite Care Aide' WHERE SPECIALTY_TYPE_ID = @SPECIALTY_TYPE_ID

/* Link Specialty 704	Respite Care Aide */
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 718 Family Training */
SET @MMIS_SPECIALTY_TYPE_ID = '718'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 719 One Time Transitional Services */
SET @MMIS_SPECIALTY_TYPE_ID = '719'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 720	Vehicle Modifications */
SET @MMIS_SPECIALTY_TYPE_ID = '720'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 	721	DME Personal Emerg Resp Sys */
SET @MMIS_SPECIALTY_TYPE_ID = '721'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	DELETE FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID

/* Link Specialty 723	Art Therapist  */
SET @MMIS_SPECIALTY_TYPE_ID = '723'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 724	Dance Therapist   */
SET @MMIS_SPECIALTY_TYPE_ID = '724'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 725	Drama Therapist    */
SET @MMIS_SPECIALTY_TYPE_ID = '725'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty	726	Fitness Trainer */
SET @MMIS_SPECIALTY_TYPE_ID = '726'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 727 Massage Therapist */
SET @MMIS_SPECIALTY_TYPE_ID = '727'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 728	Music Therapist  */
SET @MMIS_SPECIALTY_TYPE_ID = '728'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 	729	Sexuality Education Specialist   */
SET @MMIS_SPECIALTY_TYPE_ID = '729'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 735 In-Home Supports */
SET @MMIS_SPECIALTY_TYPE_ID = '735'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 736 Supported Living */
SET @MMIS_SPECIALTY_TYPE_ID = '736'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 738 Attendant Care */
SET @MMIS_SPECIALTY_TYPE_ID = '738'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 802 FQHC Dental */
SET @MMIS_SPECIALTY_TYPE_ID = '802'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 803 Companion Services */
SET @MMIS_SPECIALTY_TYPE_ID = '803'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 804 EPD Physical Therapy */
SET @MMIS_SPECIALTY_TYPE_ID = '804'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 805 EPD Occupational Therapy */
SET @MMIS_SPECIALTY_TYPE_ID = '805'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID

/* Link Specialty 806 EPD Adult Day Health Program */
SET @MMIS_SPECIALTY_TYPE_ID = '806'
SELECT @SPECIALTY_TYPE_ID = MAX(SPECIALTY_TYPE_ID) FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID
IF NOT EXISTS (SELECT * FROM TAXONOMY_TYPE WHERE PROVIDER_TYPE_ID IN (SELECT PROVIDER_TYPE_ID FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID) AND MMIS_SPECIALTY_TYPE_ID = @MMIS_SPECIALTY_TYPE_ID)
	INSERT INTO TAXONOMY_TYPE (SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, TAXONOMY_CODE, TAXONOMY_NAME, EXPIRATION_DATE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, MMIS_SPECIALTY_TYPE_ID, NPI_REQUIRED)
	SELECT @SPECIALTY_TYPE_ID, PROVIDER_TYPE_ID, '', '', '12/31/9999', @pin_conv_run_time, '5C8EEA1D-B312-41A7-999C-DEDBCCA3688D', @MMIS_SPECIALTY_TYPE_ID, 1 FROM PROVIDER_TYPE WHERE MMIS_PROVIDER_TYPE_ID = @MMIS_PROVIDER_TYPE_ID




END

GO