/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulatePROVTYPE_ORGTYPE_MAPPING]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulatePROVTYPE_ORGTYPE_MAPPING]','P') is not null
DROP PROCEDURE [dbo].[DCConv_LkUp_PopulatePROVTYPE_ORGTYPE_MAPPING]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the PROVTYPE_ORGTYPE_MAPPING
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulatePROVTYPE_ORGTYPE_MAPPING] 
	@pin_run_reference_time datetime
AS
BEGIN
 -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	TRUNCATE TABLE dbo.PROVTYPE_ORGTYPE_MAPPING;

	INSERT INTO dbo.PROVTYPE_ORGTYPE_MAPPING
	 (PROVIDER_TYPE_ID, ORGANIZATION_TYPE_ID)
	SELECT DISTINCT a.PROVIDER_TYPE_ID,  b.ORGANIZATION_TYPE_ID
	FROM PROVIDER_TYPE a
	JOIN ORGANIZATION_TYPE b ON a.PROVIDER_TYPE_NAME = b.ORGANIZATION_TYPE_NAME
	WHERE a.PROVIDER_CATEGORY_TYPE_ID <> 1


--	DELETE FROM [dbo].[PROVTYPE_ORGTYPE_MAPPING];

--	SET IDENTITY_INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ON 

--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (96, 1, 86)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (97, 3, 87)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (98, 4, 88)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (99, 6, 89)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (100, 8, 90)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (101, 9, 91)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (102, 10, 92)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (103, 11, 93)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (104, 12, 94)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (105, 13, 95)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (106, 14, 96)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (107, 15, 97)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (108, 16, 98)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (109, 17, 99)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (110, 18, 100)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (111, 19, 101)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (112, 20, 102)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (113, 21, 103)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (114, 22, 104)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (115, 23, 105)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (116, 24, 106)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (117, 25, 107)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (118, 26, 108)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (119, 27, 109)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (120, 28, 110)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (121, 29, 111)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (122, 31, 112)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (123, 32, 113)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (124, 34, 114)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (125, 35, 115)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (126, 36, 116)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (127, 38, 117)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (128, 39, 118)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (129, 41, 119)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (130, 43, 120)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (131, 44, 121)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (132, 45, 122)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (133, 46, 123)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (134, 47, 124)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (135, 48, 125)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (136, 50, 126)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (137, 52, 127)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (138, 54, 128)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (139, 56, 129)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (140, 57, 130)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (141, 58, 131)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (142, 60, 132)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (143, 61, 133)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (144, 62, 134)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (145, 64, 135)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (146, 65, 136)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (147, 66, 137)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (148, 67, 138)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (149, 68, 139)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (150, 69, 140)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (151, 71, 141)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (152, 72, 142)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (153, 73, 143)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (154, 74, 144)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (155, 75, 145)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (156, 76, 146)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (157, 77, 147)
--INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] ([PROVTYPE_ORGTYPE_MAPPING_ID], [PROVIDER_TYPE_ID], [ORGANIZATION_TYPE_ID]) VALUES (158, 78, 148)
--SET IDENTITY_INSERT [dbo].[PROVTYPE_ORGTYPE_MAPPING] OFF

END

GO
