/****** Object:  StoredProcedure [dbo].[DCConv_ClearRegistrationData]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_ClearRegistrationData]','P') is not null
DROP PROCEDURE [dbo].[DCConv_ClearRegistrationData]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Richard Mays
-- Create date: 5/10/2016
-- Description:	Deletes the content of the registration tables
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_ClearRegistrationData] 
(
	@pin_conv_run_id varchar(20)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @table varchar(50);
	SET @table = '';
	BEGIN TRY
		BEGIN TRANSACTION;

		SET @table = 'REG_MALPRACTICE_CLAIM';
		DELETE	FROM [dbo].REG_MALPRACTICE_CLAIM;
		DBCC CHECKIDENT('dbo.REG_MALPRACTICE_CLAIM', RESEED, 0);

		SET @table = 'REG_EVENT_INFO';
		DELETE	FROM [dbo].REG_EVENT_INFO;
		DBCC CHECKIDENT('dbo.REG_EVENT_INFO', RESEED, 0);

		SET @table = 'REG_OWNER_PAPER_PROVIDER';
		DELETE	FROM [dbo].REG_OWNER_PAPER_PROVIDER;
		DBCC CHECKIDENT('dbo.REG_OWNER_PAPER_PROVIDER', RESEED, 0);

		SET @table = 'REG_STATE_CDS_NUMBER';
		DELETE	FROM [dbo].REG_STATE_CDS_NUMBER;
		DBCC CHECKIDENT('dbo.REG_STATE_CDS_NUMBER', RESEED, 0);

		SET @table = 'REG_ORIENTATION';
		DELETE	FROM [dbo].REG_ORIENTATION;
		DBCC CHECKIDENT('dbo.REG_ORIENTATION', RESEED, 0);

		SET @table = 'REG_BACKGROUND_VERIFICATION';
		DELETE	FROM [dbo].REG_BACKGROUND_VERIFICATION;
		DBCC CHECKIDENT('dbo.REG_ORIENTATION', RESEED, 0);

		SET @table = 'REG_BACKGROUND_CHECK';
		DELETE	FROM [dbo].REG_BACKGROUND_CHECK;
		DBCC CHECKIDENT('dbo.REG_BACKGROUND_CHECK', RESEED, 0);

		SET @table = 'REG_DME';
		DELETE	FROM [dbo].REG_DME;
		DBCC CHECKIDENT('dbo.REG_DME', RESEED, 0);

		SET @table = 'REG_FEDERAL_DEA_REGISTRATION';
		DELETE	FROM [dbo].REG_FEDERAL_DEA_REGISTRATION;
		DBCC CHECKIDENT('dbo.REG_FEDERAL_DEA_REGISTRATION', RESEED, 0);

        SET @table = 'REG_VISION_PROVIDER_DETAILS';
		DELETE	FROM [dbo].REG_VISION_PROVIDER_DETAILS;
		DBCC CHECKIDENT('dbo.REG_VISION_PROVIDER_DETAILS', RESEED, 0);

		SET @table = 'REG_NURSING_PROFESSIONAL_CERTIFICATION';
		DELETE	FROM [dbo].REG_NURSING_PROFESSIONAL_CERTIFICATION;
		DBCC CHECKIDENT('dbo.REG_NURSING_PROFESSIONAL_CERTIFICATION', RESEED, 0);

        SET @table = 'REG_OWNER_CONVICTION_ON_BEHALF';
		DELETE	FROM [dbo].REG_OWNER_CONVICTION_ON_BEHALF;
		DBCC CHECKIDENT('dbo.REG_OWNER_CONVICTION_ON_BEHALF', RESEED, 0);

        SET @table = 'REG_OWNER_TRANSACTION';
		DELETE	FROM [dbo].REG_OWNER_TRANSACTION;
		DBCC CHECKIDENT('dbo.REG_OWNER_TRANSACTION', RESEED, 0);

        SET @table = 'REG_DME_PERSONNEL_INFO';
		DELETE	FROM [dbo].REG_DME_PERSONNEL_INFO;
		DBCC CHECKIDENT('dbo.REG_DME_PERSONNEL_INFO', RESEED, 0);

        SET @table = 'REG_DENTAL_LICENSETYPE_LICENSEID';
		DELETE	FROM [dbo].REG_DENTAL_LICENSETYPE_LICENSEID;

        SET @table = 'REG_DME_BACKGROUND_CHK_PROFESSIONAL_INFO';
		DELETE	FROM [dbo].REG_DME_BACKGROUND_CHK_PROFESSIONAL_INFO;
		DBCC CHECKIDENT('dbo.REG_DME_BACKGROUND_CHK_PROFESSIONAL_INFO', RESEED, 0);

        SET @table = 'REG_DENTAL_LICENSES';
		DELETE	FROM [dbo].REG_DENTAL_LICENSES;
		DBCC CHECKIDENT('dbo.REG_DENTAL_LICENSES', RESEED, 0);

        SET @table = 'REG_PENDING_AFFILIATION';
		DELETE	FROM [dbo].REG_PENDING_AFFILIATION;
		DBCC CHECKIDENT('dbo.REG_PENDING_AFFILIATION', RESEED, 0);

        SET @table = 'REG_CPR_CERTIFICATION';
		DELETE	FROM [dbo].REG_CPR_CERTIFICATION;
		DBCC CHECKIDENT('dbo.REG_CPR_CERTIFICATION', RESEED, 0);

        SET @table = 'REG_DME_ACCREDITATION_AGENCY';
		DELETE	FROM [dbo].REG_DME_ACCREDITATION_AGENCY;
		DBCC CHECKIDENT('dbo.REG_DME_ACCREDITATION_AGENCY', RESEED, 0);

  --      SET @table = 'REG_DDS';
		--DELETE	FROM [dbo].REG_DDS;

        SET @table = 'REG_SUBCONTRACTOR';
		DELETE	FROM [dbo].REG_SUBCONTRACTOR;
		DBCC CHECKIDENT('dbo.REG_SUBCONTRACTOR', RESEED, 0);

        SET @table = 'REG_CATEGORY_OF_SERVICE_INFO';
		DELETE	FROM [dbo].REG_CATEGORY_OF_SERVICE_INFO;
		DBCC CHECKIDENT('dbo.REG_CATEGORY_OF_SERVICE_INFO', RESEED, 0);
		
		SET @table = 'REG_NUMBER_OF_BEDS';
		DELETE	FROM [dbo].REG_NUMBER_OF_BEDS;
		DBCC CHECKIDENT('dbo.REG_NUMBER_OF_BEDS', RESEED, 0);

		SET @table = 'REG_DOCUMENT_XREF';
		DELETE	FROM [dbo].REG_DOCUMENT_XREF;

        SET @table = 'DOCUMENT';
		DELETE	FROM [dbo].DOCUMENT;
		DBCC CHECKIDENT('dbo.DOCUMENT', RESEED, 0);

		SET @table = 'REG_TAXONOMY';
		DELETE FROM [dbo].REG_TAXONOMY;
		DBCC CHECKIDENT('dbo.REG_TAXONOMY', RESEED, 0);

	
		SET @table = 'REG_SPECIALTY';
		DELETE FROM [dbo].REG_SPECIALTY;
		DBCC CHECKIDENT('dbo.REG_SPECIALTY', RESEED, 0);

		SET @table = 'REG_LICENSE';
		DELETE FROM [dbo].REG_LICENSE;
		DBCC CHECKIDENT('dbo.REG_LICENSE', RESEED, 0);

		SET @table = 'REG_CLIA';
		DELETE FROM [dbo].REG_CLIA;
		DBCC CHECKIDENT('dbo.REG_CLIA', RESEED, 0);

		SET @table = 'REG_MEDICARE';
		DELETE FROM [dbo].REG_MEDICARE;
		DBCC CHECKIDENT('dbo.REG_MEDICARE', RESEED, 0);

		SET @table = 'REG_SERVICE_LOCATION';
		DELETE FROM [dbo].REG_SERVICE_LOCATION;
		DBCC CHECKIDENT('dbo.REG_SERVICE_LOCATION', RESEED, 0);

		SET @table = 'REG_ADDITIONAL_ADDRESSES';
		DELETE FROM [dbo].REG_ADDITIONAL_ADDRESSES;
		DBCC CHECKIDENT('dbo.REG_ADDITIONAL_ADDRESSES', RESEED, 0);

		SET @table = 'REG_DEA';
		DELETE FROM [dbo].REG_DEA;
		DBCC CHECKIDENT('dbo.REG_DEA', RESEED, 0);

		SET @table = 'REG_MEDICAID';
		DELETE FROM [dbo].REG_MEDICAID;
		DBCC CHECKIDENT('dbo.REG_MEDICAID', RESEED, 0);

		SET @table = 'REG_OWNER';
		DELETE FROM [dbo].REG_OWNER;
		DBCC CHECKIDENT('dbo.REG_OWNER', RESEED, 0);

		SET @table = 'REG_PROVIDER';
		DELETE FROM [dbo].REG_PROVIDER;
		

		SET @table = 'REG_ENROLLMENT';
		DELETE FROM [dbo].REG_ENROLLMENT;
		DBCC CHECKIDENT('dbo.REG_ENROLLMENT', RESEED, 0);
		
		SET @table = 'REGISTRATION';
		DELETE FROM [dbo].REGISTRATION;
		DBCC CHECKIDENT('dbo.REGISTRATION', RESEED, 0);
		
		SET @table = 'DCConv_KeyCrossReferences';
		DELETE FROM [dbo].DCConv_KeyCrossReferences;

		SET @table = 'LICENSURE';
		DELETE FROM [dbo].LICENSURE;
		DBCC CHECKIDENT('dbo.LICENSURE', RESEED, 0);

		SET @table = 'Log';

		DELETE FROM [dbo].[Log];
		DBCC CHECKIDENT('dbo.Log', RESEED, 0);

		SET @table = 'REG_AFFILIATION';
		DELETE FROM [dbo].REG_AFFILIATION;
		DBCC CHECKIDENT('dbo.REG_AFFILIATION', RESEED, 0);

		SET @table = 'COMMUNICATION_EVENT';
		DELETE FROM [dbo].COMMUNICATION_EVENT;
		DBCC CHECKIDENT('dbo.COMMUNICATION_EVENT', RESEED, 0);

		SET @table = 'ELECTRONIC_ADDRESS';
		DELETE FROM [dbo].ELECTRONIC_ADDRESS;

		SET @table = 'CONTACT_MECHANISM';
		DELETE FROM [dbo].CONTACT_MECHANISM;
		DBCC CHECKIDENT('dbo.CONTACT_MECHANISM', RESEED, 0);

		SET @table = 'CONTACT_MECHANISM_ROLE';
		DELETE FROM [dbo].CONTACT_MECHANISM_ROLE;
		DBCC CHECKIDENT('dbo.CONTACT_MECHANISM_ROLE', RESEED, 0);

		SET @table = 'PARTY_CONTACT_MECHANISM';
		DELETE FROM [dbo].PARTY_CONTACT_MECHANISM;

		SET @table = 'REG_AFFILIATION_CROSSOVER_XREF';
		DELETE FROM [dbo].REG_AFFILIATION_CROSSOVER_XREF;

		SET @table = 'ADDITIONAL_ADDRESSES';
		DELETE FROM [dbo].ADDITIONAL_ADDRESSES;
		DBCC CHECKIDENT('dbo.ADDITIONAL_ADDRESSES', RESEED, 0);

		SET @table = 'PARTY_IDENTIFICATION_NUMBER';
		DELETE FROM [dbo].PARTY_IDENTIFICATION_NUMBER;
		DBCC CHECKIDENT('dbo.PARTY_IDENTIFICATION_NUMBER', RESEED, 0);

		SET @table = 'PARTY_SPECIALTY';
		DELETE FROM [dbo].PARTY_SPECIALTY;
		DBCC CHECKIDENT('dbo.PARTY_SPECIALTY', RESEED, 0);

		SET @table = 'TELECOMMUNICATIONS_NUMBER';
		DELETE FROM [dbo].TELECOMMUNICATIONS_NUMBER;

		SET @table = 'PARTY_TAXONOMY';
		DELETE FROM [dbo].PARTY_TAXONOMY;
		DBCC CHECKIDENT('dbo.PARTY_TAXONOMY', RESEED, 0);

		SET @table = 'REG_TRANSFER_HISTORY';
		DELETE FROM [dbo].REG_TRANSFER_HISTORY;

		SET @table = 'PARTY_ROLE';
		DELETE FROM [dbo].PARTY_ROLE;
		DBCC CHECKIDENT('dbo.PARTY_ROLE', RESEED, 0);

		SET @table = 'PARTY_PROVIDER_TYPE_XREF';
		DELETE FROM [dbo].PARTY_PROVIDER_TYPE_XREF;
		DBCC CHECKIDENT('dbo.PARTY_PROVIDER_TYPE_XREF', RESEED, 0);

		SET @table = 'PARTY_TYPEOFPRACTICE_XREF';
		DELETE FROM [dbo].PARTY_TYPEOFPRACTICE_XREF;
		DBCC CHECKIDENT('dbo.PARTY_TYPEOFPRACTICE_XREF', RESEED, 0);

		SET @table = 'POSTAL_ADDRESS';
		DELETE FROM [dbo].POSTAL_ADDRESS;


		SET @table = 'PROVIDER_PROPERTY';
		DELETE FROM [dbo].PROVIDER_PROPERTY;
		DBCC CHECKIDENT('dbo.PROVIDER_PROPERTY', RESEED, 0);

		--SET @table = 'ELECTRONIC_ADDRESS';

		--DELETE
		--FROM [dbo].ELECTRONIC_ADDRESS

		SET @table = 'TAX_ID';
		DELETE FROM [dbo].TAX_ID;
		DBCC CHECKIDENT('dbo.TAX_ID', RESEED, 0);

		SET @table = 'PERSON';
		DELETE FROM [dbo].PERSON;

		SET @table = 'LICENSURE_MEDICARE';
		DELETE FROM dbo.LICENSURE_MEDICARE;
		DBCC CHECKIDENT('dbo.LICENSURE_MEDICARE', RESEED, 0);

		SET @table = 'ORGANIZATION';
		DELETE FROM [dbo].ORGANIZATION;
		
		SET @table = 'WF_STEP';
		DELETE FROM dbo.WF_STEP;
		DBCC CHECKIDENT('dbo.WF_STEP', RESEED, 0);
		
		SET @table = 'WF_PROCESS';
		DELETE FROM dbo.WF_PROCESS;
		DBCC CHECKIDENT('dbo.WF_PROCESS', RESEED, 0);
				
		SET @table = 'EMAIL';
		DELETE FROM dbo.EMAIL;
		
		
		SET @table = 'A_ELECTRONIC_ADDRESS';

		TRUNCATE TABLE  audit.A_ELECTRONIC_ADDRESS


		SET @table = 'A_TAX_ID';

		TRUNCATE TABLE  audit.A_TAX_ID


		SET @table = 'A_PERSON';

		TRUNCATE TABLE  audit.A_PERSON


		SET @table = 'A_LICENSURE_MEDICARE';

		TRUNCATE TABLE  audit.A_LICENSURE_MEDICARE


		SET @table = 'A_ORGANIZATION';

		TRUNCATE TABLE  audit.A_ORGANIZATION


		SET @table = 'A_REG_CLIA';

		TRUNCATE TABLE audit.A_REG_CLIA

		SET @table = 'A_REG_ADDITIONAL_ADDRESSES';

		TRUNCATE TABLE  audit.A_REG_ADDITIONAL_ADDRESSES

		SET @table = 'A_REGISTRATION';

		TRUNCATE TABLE audit.A_REG_ENROLLMENT;

		SET @table = 'A_REG_PROVIDER';
		
		TRUNCATE TABLE audit.A_REGISTRATION;
		
		SET @table = 'A_REG_ENROLLMENT';		

		TRUNCATE TABLE  audit.A_REG_PROVIDER

		SET @table = 'A_REG_LICENSE';

		TRUNCATE TABLE  audit.A_REG_LICENSE

		SET @table = 'A_REG_SPECIALTY';

		TRUNCATE TABLE audit.A_REG_SPECIALTY

		SET @table = 'A_REG_DEA';

		TRUNCATE TABLE  audit.A_REG_DEA

		SET @table = 'A_REG_SERVICE_LOCATION';

		TRUNCATE TABLE audit.A_REG_SERVICE_LOCATION

		SET @table = 'A_REG_AFFILIATION';

		TRUNCATE TABLE audit.A_REG_AFFILIATION

		SET @table = 'A_REG_TAXONOMY';

		TRUNCATE TABLE audit.A_REG_TAXONOMY

		SET @table = 'A_REG_MEDICARE';

		TRUNCATE TABLE  audit.A_REG_MEDICARE

		SET @table = 'A_REG_OWNER';

		TRUNCATE TABLE  audit.A_REG_OWNER

		SET @table = 'A_LICENSURE';

		TRUNCATE TABLE audit.A_LICENSURE

		SET @table = 'A_SPECIALTY_TYPE';

		TRUNCATE TABLE audit.A_SPECIALTY_TYPE

		SET @table = 'A_COMMUNICATION_EVENT';

		TRUNCATE TABLE audit.A_COMMUNICATION_EVENT

		SET @table = 'A_REG_MEDICAID';

		TRUNCATE TABLE audit.A_REG_MEDICAID

		SET @table = 'A_TAXONOMY_TYPE';

		TRUNCATE TABLE audit.A_TAXONOMY_TYPE
		SET @table = 'A_PROVIDER_TYPE';

		TRUNCATE TABLE audit.A_PROVIDER_TYPE

		SET @table = 'A_CONTACT_MECHANISM';

		TRUNCATE TABLE audit.A_CONTACT_MECHANISM

		SET @table = 'A_CONTACT_MECHANISM_ROLE';

		TRUNCATE TABLE audit.A_CONTACT_MECHANISM_ROLE

		SET @table = 'A_PARTY_CONTACT_MECHANISM';

		TRUNCATE TABLE audit.A_PARTY_CONTACT_MECHANISM

		SET @table = 'CONTACT_MECHANISM';

		SET @table = 'A_PARTY';

		TRUNCATE TABLE  audit.A_PARTY

		SET @table = 'A_REG_AFFILIATION_CROSSOVER_XREF';

		TRUNCATE TABLE  audit.A_REG_AFFILIATION_CROSSOVER_XREF


		SET @table = 'A_ADDITIONAL_ADDRESSES';

		TRUNCATE TABLE  audit.A_ADDITIONAL_ADDRESSES


		SET @table = 'A_PARTY_IDENTIFICATION_NUMBER';

		TRUNCATE TABLE  audit.A_PARTY_IDENTIFICATION_NUMBER


		SET @table = 'A_PARTY_SPECIALTY';

		TRUNCATE TABLE  audit.A_PARTY_SPECIALTY

		SET @table = 'A_PARTY_TAXONOMY';

		TRUNCATE TABLE  audit.A_PARTY_TAXONOMY

		SET @table = 'A_TELECOMMUNICATIONS_NUMBER';

		TRUNCATE TABLE  audit.A_TELECOMMUNICATIONS_NUMBER


		SET @table = 'A_PARTY_ROLE';

		TRUNCATE TABLE  audit.A_PARTY_ROLE


		SET @table = 'A_PARTY_PROVIDER_TYPE_XREF';

		TRUNCATE TABLE  audit.A_PARTY_PROVIDER_TYPE_XREF

		SET @table = 'A_PARTY_TYPEOFPRACTICE_XREF';

		TRUNCATE TABLE  audit.A_PARTY_TYPEOFPRACTICE_XREF

		SET @table = 'A_POSTAL_ADDRESS';

		TRUNCATE TABLE  audit.A_POSTAL_ADDRESS

		SET @table = 'A_REG_MALPRACTICE_CLAIM';
		TRUNCATE TABLE  audit.A_REG_MALPRACTICE_CLAIM;

		SET @table = 'A_REG_EVENT_INFO';
		TRUNCATE TABLE  audit.A_REG_EVENT_INFO;

		SET @table = 'A_REG_OWNER_PAPER_PROVIDER';
		TRUNCATE TABLE  audit.A_REG_OWNER_PAPER_PROVIDER;

		SET @table = 'A_REG_STATE_CDS_NUMBER';
		TRUNCATE TABLE  audit.A_REG_STATE_CDS_NUMBER;

		SET @table = 'A_REG_ORIENTATION';
		TRUNCATE TABLE  audit.A_REG_ORIENTATION;

		SET @table = 'A_REG_BACKGROUND_VERIFICATION';
		TRUNCATE TABLE  audit.A_REG_BACKGROUND_VERIFICATION;

		SET @table = 'A_REG_BACKGROUND_CHECK';
		TRUNCATE TABLE  audit.A_REG_BACKGROUND_CHECK;

		SET @table = 'A_REG_DME';
		TRUNCATE TABLE  audit.A_REG_DME;

		SET @table = 'A_REG_FEDERAL_DEA_REGISTRATION';
		TRUNCATE TABLE  audit.A_REG_FEDERAL_DEA_REGISTRATION;

  --      SET @table = 'A_REG_VISION_PROVIDER_DETAILS';
		--TRUNCATE TABLE  audit.A_REG_VISION_PROVIDER_DETAILS;

		SET @table = 'A_REG_NURSING_PROFESSIONAL_CERTIFICATION';
		TRUNCATE TABLE  audit.A_REG_NURSING_PROFESSIONAL_CERTIFICATION;

        SET @table = 'A_REG_OWNER_CONVICTION_ON_BEHALF';
		TRUNCATE TABLE  audit.A_REG_OWNER_CONVICTION_ON_BEHALF;

        SET @table = 'A_REG_OWNER_TRANSACTION';
		TRUNCATE TABLE  audit.A_REG_OWNER_TRANSACTION;

        SET @table = 'A_REG_DME_PERSONNEL_INFO';
		TRUNCATE TABLE  audit.A_REG_DME_PERSONNEL_INFO;

  --      SET @table = 'A_REG_DENTAL_LICENSETYPE_LICENSEID';
		--TRUNCATE TABLE  audit.A_REG_DENTAL_LICENSETYPE_LICENSEID;

        SET @table = 'A_REG_DME_BACKGROUND_CHK_PROFESSIONAL_INFO';
		TRUNCATE TABLE  audit.A_REG_DME_BACKGROUND_CHK_PROFESSIONAL_INFO;

  --      SET @table = 'A_REG_DENTAL_LICENSES';
		--TRUNCATE TABLE  audit.A_REG_DENTAL_LICENSES;

        SET @table = 'A_REG_PENDING_AFFILIATION';
		TRUNCATE TABLE  audit.A_REG_PENDING_AFFILIATION;

        SET @table = 'A_REG_CPR_CERTIFICATION';
		TRUNCATE TABLE  audit.A_REG_CPR_CERTIFICATION;

  --      SET @table = 'A_REG_DME_ACCREDITATION_AGENCY';
		--TRUNCATE TABLE  audit.A_REG_DME_ACCREDITATION_AGENCY;

        SET @table = 'A_REG_SUBCONTRACTOR';
		TRUNCATE TABLE  audit.A_REG_SUBCONTRACTOR;

        SET @table = 'A_REG_CATEGORY_OF_SERVICE_INFO';
		TRUNCATE TABLE  audit.A_REG_CATEGORY_OF_SERVICE_INFO;
		
		SET @table = 'A_REG_NUMBER_OF_BEDS';
		TRUNCATE TABLE [audit].A_REG_NUMBER_OF_BEDS;

		SET @table = 'A_REG_DOCUMENT_XREF';
		TRUNCATE TABLE  audit.A_REG_DOCUMENT_XREF;

        SET @table = 'A_DOCUMENT';
		TRUNCATE TABLE  audit.A_DOCUMENT;
		
		SET @table = 'A_WF_PROCESS';
		TRUNCATE TABLE audit.A_WF_PROCESS;
		
		SET @table = 'A_WF_STEP'
		TRUNCATE TABLE audit.A_WF_STEP;
		
		SET @table = 'A_EMAIL'
		TRUNCATE TABLE audit.A_EMAIL;

		
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION;
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorLine int;
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		DECLARE @ErrorNumber int;
		DECLARE @ErrorProcedure varchar(128);

		SELECT 
			@ErrorMessage = ERROR_MESSAGE(),
			@ErrorLine = ERROR_LINE(),
			@ErrorSeverity = ERROR_SEVERITY(),
			@ErrorState = ERROR_STATE(),
			@ErrorNumber = ERROR_NUMBER(),
			@ErrorProcedure = ERROR_PROCEDURE();

		-- add the error to the log
		INSERT INTO [dbo].[DCConv_Errors]([RunID],[TableContext],[ColumnContext],[ErrorLine],[ErrorNumber],[ErrorMessage],[ErrorProcedure])
		VALUES
        (@pin_conv_run_id,@table,'', @ErrorLine, @ErrorNumber, @ErrorMessage, @ErrorProcedure);
		
		-- this will be a fatal error
		RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
END


GO
