/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulateSPECIALTY_EMPLOYEE_TYPE]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulateSPECIALTY_EMPLOYEE_TYPE]','P') is not null
DROP PROCEDURE [dbo].[DCConv_LkUp_PopulateSPECIALTY_EMPLOYEE_TYPE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the ORGANIZATION_TYPE
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulateSPECIALTY_EMPLOYEE_TYPE] 
	@pin_run_reference_time datetime
AS
BEGIN


SET IDENTITY_INSERT [dbo].SPECIALTY_EMPLOYEE_TYPE ON 

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 1)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 1, SPECIALTY_TYPE_ID, 2, 'Professional Behavioral Support', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '716'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 2)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 2, SPECIALTY_TYPE_ID, 2, 'Paraprofessional Behavioral Support', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '716'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 3)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 3, SPECIALTY_TYPE_ID, 2, 'Non-Professional BSP', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '716'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 4)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 4, SPECIALTY_TYPE_ID, 18, 'Day Habilitation Specialist (Direct Support Professionals)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '706'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 5)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 5, SPECIALTY_TYPE_ID, 18, 'Day Habilitation Specialist One to One (Direct Support Professionals)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '706'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 6)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 6, SPECIALTY_TYPE_ID, 3, 'Employment Readiness (Direct Support Professionals)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '758'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 7)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT top 1 7, SPECIALTY_TYPE_ID, 4, 'Environmental Accessibilities Adaptation Services', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '709'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 8)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 8, SPECIALTY_TYPE_ID, 5, 'Independent Clinical Social Worker', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '718'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 9)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 9, SPECIALTY_TYPE_ID, 5, 'Occupational Therapist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '733'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 10)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 10, SPECIALTY_TYPE_ID, 5, 'Physical Therapist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '732'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 11)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 11, SPECIALTY_TYPE_ID, 5, 'Speech, Hearing and Language Therapist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '701'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 12)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 12, SPECIALTY_TYPE_ID, 5, 'Registered Nurse', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '718'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 13)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 13, SPECIALTY_TYPE_ID, 5, 'Special Education Instructor', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '718'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 14)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 14, SPECIALTY_TYPE_ID, 6, 'Host Home Provider (Direct Support Professional)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '734'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 15)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 15, SPECIALTY_TYPE_ID, 7, 'Direct Support Professionals', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '753'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 16)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 16, SPECIALTY_TYPE_ID, 8, 'Direct Support Professionals', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '735'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 17)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT top 1 17, SPECIALTY_TYPE_ID, 9, 'Twenty-four (24) hour Facility', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '710'
END

-- Mod from Ben
--IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 18)
--BEGIN
--	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
--		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
--		SELECT 18, SPECIALTY_TYPE_ID, 10, 'Direct Support Professionals', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '704'
--END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 18)
BEGIN
       INSERT INTO SPECIALTY_EMPLOYEE_TYPE
              (SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
              SELECT 18, SPECIALTY_TYPE_ID, 10, 'Respite Care', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '704'
END
-- BO 11/15/2016 - Changed by Kelly, but not in DSD
ELSE IF EXISTS (SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 18 AND EMPLOYEE_TYPE_NAME <> 'Respite Care Aide')
       UPDATE SPECIALTY_EMPLOYEE_TYPE
       SET EMPLOYEE_TYPE_NAME = 'Respite Care Aide'
       WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 18



IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 19)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 19, SPECIALTY_TYPE_ID, 11, 'Direct Support Professional', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '705'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 20)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 20, SPECIALTY_TYPE_ID, 12, 'Licensed Registered Nurse', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '731'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 21)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 21, SPECIALTY_TYPE_ID, 12, 'Licensed Practical Nurse', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '731'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 22)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 22, SPECIALTY_TYPE_ID, 13, 'Licensed Speech Pathologist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '701'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 23)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 23, SPECIALTY_TYPE_ID, 13, 'Audiologist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '701'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 24)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 24, SPECIALTY_TYPE_ID, 13, 'Speech Pathologist Assistance', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '701'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 25)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 25, SPECIALTY_TYPE_ID, 14, 'Vocational Rehabilitation Counselor', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '746'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 26)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 26, SPECIALTY_TYPE_ID, 14, 'Rehabilitation Specialist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '746'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 27)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 27, SPECIALTY_TYPE_ID, 14, 'A person with a Master''s degree and a minimum of one (1) year of experience working with persons with intellectual and developmental disabilities', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '746'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 28)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 28, SPECIALTY_TYPE_ID, 14, 'A person with a Bachelor''s degree and a minimum of two (2) years of experience working in supported employment', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '746'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 29)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 29, SPECIALTY_TYPE_ID, 14, 'Job Coach', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '746'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 30)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 30, SPECIALTY_TYPE_ID, 14, 'Employment Specialist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '746'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 31)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 31, SPECIALTY_TYPE_ID, 15, 'Direct Support Professionals', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '755'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 32)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 32, SPECIALTY_TYPE_ID, 16, 'Fitness Trainer', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '726'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 33)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 33, SPECIALTY_TYPE_ID, 16, 'Massage Therapist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '727'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 34)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 34, SPECIALTY_TYPE_ID, 16, 'Dietician/Nutritionist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '702'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 35)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 35, SPECIALTY_TYPE_ID, 16, 'Bereavement Counseling', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '750'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 36)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 36, SPECIALTY_TYPE_ID, 16, 'Sexuality Education Therapist - Counselor', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '729'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 37)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 37, SPECIALTY_TYPE_ID, 16, 'Sexuality Education Therapist - Therapist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '729'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 38)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 38, SPECIALTY_TYPE_ID, 16, 'Sexuality Education Therapist - Psychologist', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '729'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 39)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 39, SPECIALTY_TYPE_ID, 16, 'Licensed Independent Clinical Social Worker', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '729'
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_EMPLOYEE_TYPE WHERE SPECIALTY_EMPLOYEE_TYPE_ID = 40)
BEGIN
	INSERT INTO SPECIALTY_EMPLOYEE_TYPE
		(SPECIALTY_EMPLOYEE_TYPE_ID, SPECIALTY_TYPE_ID, SPECIALTY_CATEGORY_ID, EMPLOYEE_TYPE_NAME, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 40, SPECIALTY_TYPE_ID, 16, 'Licensed Professional Counselor', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '729'
END

SET IDENTITY_INSERT [dbo].SPECIALTY_EMPLOYEE_TYPE OFF;

END

GO