/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_DEFAULT_TEMPLATE]    Script Date: 8/3/2016 10:29:45 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_DEFAULT_TEMPLATE]','P') is not null
DROP PROCEDURE [dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_DEFAULT_TEMPLATE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the SCREENING_ACTIVITY_DEFAULT_TEMPLATE
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulateSCREENING_ACTIVITY_DEFAULT_TEMPLATE] 
	@pin_run_reference_time datetime
AS
BEGIN
 -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	DECLARE @pin_order_seed int;

	
	TRUNCATE TABLE [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE];

	SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] ON ;

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	1	,	1	,	1	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	2	,	1	,	1	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	5	,	1	,	1	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	6	,	1	,	1	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	7	,	1	,	1	,	5	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	11	,	1	,	1	,	9	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	85	,	1	,	1	,	6	,	2	,	1	,	8	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	13	,	1	,	1	,	11	,	2	,	1	,	7	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	3	,	1	,	17	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	4	,	1	,	17	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	8	,	1	,	17	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	9	,	1	,	17	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	10	,	1	,	17	,	5	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	12	,	1	,	17	,	9	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	38	,	1	,	17	,	11	,	2	,	1	,	7	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	86	,	1	,	17	,	6	,	2	,	1	,	8	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	87	,	2	,	1	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	88	,	2	,	1	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	89	,	2	,	1	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	90	,	2	,	1	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	91	,	2	,	6	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	92	,	2	,	6	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	93	,	2	,	6	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	94	,	2	,	6	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	95	,	2	,	15	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	96	,	2	,	15	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	97	,	2	,	15	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	98	,	2	,	15	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	99	,	2	,	16	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	100	,	2	,	16	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	101	,	2	,	16	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	102	,	2	,	16	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	103	,	2	,	17	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	104	,	2	,	17	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	105	,	2	,	17	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	106	,	2	,	17	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	107	,	2	,	1	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	108	,	2	,	6	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	109	,	2	,	15	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	110	,	2	,	16	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	111	,	2	,	17	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	112	,	2	,	1	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	156	,	2	,	6	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	200	,	2	,	15	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	244	,	2	,	16	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	288	,	2	,	17	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	332	,	3	,	1	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	333	,	3	,	1	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	334	,	3	,	1	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	335	,	3	,	1	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	336	,	3	,	6	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	337	,	3	,	6	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	338	,	3	,	6	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	339	,	3	,	6	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	340	,	3	,	15	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	341	,	3	,	15	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	342	,	3	,	15	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	343	,	3	,	15	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	344	,	3	,	16	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	345	,	3	,	16	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	346	,	3	,	16	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	347	,	3	,	16	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	348	,	3	,	17	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	349	,	3	,	17	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	350	,	3	,	17	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	351	,	3	,	17	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	352	,	3	,	1	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	353	,	3	,	6	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	354	,	3	,	15	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	355	,	3	,	16	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	356	,	3	,	17	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	357	,	3	,	1	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	448	,	3	,	6	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	539	,	3	,	15	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	630	,	3	,	16	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	721	,	3	,	17	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	812	,	5	,	1	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	813	,	5	,	1	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	814	,	5	,	1	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	815	,	5	,	1	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	832	,	5	,	1	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	837	,	5	,	1	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	816	,	5	,	6	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	817	,	5	,	6	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	818	,	5	,	6	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	819	,	5	,	6	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	833	,	5	,	6	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	846	,	5	,	6	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	820	,	5	,	15	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	821	,	5	,	15	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	822	,	5	,	15	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	823	,	5	,	15	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	834	,	5	,	15	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	855	,	5	,	15	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	824	,	5	,	16	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	825	,	5	,	16	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	826	,	5	,	16	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	827	,	5	,	16	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	835	,	5	,	16	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	864	,	5	,	16	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	828	,	5	,	17	,	1	,	7	,	1	,	1	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	829	,	5	,	17	,	2	,	7	,	1	,	2	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	830	,	5	,	17	,	3	,	2	,	1	,	3	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	831	,	5	,	17	,	4	,	2	,	1	,	4	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	836	,	5	,	17	,	6	,	2	,	1	,	5	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)
INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID],[PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])VALUES(	873	,	5	,	17	,	11	,	2	,	1	,	6	,	@pin_run_reference_time	,	'5D0689A8-D885-4211-B9FD-56757474AB4D'	,	0	,	0	,	null	)

SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] OFF ;

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
select [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
 '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID]
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7))
ORDER BY [PROVIDER_TYPE_ID]

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND (APPLICATION_TYPE_ID IN (1))
ORDER BY [PROVIDER_TYPE_ID]


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
FROM PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 
ORDER BY [PROVIDER_TYPE_ID]

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 1 AND (APPLICATION_TYPE_ID IN (1))
ORDER BY [PROVIDER_TYPE_ID]


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7))
ORDER BY [PROVIDER_TYPE_ID]

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 6

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 6 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 6

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 6 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 15

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 15 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 15

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 15 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 16

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 16 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7))

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 16

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 16 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 2 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID]
from PROVIDER_TYPE
WHERE MMIS_PROVIDER_TYPE_ID in ('D01','D02','D03')
and APPLICATION_TYPE_ID = 7

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 6

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 6 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7))

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 6

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 6 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID]
from PROVIDER_TYPE
WHERE MMIS_PROVIDER_TYPE_ID in ('D01','D02','D03')
and APPLICATION_TYPE_ID = 7

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 6

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 6 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 15

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 15 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7))

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 15

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 15 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID]
from PROVIDER_TYPE
WHERE MMIS_PROVIDER_TYPE_ID in ('D01','D02','D03')
and APPLICATION_TYPE_ID = 7

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 15

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 15 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 16

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 16 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7))

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 16

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 16 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID]
from PROVIDER_TYPE
WHERE MMIS_PROVIDER_TYPE_ID in ('D01','D02','D03')
and APPLICATION_TYPE_ID = 7

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 16

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 16 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7))

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID]
from PROVIDER_TYPE
WHERE MMIS_PROVIDER_TYPE_ID in ('D01','D02','D03')
and APPLICATION_TYPE_ID = 7

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 3 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 1

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 1 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 6

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 6 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 6

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 6 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 15

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 15 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 15

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 15 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 16

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 16 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 16

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 16 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID IN (1))


--- Reset Display Order
select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 19 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID NOT IN (2,3,4,5,7)) 

select @pin_order_seed = MAX(DISPLAY_ORDER)
FROM SCREENING_ACTIVITY_DEFAULT_TEMPLATE
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 and WORKFLOW_ID = 17

INSERT INTO [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE]
([PROVIDER_CATEGORY_TYPE_ID],[WORKFLOW_ID],[SCREENING_ACTIVITY_TYPE_ID],[SCREENING_ACTIVITY_STATUS_ID],[IS_ACTIVE],[DISPLAY_ORDER],[LAST_MODIFIED_DATE_TIME],[LAST_MODIFIED_USER],[REFERRAL_REQUIRED],[SCREENING_EVENT_TYPE_ID],[PROVIDER_TYPE_ID])
SELECT [PROVIDER_CATEGORY_TYPE_ID], 17 as [WORKFLOW_ID], 20 as [SCREENING_ACTIVITY_TYPE_ID], 2 as [SCREENING_ACTIVITY_STATUS_ID],
 1 as IS_ACTIVE, @pin_order_seed + row_number() over(ORDER BY [PROVIDER_TYPE_ID]) as DISPLAY_ORDER, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
  '5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER,
 0 as REFERRAL_REQUIRED, 0 as SCREENING_EVENT_TYPE_ID, [PROVIDER_TYPE_ID] 
from PROVIDER_TYPE 
WHERE PROVIDER_CATEGORY_TYPE_ID = 5 AND (APPLICATION_TYPE_ID IN (1))


-- More from Diwakar DeltaafterRun.sql script
SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] ON;

DECLARE @id int;

SELECT @id = MAX([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID]) + 1 FROM [SCREENING_ACTIVITY_DEFAULT_TEMPLATE];
INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] ([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID], [PROVIDER_TYPE_ID]) VALUES (@id, 1, 1, 18, 2, 1, 11, CAST(N'2016-08-12 03:35:23.890' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0, NULL);
SELECT @id = MAX([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID]) + 1 FROM [SCREENING_ACTIVITY_DEFAULT_TEMPLATE];
INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] ([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID], [PROVIDER_TYPE_ID]) VALUES (@id, 2, 1, 18, 2, 1, 9, CAST(N'2016-08-12 03:35:23.890' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0, NULL);
SELECT @id = MAX([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID]) + 1 FROM [SCREENING_ACTIVITY_DEFAULT_TEMPLATE];
INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] ([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID], [PROVIDER_TYPE_ID]) VALUES (@id, 3, 1, 18, 2, 1, 9, CAST(N'2016-08-12 03:35:23.890' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0, NULL);
SELECT @id = MAX([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID]) + 1 FROM [SCREENING_ACTIVITY_DEFAULT_TEMPLATE];
INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] ([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID], [PROVIDER_TYPE_ID]) VALUES (@id, 4, 1, 18, 2, 1, 9, CAST(N'2016-08-12 03:35:23.890' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0, NULL);
SELECT @id = MAX([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID]) + 1 FROM [SCREENING_ACTIVITY_DEFAULT_TEMPLATE];
INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] ([SCREENING_ACTIVITY_DEFAULT_TEMPLATE_ID], [PROVIDER_CATEGORY_TYPE_ID], [WORKFLOW_ID], [SCREENING_ACTIVITY_TYPE_ID], [SCREENING_ACTIVITY_STATUS_ID], [IS_ACTIVE], [DISPLAY_ORDER], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [REFERRAL_REQUIRED], [SCREENING_EVENT_TYPE_ID], [PROVIDER_TYPE_ID]) VALUES (@id, 5, 1, 18, 2, 1, 9, CAST(N'2016-08-12 03:35:23.890' AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', 0, 0, NULL);

SET IDENTITY_INSERT [dbo].[SCREENING_ACTIVITY_DEFAULT_TEMPLATE] OFF;




END

GO
