/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulateTAX_ENTITY_TYPE]    Script Date: 9/29/2016 ******/
IF object_id('[dbo].[DCConv_LkUp_PopulateTAX_ENTITY_TYPE]','P') is not null
DROP PROCEDURE [dbo].[DCConv_LkUp_PopulateTAX_ENTITY_TYPE]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulateTAX_ENTITY_TYPE] 
	@pin_run_reference_time datetime
AS

BEGIN

	SET NOCOUNT ON;


	SET IDENTITY_INSERT [dbo].[TAX_ENTITY_TYPE] ON;

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 1)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (1, 'C Corporation', 'C', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 2)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (2, 'S Corporation', 'C', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 3)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (3, 'LLC Corporation', 'C', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 4)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (4, 'LLC S Corporation', 'C', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 5)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (5, 'Partnership', 'P', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 6)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (6, 'LLC Partnership', 'P', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 7)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (7, 'Government Entity', 'G', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 8)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (8, 'Non-profit Ownership', 'N', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 9)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (9, 'Other Ownership', 'O', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 10)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (10, 'Sole Ownership/Proprietorship', 'V', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 11)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (11, 'Individual Recipient', 'I', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');


	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 12)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (12, 'Board or Commissioner', 'B', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 13)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (13, 'Non-profit Corporation (Legacy)', 'D', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 14)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (14, 'Public (Legacy)', 'H', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');

	IF NOT EXISTS (SELECT TAX_ENTITY_TYPE_ID FROM [dbo].[TAX_ENTITY_TYPE] WHERE TAX_ENTITY_TYPE_ID = 15)
	INSERT [dbo].[TAX_ENTITY_TYPE] ([TAX_ENTITY_TYPE_ID], [TAX_ENTITY_TYPE], [MMIS], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER]) 
	VALUES (15, 'Limited Liability Corp (Legacy)', 'L', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d');


	SET IDENTITY_INSERT [dbo].[TAX_ENTITY_TYPE] OFF;


END

GO
