/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulatePROVIDER_RISK_LEVEL]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulatePROVIDER_RISK_LEVEL]','P') is not null
DROP PROCEDURE [dbo].DCConv_LkUp_PopulatePROVIDER_RISK_LEVEL
GO

/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulatePROVIDER_RISK_LEVEL]    Script Date: 8/1/2016 3:13:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the PROVIDER_RISK_LEVEL
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulatePROVIDER_RISK_LEVEL] 
	@pin_run_reference_time datetime
AS
BEGIN
 -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DELETE FROM [dbo].[PROVIDER_RISK_LEVEL];

	SET IDENTITY_INSERT [dbo].[PROVIDER_RISK_LEVEL] ON 

	INSERT [dbo].[PROVIDER_RISK_LEVEL] ([PROVIDER_RISK_LEVEL_ID], [PROVIDER_RISK_LEVEL_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [MMIS_PROVIDER_RISK_LEVEL_ID]) VALUES (0, N'Undefined', CAST(0x0000A4B900DDFEC6 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', NULL)
	INSERT [dbo].[PROVIDER_RISK_LEVEL] ([PROVIDER_RISK_LEVEL_ID], [PROVIDER_RISK_LEVEL_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [MMIS_PROVIDER_RISK_LEVEL_ID]) VALUES (1, N'Limited', CAST(0x0000A44400BC11A2 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', N'L')
	INSERT [dbo].[PROVIDER_RISK_LEVEL] ([PROVIDER_RISK_LEVEL_ID], [PROVIDER_RISK_LEVEL_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [MMIS_PROVIDER_RISK_LEVEL_ID]) VALUES (2, N'Moderate', CAST(0x0000A44400BC11A5 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', N'M')
	INSERT [dbo].[PROVIDER_RISK_LEVEL] ([PROVIDER_RISK_LEVEL_ID], [PROVIDER_RISK_LEVEL_NAME], [LAST_MODIFIED_DATE_TIME], [LAST_MODIFIED_USER], [MMIS_PROVIDER_RISK_LEVEL_ID]) VALUES (3, N'High', CAST(0x0000A44400BC11A6 AS DateTime), N'5d0689a8-d885-4211-b9fd-56757474ab4d', N'H')
	SET IDENTITY_INSERT [dbo].[PROVIDER_RISK_LEVEL] OFF

END

GO
