/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulateCERTIFICATION_ACTION_TYPE]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulateCERTIFICATION_ACTION_TYPE]','P') is not null
DROP PROCEDURE [dbo].DCConv_LkUp_PopulateCERTIFICATION_ACTION_TYPE
GO
/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulateCERTIFICATION_ACTION_TYPE]    Script Date: 8/1/2016 3:13:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the CERTIFICATION_ACTION_TYPE
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulateCERTIFICATION_ACTION_TYPE] 
	@pin_run_reference_time datetime
AS
BEGIN
 -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DELETE FROM [dbo].[CERTIFICATION_ACTION_TYPE];

SET IDENTITY_INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ON 

INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (1, N'Initial', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (2, N'Recertification', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (3, N'Termination', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (4, N'CHOW', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (5, N'Validation', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (6, N'Compliant', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (7, N'On-site visit', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (8, N'Full Survey after Complaint', 1)
INSERT [dbo].[CERTIFICATION_ACTION_TYPE] ([CERTIFICATION_ACTION_TYPE_ID], [NAME], [IS_ACTIVE]) VALUES (9, N'Other', 1)
SET IDENTITY_INSERT [dbo].[CERTIFICATION_ACTION_TYPE] OFF

END

GO
