
/****** Object:  StoredProcedure [dbo].[DCConv_PostConversionTrimSpaces]    Script Date: 9/28/2016 4:26:25 PM ******/
IF object_id('[dbo].[DCConv_PostConversionTrimSpaces]','P') is not null
DROP PROCEDURE [dbo].[DCConv_PostConversionTrimSpaces]
GO

/****** Object:  StoredProcedure [dbo].[DCConv_PostConversionTrimSpaces]    Script Date: 9/28/2016 4:26:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Richard Mays
-- Create date: 9/28/2016
-- Description:	Trims spaces from all strings in system
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_PostConversionTrimSpaces] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	UPDATE [dbo].[REGISTRATION]
	   SET [FORM_COMPLETION_NAME] = RTRIM(LTRIM(FORM_COMPLETION_NAME))
		  ,[FORM_COMPLETION_PHONE] = RTRIM(LTRIM(FORM_COMPLETION_PHONE))

	UPDATE [dbo].[REG_PROVIDER]
	   SET [NAME] = RTRIM(LTRIM(NAME))
		  ,[DBA] = RTRIM(LTRIM(DBA))
		  ,[NPI] = RTRIM(LTRIM(NPI))
		  ,[CONTACT_NAME] = RTRIM(LTRIM(CONTACT_NAME))
		  ,[CONTACT_TITLE] = RTRIM(LTRIM(CONTACT_TITLE))
		  ,[CONTACT_ADDRESS1] = RTRIM(LTRIM(CONTACT_ADDRESS1))
		  ,[CONTACT_ADDRESS2] = RTRIM(LTRIM(CONTACT_ADDRESS2))
		  ,[CONTACT_CITY] = RTRIM(LTRIM(CONTACT_CITY))
		  ,[CONTACT_STATE] = RTRIM(LTRIM(CONTACT_STATE))
		  ,[CONTACT_ZIP] = RTRIM(LTRIM(CONTACT_ZIP))
		  ,[CONTACT_EXT_ZIP] = RTRIM(LTRIM(CONTACT_EXT_ZIP))
		  ,[CONTACT_PHONE_NUMBER] = RTRIM(LTRIM(CONTACT_PHONE_NUMBER))
		  ,[CONTACT_PHONE_EXT] = RTRIM(LTRIM(CONTACT_PHONE_EXT))
		  ,[CONTACT_FAX_NUMBER] = RTRIM(LTRIM(CONTACT_FAX_NUMBER))
		  ,[CONTACT_EMAIL_ADDRESS] = RTRIM(LTRIM(CONTACT_EMAIL_ADDRESS))
		  ,[ENROLLMENT_STATUS_CODE] = RTRIM(LTRIM(ENROLLMENT_STATUS_CODE))
		  ,[FIRST_NAME] = RTRIM(LTRIM(FIRST_NAME))
		  ,[LAST_NAME] = RTRIM(LTRIM(LAST_NAME))
		  ,[MIDDLE_INITIAL] = RTRIM(LTRIM(MIDDLE_INITIAL))
		  ,[TITLE] = RTRIM(LTRIM(TITLE))
		  ,[ALIEN_NUMBER] = RTRIM(LTRIM(ALIEN_NUMBER))
		  ,[OFFICE_MANAGER] = RTRIM(LTRIM(OFFICE_MANAGER))
		  ,[CONTACT_QUADRANT] = RTRIM(LTRIM(CONTACT_QUADRANT))
		  ,[CONTACT_WARD] = RTRIM(LTRIM(CONTACT_WARD))
		  ,[CONTACT_COUNTY] = RTRIM(LTRIM(CONTACT_COUNTY))
		  ,[ALT_TAX_ID] = RTRIM(LTRIM(ALT_TAX_ID))
		  ,[TAX_ID] = RTRIM(LTRIM(TAX_ID))

	UPDATE [dbo].[REG_LICENSE]
		SET [LICENSE_NUMBER] = RTRIM(LTRIM(LICENSE_NUMBER))
	      ,[LICENSE_STATE] = RTRIM(LTRIM(LICENSE_STATE))

	UPDATE [dbo].[REG_CLIA]
		SET [CLIA_NUMBER] = RTRIM(LTRIM(CLIA_NUMBER))
  		,[CLIA_STATE] = RTRIM(LTRIM(CLIA_STATE))


	UPDATE [dbo].[REG_MEDICARE]
		SET [MEDICARE_NUMBER] = RTRIM(LTRIM(MEDICARE_NUMBER))
	      ,[NCPDP_NUMBER] = RTRIM(LTRIM(NCPDP_NUMBER))
	      ,[NPI] = RTRIM(LTRIM(NPI))

	UPDATE [dbo].[REG_SERVICE_LOCATION]
	   SET [PRACTICE_NAME] = RTRIM(LTRIM(PRACTICE_NAME))
		  ,[MEDICAID_ID] = RTRIM(LTRIM(MEDICAID_ID))
		  ,[SERVICING_ADDRESS1] = RTRIM(LTRIM(SERVICING_ADDRESS1))
		  ,[SERVICING_ADDRESS2] = RTRIM(LTRIM(SERVICING_ADDRESS2))
		  ,[SERVICING_CITY] = RTRIM(LTRIM(SERVICING_CITY))
		  ,[SERVICING_COUNTY] = RTRIM(LTRIM(SERVICING_COUNTY))
		  ,[SERVICING_STATE] = RTRIM(LTRIM(SERVICING_STATE))
		  ,[SERVICING_ZIP] = RTRIM(LTRIM(SERVICING_ZIP))
		  ,[SERVICING_EXT_ZIP] = RTRIM(LTRIM(SERVICING_EXT_ZIP))
		  ,[SERVICING_COUNTRY] = RTRIM(LTRIM(SERVICING_COUNTRY))
		  ,[SERVICING_ADDRESS_NAME] = RTRIM(LTRIM(SERVICING_ADDRESS_NAME))
		  ,[SERVICING_PHONE_NUMBER] = RTRIM(LTRIM(SERVICING_PHONE_NUMBER))
		  ,[SERVICING_PHONE_EXT] = RTRIM(LTRIM(SERVICING_PHONE_EXT))
		  ,[SERVICING_FAX_NUMBER] = RTRIM(LTRIM(SERVICING_FAX_NUMBER))
		  ,[SERVICING_EMAIL_ADDRESS] = RTRIM(LTRIM(SERVICING_EMAIL_ADDRESS))
		  ,[MAILTO_ADDRESS1] = RTRIM(LTRIM(MAILTO_ADDRESS1))
		  ,[MAILTO_ADDRESS2] = RTRIM(LTRIM(MAILTO_ADDRESS2))
		  ,[MAILTO_CITY] = RTRIM(LTRIM(MAILTO_CITY))
		  ,[MAILTO_COUNTY] = RTRIM(LTRIM(MAILTO_COUNTY))
		  ,[MAILTO_STATE] = RTRIM(LTRIM(MAILTO_STATE))
		  ,[MAILTO_ZIP] = RTRIM(LTRIM(MAILTO_ZIP))
		  ,[MAILTO_EXT_ZIP] = RTRIM(LTRIM(MAILTO_EXT_ZIP))
		  ,[MAILTO_COUNTRY] = RTRIM(LTRIM(MAILTO_COUNTRY))
		  ,[MAILTO_ADDRESS_NAME] = RTRIM(LTRIM(MAILTO_ADDRESS_NAME))
		  ,[MAILTO_PHONE_NUMBER] = RTRIM(LTRIM(MAILTO_PHONE_NUMBER))
		  ,[MAILTO_PHONE_EXT] = RTRIM(LTRIM(MAILTO_PHONE_EXT))
		  ,[MAILTO_FAX_NUMBER] = RTRIM(LTRIM(MAILTO_FAX_NUMBER))
		  ,[MAILTO_EMAIL_ADDRESS] = RTRIM(LTRIM(MAILTO_EMAIL_ADDRESS))
		  ,[PAYTO_ADDRESS1] = RTRIM(LTRIM(PAYTO_ADDRESS1))
		  ,[PAYTO_ADDRESS2] = RTRIM(LTRIM(PAYTO_ADDRESS2))
		  ,[PAYTO_CITY] = RTRIM(LTRIM(PAYTO_CITY))
		  ,[PAYTO_COUNTY] = RTRIM(LTRIM(PAYTO_COUNTY))
		  ,[PAYTO_STATE] = RTRIM(LTRIM(PAYTO_STATE))
		  ,[PAYTO_ZIP] = RTRIM(LTRIM(PAYTO_ZIP))
		  ,[PAYTO_EXT_ZIP] = RTRIM(LTRIM(PAYTO_EXT_ZIP))
		  ,[PAYTO_COUNTRY] = RTRIM(LTRIM(PAYTO_COUNTRY))
		  ,[PAYTO_ADDRESS_NAME] = RTRIM(LTRIM(PAYTO_ADDRESS_NAME))
		  ,[PAYTO_PHONE_NUMBER] = RTRIM(LTRIM(PAYTO_PHONE_NUMBER))
		  ,[PAYTO_PHONE_EXT] = RTRIM(LTRIM(PAYTO_PHONE_EXT))
		  ,[PAYTO_FAX_NUMBER] = RTRIM(LTRIM(PAYTO_FAX_NUMBER))
		  ,[PAYTO_EMAIL_ADDRESS] = RTRIM(LTRIM(PAYTO_EMAIL_ADDRESS))
		  ,[BILLING_CONTACT_FIRST_NAME] = RTRIM(LTRIM(BILLING_CONTACT_FIRST_NAME))
		  ,[BILLING_CONTACT_LAST_NAME] = RTRIM(LTRIM(BILLING_CONTACT_LAST_NAME))
		  ,[CHECK_PAYABLE_TO_NAME] = RTRIM(LTRIM(CHECK_PAYABLE_TO_NAME))
		  ,[TERM_ENROLLMENT_STATUS] = RTRIM(LTRIM(TERM_ENROLLMENT_STATUS))
		  ,[PAYTO_ADDRESS3] = RTRIM(LTRIM(PAYTO_ADDRESS3))
		  ,[MAILTO_ADDRESS3] = RTRIM(LTRIM(MAILTO_ADDRESS3))
		  ,[SERVICING_ADDRESS3] = RTRIM(LTRIM(SERVICING_ADDRESS3))
		  ,[CBSA_NUM] = RTRIM(LTRIM(CBSA_NUM))
		  ,[SERVICING_LONGITUDE] = RTRIM(LTRIM(SERVICING_LONGITUDE))
		  ,[SERVICING_LATITUDE] = RTRIM(LTRIM(SERVICING_LATITUDE))
		  ,[REMITTANCE_ADVICENAME] = RTRIM(LTRIM(REMITTANCE_ADVICENAME))
		  ,[REMITTANCE_ADDRESS1] = RTRIM(LTRIM(REMITTANCE_ADDRESS1))
		  ,[REMITTANCE_ADDRESS2] = RTRIM(LTRIM(REMITTANCE_ADDRESS2))
		  ,[REMITTANCE_CITY] = RTRIM(LTRIM(REMITTANCE_CITY))
		  ,[REMITTANCE_STATE] = RTRIM(LTRIM(REMITTANCE_STATE))
		  ,[REMITTANCE_COUNTY] = RTRIM(LTRIM(REMITTANCE_COUNTY))
		  ,[REMITTANCE_ZIP] = RTRIM(LTRIM(REMITTANCE_ZIP))
		  ,[REMITTANCE_EXT_ZIP] = RTRIM(LTRIM(REMITTANCE_EXT_ZIP))
		  ,[REMITTANCE_PHONE_NUMBER] = RTRIM(LTRIM(REMITTANCE_PHONE_NUMBER))
		  ,[REMITTANCE_CONTACT_NAME] = RTRIM(LTRIM(REMITTANCE_CONTACT_NAME))
		  ,[REMITTANCE_CONTACT_TYPE] = RTRIM(LTRIM(REMITTANCE_CONTACT_TYPE))
		  ,[REMITTANCE_ORGANIZATION_NAME] = RTRIM(LTRIM(REMITTANCE_ORGANIZATION_NAME))
		  ,[REMITTANCE_EMAIL] = RTRIM(LTRIM(REMITTANCE_EMAIL))
		  ,[REMITTANCE_FAX_NUMBER] = RTRIM(LTRIM(REMITTANCE_FAX_NUMBER))
		  ,[OTHER_ADDRESS1] = RTRIM(LTRIM(OTHER_ADDRESS1))
		  ,[OTHER_ADDRESS2] = RTRIM(LTRIM(OTHER_ADDRESS2))
		  ,[OTHER_CITY] = RTRIM(LTRIM(OTHER_CITY))
		  ,[OTHER_STATE] = RTRIM(LTRIM(OTHER_STATE))
		  ,[OTHER_COUNTY] = RTRIM(LTRIM(OTHER_COUNTY))
		  ,[OTHER_ZIP] = RTRIM(LTRIM(OTHER_ZIP))
		  ,[OTHER_EXT_ZIP] = RTRIM(LTRIM(OTHER_EXT_ZIP))
		  ,[OTHER_PHONE_NUMBER] = RTRIM(LTRIM(OTHER_PHONE_NUMBER))
		  ,[OTHER_CONTACT_NAME] = RTRIM(LTRIM(OTHER_CONTACT_NAME))
		  ,[OTHER_CONTACT_TYPE] = RTRIM(LTRIM(OTHER_CONTACT_TYPE))
		  ,[OTHER_ORGANIZATION_NAME] = RTRIM(LTRIM(OTHER_ORGANIZATION_NAME))
		  ,[OTHER_EMAIL] = RTRIM(LTRIM(OTHER_EMAIL))
		  ,[OTHER_FAX_NUMBER] = RTRIM(LTRIM(OTHER_FAX_NUMBER))
		  ,[TAX_ENTITY_STATE_ID] = RTRIM(LTRIM(TAX_ENTITY_STATE_ID))
		  ,[W9_ADDRESS1] = RTRIM(LTRIM(W9_ADDRESS1))
		  ,[W9_ADDRESS2] = RTRIM(LTRIM(W9_ADDRESS2))
		  ,[W9_QUADRANT] = RTRIM(LTRIM(W9_QUADRANT))
		  ,[W9_WARD] = RTRIM(LTRIM(W9_WARD))
		  ,[W9_CITY] = RTRIM(LTRIM(W9_CITY))
		  ,[W9_STATE] = RTRIM(LTRIM(W9_STATE))
		  ,[W9_ZIP] = RTRIM(LTRIM(W9_ZIP))
		  ,[W9_EXT_ZIP] = RTRIM(LTRIM(W9_EXT_ZIP))
		  ,[W9_PHONE_NUMBER] = RTRIM(LTRIM(W9_PHONE_NUMBER))
		  ,[W9_FAX_NUMBER] = RTRIM(LTRIM(W9_FAX_NUMBER))
		  ,[OFFICE_MON] = RTRIM(LTRIM(OFFICE_MON))
		  ,[OFFICE_TUE] = RTRIM(LTRIM(OFFICE_TUE))
		  ,[OFFICE_WED] = RTRIM(LTRIM(OFFICE_WED))
		  ,[OFFICE_THU] = RTRIM(LTRIM(OFFICE_THU))
		  ,[OFFICE_FRI] = RTRIM(LTRIM(OFFICE_FRI))
		  ,[OFFICE_SAT] = RTRIM(LTRIM(OFFICE_SAT))
		  ,[OFFICE_SUN] = RTRIM(LTRIM(OFFICE_SUN))
		  ,[OFFICE_WEBSITE] = RTRIM(LTRIM(OFFICE_WEBSITE))
		  ,[SERVICING_CONTACT_NAME] = RTRIM(LTRIM(SERVICING_CONTACT_NAME))
		  ,[SERVICING_CONTACT_TYPE] = RTRIM(LTRIM(SERVICING_CONTACT_TYPE))
		  ,[SERVICING_ORGANIZATION_NAME] = RTRIM(LTRIM(SERVICING_ORGANIZATION_NAME))
		  ,[SERVICING_EMAIL] = RTRIM(LTRIM(SERVICING_EMAIL))
		  ,[PAYTO_CONTACT_NAME] = RTRIM(LTRIM(PAYTO_CONTACT_NAME))
		  ,[PAYTO_CONTACT_TYPE] = RTRIM(LTRIM(PAYTO_CONTACT_TYPE))
		  ,[PAYTO_ORGANIZATION_NAME] = RTRIM(LTRIM(PAYTO_ORGANIZATION_NAME))
		  ,[MAILTO_CONTACT_NAME] = RTRIM(LTRIM(MAILTO_CONTACT_NAME))
		  ,[MAILTO_CONTACT_TYPE] = RTRIM(LTRIM(MAILTO_CONTACT_TYPE))
		  ,[MAILTO_ORGANIZATION_NAME] = RTRIM(LTRIM(MAILTO_ORGANIZATION_NAME))
		  ,[MAILTO_QUADRANT] = RTRIM(LTRIM(MAILTO_QUADRANT))
		  ,[PAYTO_QUADRANT] = RTRIM(LTRIM(PAYTO_QUADRANT))
		  ,[SERVICING_QUADRANT] = RTRIM(LTRIM(SERVICING_QUADRANT))
		  ,[REMITTANCE_QUADRANT] = RTRIM(LTRIM(REMITTANCE_QUADRANT))
		  ,[OTHER_QUADRANT] = RTRIM(LTRIM(OTHER_QUADRANT))
		  ,[MAILTO_WARD] = RTRIM(LTRIM(MAILTO_WARD))
		  ,[PAYTO_WARD] = RTRIM(LTRIM(PAYTO_WARD))
		  ,[SERVICING_WARD] = RTRIM(LTRIM(SERVICING_WARD))
		  ,[REMITTANCE_WARD] = RTRIM(LTRIM(REMITTANCE_WARD))
		  ,[OTHER_WARD] = RTRIM(LTRIM(OTHER_WARD))
		  ,[OFFICE_TOTAL] = RTRIM(LTRIM(OFFICE_TOTAL))
		  ,[W9_COUNTY] = RTRIM(LTRIM(W9_COUNTY))
		  ,[W9_CONTACT_NAME] = RTRIM(LTRIM(W9_CONTACT_NAME))
		  ,[W9_EMAIL_ADDRESS] = RTRIM(LTRIM(W9_EMAIL_ADDRESS))
		  ,[W9_ORGANIZATION_NAME] = RTRIM(LTRIM(W9_ORGANIZATION_NAME))
		  ,[PAYTO_ADDRESS_FIRSTNAME] = RTRIM(LTRIM(PAYTO_ADDRESS_FIRSTNAME))
		  ,[PAYTO_ADDRESS_MIDDLENAME] = RTRIM(LTRIM(PAYTO_ADDRESS_MIDDLENAME))
		  ,[PAYTO_ADDRESS_LASTNAME] = RTRIM(LTRIM(PAYTO_ADDRESS_LASTNAME))
		  ,[PAYTO_ADDRESS_TITLE] = RTRIM(LTRIM(PAYTO_ADDRESS_TITLE))
		  ,[MAILTO_ADDRESS_FIRSTNAME] = RTRIM(LTRIM(MAILTO_ADDRESS_FIRSTNAME))
		  ,[MAILTO_ADDRESS_MIDDLENAME] = RTRIM(LTRIM(MAILTO_ADDRESS_MIDDLENAME))
		  ,[MAILTO_ADDRESS_LASTNAME] = RTRIM(LTRIM(MAILTO_ADDRESS_LASTNAME))
		  ,[MAILTO_ADDRESS_TITLE] = RTRIM(LTRIM(MAILTO_ADDRESS_TITLE))
		  ,[REMITTANCE_ADDRESS_FIRSTNAME] = RTRIM(LTRIM(REMITTANCE_ADDRESS_FIRSTNAME))
		  ,[REMITTANCE_ADDRESS_MIDDLENAME] = RTRIM(LTRIM(REMITTANCE_ADDRESS_MIDDLENAME))
		  ,[REMITTANCE_ADDRESS_LASTNAME] = RTRIM(LTRIM(REMITTANCE_ADDRESS_LASTNAME))
		  ,[REMITTANCE_ADDRESS_TITLE] = RTRIM(LTRIM(REMITTANCE_ADDRESS_TITLE))
		  ,[OTHER_ADDRESS_FIRSTNAME] = RTRIM(LTRIM(OTHER_ADDRESS_FIRSTNAME))
		  ,[OTHER_ADDRESS_MIDDLENAME] = RTRIM(LTRIM(OTHER_ADDRESS_MIDDLENAME))
		  ,[OTHER_ADDRESS_LASTNAME] = RTRIM(LTRIM(OTHER_ADDRESS_LASTNAME))
		  ,[OTHER_ADDRESS_TITLE] = RTRIM(LTRIM(OTHER_ADDRESS_TITLE))


	UPDATE [dbo].[REG_ADDITIONAL_ADDRESSES]
	   SET [ADDRESS_DESC] = RTRIM(LTRIM(ADDRESS_DESC))
		  ,[ADDRESS1] = RTRIM(LTRIM(ADDRESS1))
		  ,[ADDRESS2] = RTRIM(LTRIM(ADDRESS2))
		  ,[CITY] = RTRIM(LTRIM(CITY))
		  ,[STATE] = RTRIM(LTRIM(STATE))
		  ,[ZIP] = RTRIM(LTRIM(ZIP))
		  ,[EXT_ZIP] = RTRIM(LTRIM(EXT_ZIP))
		  ,[COUNTY] = RTRIM(LTRIM(COUNTY))
		  ,[PHONE] = RTRIM(LTRIM(PHONE))
		  ,[PHONE_EXT] = RTRIM(LTRIM(PHONE_EXT))
		  ,[WARD] = RTRIM(LTRIM(WARD))
		  ,[QUADRANT] = RTRIM(LTRIM(QUADRANT))
		  ,[ADDRESS3] = RTRIM(LTRIM(ADDRESS3))

	UPDATE [dbo].[REG_DEA]
	   SET [DEA_NUMBER] = RTRIM(LTRIM(DEA_NUMBER))
		  ,[DEA_STATE] = RTRIM(LTRIM(DEA_STATE))

	UPDATE [dbo].[REG_MEDICAID]
	   SET [MEDICAID_NUMBER] = RTRIM(LTRIM(MEDICAID_NUMBER))
		  ,[MEDICAID_STATE] = RTRIM(LTRIM(MEDICAID_STATE))
		  ,[NPI] = RTRIM(LTRIM(NPI))

	UPDATE [dbo].[REG_OWNER]
	   SET [NAME] = RTRIM(LTRIM(NAME))
		  ,[TAX_ID] = RTRIM(LTRIM(TAX_ID))
		  ,[TITLE] = RTRIM(LTRIM(TITLE))
		  ,[ADDRESS1] = RTRIM(LTRIM(ADDRESS1))
		  ,[ADDRESS2] = RTRIM(LTRIM(ADDRESS2))
		  ,[CITY] = RTRIM(LTRIM(CITY))
		  ,[STATE] = RTRIM(LTRIM(STATE))
		  ,[ZIP] = RTRIM(LTRIM(ZIP))
		  ,[EXT_ZIP] = RTRIM(LTRIM(EXT_ZIP))
		  ,[ADDRESS3] = RTRIM(LTRIM(ADDRESS3))
		  ,[QUADRANT] = RTRIM(LTRIM(QUADRANT))
		  ,[COUNTY] = RTRIM(LTRIM(COUNTY))

	UPDATE [dbo].[REG_ENROLLMENT]
	   SET [ENROLLMENT_STATUS_CODE] = RTRIM(LTRIM(ENROLLMENT_STATUS_CODE))


END

GO

