/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulateSPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF]    Script Date: 8/1/2016 3:13:13 PM ******/
IF object_id('[dbo].[DCConv_LkUp_PopulateSPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF]','P') is not null
DROP PROCEDURE [dbo].[DCConv_LkUp_PopulateSPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Richard Mays
-- Create date: 7/21/2016
-- Description:	Fills the ORGANIZATION_TYPE
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulateSPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF] 
	@pin_run_reference_time datetime
AS
BEGIN



IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 1)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 1, SPECIALTY_TYPE_ID, 'Art Therapist certified to practice art therapy by the American Art Therapy Association, Inc. and/or credentialing of the Art Therapy Credentialing Board.', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 723

	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 1, SPECIALTY_TYPE_ID, 'Dance Therapist (as defined in Chapter 71 (Dance Therapy), Title 17 (Business Occupations, and Professions) of the DCMR;', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 724

	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 1, SPECIALTY_TYPE_ID, 'Drama Therapist (as certified by the National Assocation for Drama Therapy)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 725

	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 1, SPECIALTY_TYPE_ID, 'Music Therapist (as certified by the Certification Board for Music Therapists, which is managed by the American Music Therapy Association)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 728
END
ELSE
BEGIN
	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Art Therapist certified to practice art therapy by the American Art Therapy Association, Inc. and/or credentialing of the Art Therapy Credentialing Board.'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Art Therapist%'

	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Dance Therapist (as defined in Chapter 71 (Dance Therapy), Title 17 (Business Occupations, and Professions) of the DCMR;'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Dance Therapist%'

	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Drama Therapist (as certified by the National Assocation for Drama Therapy)'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Drama Therapist%'

	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Music Therapist (as certified by the Certification Board for Music Therapists, which is managed by the American Music Therapy Association)'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Music Therapist%'
END

if NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 2)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 2, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 716
END

if NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 18)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 18, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 706
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 3)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 3, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 758
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 4)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 4, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 709
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 5)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 5, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID IN (718, 733, 732,701)
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 6)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 6, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 734
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 7)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 7, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 753
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 8)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 8, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 735
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 9)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 9, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 710
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 10)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 10, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 704
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 11)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 11, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 705
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 12)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 12, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 731
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 13)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 13, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 701
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 14)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 14, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 746
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 15)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 15, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 755
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 16)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 16, SPECIALTY_TYPE_ID, @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID IN (726, 727, 702, 750, 729)
END

IF NOT EXISTS(SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17)
BEGIN
	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 17, SPECIALTY_TYPE_ID, 'Small Group Day Habilitation Services (See Section 1920, Chapter 19 of Title 29, DCMR)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 706

	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 17, SPECIALTY_TYPE_ID, 'Dental (See Section 1921, Chapter 19 of Title 29, DCMR)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 700

	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 17, SPECIALTY_TYPE_ID, 'One-Time Transitional Services (See Section 1913, Chapter 19 of Title 29, DCMR)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 719

	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 17, SPECIALTY_TYPE_ID, 'Supported Living Services (See Section 1934, Chapter 9 of Title 29, DCMR)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 736

	INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
	SELECT 17, SPECIALTY_TYPE_ID, 'Vehicle Modifications (See Section 1914, Chapter 19 of Title 29, DCMR)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 720
END
ELSE -- The category exists, but the linked specialty doesn't
BEGIN 
	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID = (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 706))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Small Group Day Habilitation Services (See Section 1920, Chapter 19 of Title 29, DCMR)', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 706
	END
END



	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Art Therapist certified to practice art therapy by the American Art Therapy Association, Inc. and/or credentialing of the Art Therapy Credentialing Board.'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Art Therapist%'

	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Dance Therapist (as defined in Chapter 71 (Dance Therapy), Title 17 (Business Occupations, and Professions) of the DCMR;'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Dance Therapist%'

	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Drama Therapist (as certified by the National Assocation for Drama Therapy)'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Drama Therapist%'

	UPDATE SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF
	SET SPECIALTY_TYPE_ALT_TEXT = 'Music Therapist (as certified by the Certification Board for Music Therapists, which is managed by the American Music Therapy Association)'
	WHERE SPECIALTY_CATEGORY_ID = 1
	AND SPECIALTY_TYPE_ALT_TEXT LIKE '%Music Therapist%'


	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 711))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Case Management', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 711
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 712))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Chore', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 712
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 717))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Community Support Team', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = 717
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '033'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'General Dentistry', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '033'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '044'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Geriatric Medicine', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '044'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '713'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Homemaker', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '713'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '737'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Live-in Caregiver', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '737'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '703' AND SPECIALTY_TYPE_NAME = 'MRDD Personal Care Aide'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Personal Care Aide', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '703' AND SPECIALTY_TYPE_NAME = 'MRDD Personal Care Aide'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '708'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Prevocational', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '708'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '715' AND SPECIALTY_TYPE_NAME = 'Personal Care Aid State Plan'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Personal Care Aid State Plan', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '715' AND SPECIALTY_TYPE_NAME = 'Personal Care Aid State Plan'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '754'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Shared Living', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '754'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '756'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Supported living Without Transportation', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '756'
	END

	IF NOT EXISTS (SELECT * FROM SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF WHERE SPECIALTY_CATEGORY_ID = 17 AND SPECIALTY_TYPE_ID IN (SELECT SPECIALTY_TYPE_ID FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '747'))
	BEGIN
		INSERT INTO SPECIALTY_TYPE_SPECIALTY_CATEGORY_XREF (SPECIALTY_CATEGORY_ID, SPECIALTY_TYPE_ID, SPECIALTY_TYPE_ALT_TEXT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER)
		SELECT 17, SPECIALTY_TYPE_ID, 'Small group supported employment', @pin_run_reference_time, N'5d0689a8-d885-4211-b9fd-56757474ab4d' FROM SPECIALTY_TYPE WHERE MMIS_SPECIALTY_TYPE_ID = '747'
	END



END

GO