/****** Object:  StoredProcedure [dbo].[DCConv_LkUp_PopulatePROVIDER_TYPE_FEE]    Script Date: 8/23/2016  ******/
IF object_id('[dbo].[DCConv_LkUp_PopulatePROVIDER_TYPE_FEE]','P') is not null
DROP PROCEDURE [dbo].[DCConv_LkUp_PopulatePROVIDER_TYPE_FEE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Andrew Zovistoski
-- Create date: 08/23/2016
-- Description:	Fills the PROVIDER_TYPE_FEE
-- =============================================
CREATE PROCEDURE [dbo].[DCConv_LkUp_PopulatePROVIDER_TYPE_FEE] 
	@pin_run_reference_time datetime
AS
BEGIN

	SET NOCOUNT ON;

	DELETE FROM PROVIDER_TYPE_FEE;

	DBCC CHECKIDENT ('PROVIDER_TYPE_FEE', RESEED, 0);

	INSERT INTO PROVIDER_TYPE_FEE
	 (PROVIDER_TYPE_ID, IS_FEE_REQUIRED, FEE_AMOUNT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, ENTITY_TYPE_ID)
	SELECT PROVIDER_TYPE_ID, 1 as IS_FEE_REQUIRED, 552.00 as FEE_AMOUNT, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME, 
	'5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER, PROVIDER_CATEGORY_TYPE_ID
	FROM dbo.PROVIDER_TYPE 
	WHERE  MMIS_PROVIDER_TYPE_ID IN ('B00', 'B01', 'D00', 'D01', 'D02', 'D03', 'D04', 'E00', 'F00','H00','H01', 'I00', 'J00', 'J01', 'J02', 'L00', 'L01', 'Q01', 'Q02', 'T00', 'V00',  'X05' );

	-- Additional
	-- Get the provider type details into a temp table
	SELECT PROVIDER_TYPE_ID, PROVIDER_CATEGORY_TYPE_ID, PROVIDER_TYPE_NAME, MMIS_PROVIDER_TYPE_ID
	INTO #prov
	FROM PROVIDER_TYPE
	WHERE MMIS_PROVIDER_TYPE_ID IN ('J02', 'J00', 'J01', 'V00', 'X05', 'I00', 'Q01', 'L00', 'L01', 'D04', 'D00', 'D01', 'D03', 'D02', 'B01', 'B01', 'B00', 'F00', 'H01', 'H00', 'E00', 'T00')
	AND PROVIDER_CATEGORY_TYPE_ID = 3

	-- Insert into PROVIDER_TYPE_FEE only records where they aren't already found
	INSERT INTO PROVIDER_TYPE_FEE (PROVIDER_TYPE_ID, IS_FEE_REQUIRED, FEE_AMOUNT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_USER, ENTITY_TYPE_ID)
	SELECT p.PROVIDER_TYPE_ID, 1 as IS_FEE_REQUIRED, 552.00 as FEE_AMOUNT, @pin_run_reference_time as LAST_MODIFIED_DATE_TIME,
	'5D0689A8-D885-4211-B9FD-56757474AB4D' as LAST_MODIFIED_USER, p.PROVIDER_CATEGORY_TYPE_ID
	FROM #prov p
	LEFT OUTER JOIN PROVIDER_TYPE_FEE fee ON p.PROVIDER_TYPE_ID = fee.PROVIDER_TYPE_ID
	WHERE fee.PROVIDER_TYPE_ID IS NULL


END

GO
