<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <!-- <Import Project="$(MSBuildExtensionsPath)\ExtensionPack\4.0\MSBuild.ExtensionPack.tasks"/>  -->
  <Target Name="CopyDeployFiles" AfterTargets="TransformAppSettings" >
    <Message Text="Copy Deploy Files" />
    <Message Text="DeployFilesDirectory = $(DeployFilesDirectory) PackageFileName = $(PackageFileName) WPPAllFilesInSingleFolder = $(WPPAllFilesInSingleFolder)" />
    <MakeDir Directories="$(PackageUrl)" />
    <MSBuild.ExtensionPack.Compression.Zip TaskAction="Create" CompressPath="$(WPPAllFilesInSingleFolder)" ZipFileName="$(PackageUrl)$(PackageFileName)" RemoveRoot="$(WPPAllFilesInSingleFolder)"/>
  </Target>
  <Target Name="TransformAppSettings" AfterTargets="CopyAllFilesToSingleFolderForPackage" Condition="exists('AppSettings.dll.$(PublishProfileName).config')">
    <Message Importance="normal" Text="Transforming AppSettings.dll.config. Using AppSettings.dll.$(PublishProfileName).config to Transform $(WPPAllFilesInSingleFolder)\bin\AppSettings.dll.config" />
    <TransformXml Source="$(WPPAllFilesInSingleFolder)\bin\AppSettings.dll.config" Destination="$(WPPAllFilesInSingleFolder)\bin\AppSettings.dll.config" Transform="AppSettings.dll.$(PublishProfileName).config" />
    <Message Importance="normal" Text="Transforming AppSettings.dll.config. Using AppSettings.dll.$(PublishProfileName).config to Transform $(WPPAllFilesInSingleFolder)\AppSettings.dll.config" />
    <TransformXml Source="$(WPPAllFilesInSingleFolder)\AppSettings.dll.config" Destination="$(WPPAllFilesInSingleFolder)\AppSettings.dll.config" Transform="AppSettings.dll.$(PublishProfileName).config" />
  </Target>
  <PropertyGroup>
    <ExcludeFilesFromDeployment>
      AppSettings.dll.Conv.config;AppSettings.dll.DevMax.config;AppSettings.dll.IntegrationMax.config;AppSettings.dll.Modern.config;AppSettings.dll.Production.config;AppSettings.dll.UAT.config;
    </ExcludeFilesFromDeployment>
  </PropertyGroup>
</Project>