using Corp.Core.Libraries;
using MAXIMUS.Core.Libraries;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Net;
using CON = MAXIMUS.Core.Libraries.Constants;

namespace MAXIMUS.Controllers.PDMS
{
    public static class TransactionController
    {
        public static int InsertTransactionQueue(
            int transactionTypeId
            , int regId
            , int medicaidPK
            , DateTime? createDate
            , DateTime? submitDate
            , DateTime? processDate
            , DateTime? changedDate
            , string changedBy
            , bool is_frm_job = false)
        {
            int returnVal = 0;

            try
            {
                // generated by sp_Admin_StoredProcBuilder on Jul 31 2013  4:57PM
                // create parameters objects and fill with values
                List<SqlParameter> parameters = new List<SqlParameter>();

                parameters.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, transactionTypeId, true));
                parameters.Add(SqlParms.CreateParameter("REG_ID", DbType.Int32, regId, true));
                parameters.Add(SqlParms.CreateParameter("MEDICAID_PK", DbType.Int32, medicaidPK, true));
                parameters.Add(SqlParms.CreateParameter("SUBMIT_DATE_TIME", DbType.DateTime, submitDate, true));
                parameters.Add(SqlParms.CreateParameter("PROCESS_DATE_TIME", DbType.DateTime, processDate, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, changedDate, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, changedBy, true));
                parameters.Add(SqlParms.CreateParameter("IS_TRANSACTION_CREATED_BY_JOB", DbType.Boolean, is_frm_job, false));

                returnVal = Methods.GetIntValue(DataAccess.ExecuteScalar("usp_SaveTransaction", parameters));
                // DataAccess.ExecuteStoredProcedure("usp_SaveTransaction", parameters);
            }
            catch (Exception ex)
            {
                throw CoreException.ThrowException(ex);
            }
            return returnVal;
        }

        public static void UpdateTransactionQueue(
            int transactionQueueId
            , DateTime? submitDate
            , DateTime? processDate
            , DateTime? changedDate
            , string changedBy)
        {
            try
            {
                List<SqlParameter> parameters = new List<SqlParameter>();

                parameters.Add(SqlParms.CreateParameter("TRANSACTION_QUEUE_ID", DbType.Int32, transactionQueueId, true));
                parameters.Add(SqlParms.CreateParameter("SUBMIT_DATE_TIME", DbType.DateTime, submitDate, true));
                parameters.Add(SqlParms.CreateParameter("PROCESS_DATE_TIME", DbType.DateTime, processDate, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, changedDate, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, changedBy, true));

                DataAccess.ExecuteStoredProcedure("usp_SaveTransaction", parameters);
            }
            catch (Exception ex)
            {
                throw CoreException.ThrowException(ex);
            }
        }

		public static void UpdateTransactionQueueByStagingGroupPK(
			int stagingGroupPK
			, DateTime? submitDate
			, DateTime? processDate
			, DateTime? changedDate
			, string changedBy)
		{
			try
			{
				List<SqlParameter> parameters = new List<SqlParameter>();

				parameters.Add(SqlParms.CreateParameter("MMIS_STAGING_GROUP_PK", DbType.Int32, stagingGroupPK, true));
				parameters.Add(SqlParms.CreateParameter("SUBMIT_DATE_TIME", DbType.DateTime, submitDate, true));
				parameters.Add(SqlParms.CreateParameter("PROCESS_DATE_TIME", DbType.DateTime, processDate, true));
				parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, changedDate, true));
				parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, changedBy, true));

				DataAccess.ExecuteStoredProcedure("usp_UpdateTransactionsByGroupStagingPK", parameters);
			}
			catch (Exception ex)
			{
				throw CoreException.ThrowException(ex);
			}
		}

        public static void UpdateTransactionQueue(
            int transactionTypeId
            , int partyId
            , int? medicaidPK
            , DateTime? submitDate
            , DateTime? processDate
            , DateTime? changedDate
            , string changedBy)
        {
            try
            {
                // generated by sp_Admin_StoredProcBuilder on Aug 20 2013  4:44PM
                // create parameters objects and fill with values
                List<SqlParameter> parameters = new List<SqlParameter>();

                parameters.Add(SqlParms.CreateParameter("PARTY_ID", DbType.Int32, partyId, true));
				if (medicaidPK.HasValue)
				{
					parameters.Add(SqlParms.CreateParameter("MEDICAID_PK", DbType.Int32, medicaidPK, true));
				}
                parameters.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, transactionTypeId, true));
                parameters.Add(SqlParms.CreateParameter("SUBMIT_DATE_TIME", DbType.DateTime, submitDate, true));
                parameters.Add(SqlParms.CreateParameter("PROCESS_DATE_TIME", DbType.DateTime, processDate, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, changedDate, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, changedBy, true));

                DataAccess.ExecuteStoredProcedure("usp_SaveTransaction", parameters);
            }
            catch (Exception ex)
            {
                throw CoreException.ThrowException(ex);
            }
        }

        public static DataSet SelectTransactionQueue(
            int transactionTypeId, 
            int partyId, 
            int medicaidPK)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("TRANSACTION_TYPE_ID", DbType.Int32, transactionTypeId, true));
            parameters.Add(SqlParms.CreateParameter("PARTY_ID", DbType.Int32, partyId, true));
            parameters.Add(SqlParms.CreateParameter("MEDICAID_PK", DbType.Int32, medicaidPK, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("selectTRANSACTION_QUEUE", parameters, "Queue");
            ds.Tables[0].TableName = "Queue";

            return ds;
        }

        public static DataSet SelectTransactions(
            string TransactionTypeId = null, 
            string ProcessStartDate = null, 
            string ProcessEndDate = null, 
            string PartyID = null, 
            string ServiceLocationID = null, 
            string MedicaidID = null, 
            string CAQHId = null, 
            string OrderBy = null, 
            string SortOrder = null)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();

            if(TransactionTypeId != null)
                parameters.Add(SqlParms.CreateParameter("TransactionTypeId", DbType.Int32, TransactionTypeId, true));

            if(ProcessStartDate != null)
                parameters.Add(SqlParms.CreateParameter("ProcessStartDate", DbType.DateTime, ProcessStartDate, true));

            if(ProcessEndDate != null)
                parameters.Add(SqlParms.CreateParameter("ProcessEndDate", DbType.DateTime, ProcessEndDate, true));

            if(PartyID != null)
                parameters.Add(SqlParms.CreateParameter("PartyID", DbType.Int32, PartyID, true));

            if(ServiceLocationID != null)
                parameters.Add(SqlParms.CreateParameter("ServiceLocationID", DbType.Int32, ServiceLocationID, true));

            if(MedicaidID != null)
                parameters.Add(SqlParms.CreateParameter("MedicaidID", DbType.String, MedicaidID, true));

            if(CAQHId != null)
                parameters.Add(SqlParms.CreateParameter("CAQHId", DbType.String, CAQHId, true));

            if(OrderBy != null)
                parameters.Add(SqlParms.CreateParameter("OrderBy", DbType.Int32, TransactionColumn(OrderBy), true));

            if(SortOrder != null)
                parameters.Add(SqlParms.CreateParameter("SortOrder", DbType.Int32, SortOrder.ToUpper().Equals("ASC"), true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SelectTransactions", parameters, "Transactions");
            if(ObjectControllerHelper.HasRows(ds))
                ds.Tables[0].TableName = "Transactions";

            return ds;
        }

        public static void CancelTransaction(
            int transactionId, 
            DateTime lastModifiedDateTime, 
            string lastModifiedUser)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("TRANSACTION_QUEUE_ID", DbType.Int32, transactionId, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, lastModifiedDateTime, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, lastModifiedUser, true));

            DataAccess.ExecuteStoredProcedure("usp_CancelTransaction", parameters);
        }

        public static void ResubmitProcessedTransaction(
            int transactionId,
            DateTime lastModifiedDateTime,
            string lastModifiedUser
            ,bool isCreatedByJob = false)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("TRANSACTION_QUEUE_ID", DbType.Int32, transactionId, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, lastModifiedDateTime, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, lastModifiedUser, true));
            parameters.Add(SqlParms.CreateParameter("IS_TRANSACTION_CREATED_BY_JOB", DbType.Boolean, isCreatedByJob, true));

            string tq = DataAccess.ExecuteScalar("usp_ResubmitProcessedTransaction", parameters);
            int.TryParse(tq, out int tqId);

            List<SqlParameter> param = new List<SqlParameter>();
            param.Add(SqlParms.CreateParameter("TransactionID", DbType.Int32, tqId, true));
            DataSet ds = DataAccess.ExecuteStoredProcedure("usp_SelectTransactionDetailsByTransactionID", param, "TransactionDetails");

            if (Methods.HasRows(ds))
            {
                string txnResult = string.Empty;
                int transactionType = Methods.GetIntValue(ds.Tables[0].Rows[0],"TRANSACTION_TYPE_ID");

                ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;
                ProviderManagementReqRes pmrr = new ProviderManagementReqRes();
                PartialProviderRequestResponse pprr = new PartialProviderRequestResponse();

                switch (transactionType)
                {
                    case (int)TransactionController.TransactionTypeNew.SendMMISEnroll:
                        RegistrationController.PopulateStagingData(tqId, CON.TransactionTypeValues.MITS, string.Empty);
                        txnResult = pmrr.providerManagementEnrollRequest(tqId, true);
                        break;

                    case (int)TransactionController.TransactionTypeNew.SendMMISUpdate:
                        RegistrationController.PopulateStagingData(tqId, CON.TransactionTypeValues.MITS, string.Empty);
                        txnResult = pmrr.providerManagementUpdateRequest(tqId, true);
                        break;

                    case (int)TransactionController.TransactionTypeNew.SendPCWFull:
                        RegistrationController.PopulateStagingData(tqId, CON.TransactionTypeValues.PCW_Full, string.Empty);
                        txnResult = pprr.partialProviderManagementSubmitRequest(tqId, Constants.PartialProviderSubscriberSystems.PCW, true);
                        break;

                    case (int)TransactionController.TransactionTypeNew.SendPSMFull:
                        RegistrationController.PopulateStagingData(tqId, CON.TransactionTypeValues.PSM_FULL, string.Empty);
                        txnResult = pprr.partialProviderManagementSubmitRequest(tqId, Constants.PartialProviderSubscriberSystems.PSM, true);
                        break;

                    case (int)TransactionController.TransactionTypeNew.SendPCWPartial:
                        RegistrationController.PopulateStagingData(tqId, CON.TransactionTypeValues.PCW_Partial, string.Empty);
                        txnResult = pprr.partialProviderManagementSubmitRequest(tqId, Constants.PartialProviderSubscriberSystems.PCW, true);
                        break;

                    case (int)TransactionController.TransactionTypeNew.SendPSMPartial:
                        RegistrationController.PopulateStagingData(tqId, CON.TransactionTypeValues.PSM_Partial, string.Empty);
                        txnResult = pprr.partialProviderManagementSubmitRequest(tqId, Constants.PartialProviderSubscriberSystems.PSM, true);
                        break;
                }
            }
        }

        /// <summary>
        /// To regenerate the list from the database run the following query
        ///     SELECT
         ///     dbo.fn_GetOnlyAlphaNumericValues(TRANSACTION_TYPE,1,1)
         ///     + ' = ' + CONVERT(varchar(4),TRANSACTION_TYPE_ID) + ','
        ///     FROM TRANSACTION_TYPE
        ///     ORDER BY TRANSACTION_TYPE_ID  
        /// </summary>
        public enum TransactionType
        {
            RequestMedicaidIDfromMMIS = 1,
            SendProviderUpdatestoMMIS = 2,
            SendProviderStatusChangetoMMIS = 3,
            SendGroupAffiliationstoMMIS = 4,
            SendPaymentInfotoMMIS = 5,
            SendProviderUpdatestoCAQH = 6,
            RequestBaseMedicaidIDfromMMIS = 7,
            RetrieveGroupsfromMMIS = 8,
            RetrieveGroupAffiliationsfromMMIS = 9,
            SendSpecialty2ToMMIS = 21,
            SendSpecialty3ToMMIS = 22,
            SendNPIUpdateToMMIS = 23,
            SendCBSAUpdateToMMIS = 24
        }

        public enum TransactionTypeNew
        {
            SendMMISUpdate = 1,
            SendMMISEnroll = 2,
            SendPSMPartial = 3,
            SendPCWPartial = 4,
            SendPSMFull = 5,
            SendPCWFull = 6
        }

        private static int TransactionColumn(string column)
        {
            switch(column)
            {
                case "TransactionQueueId":
                    return 1;
                case "TransactionType":
                    return 2;
                case "TransactionTypeId":
                    return 3;
                case "PartyId":
                    return 4;
                case "PartyType":
                    return 5;
                case "CAQHID":
                    return 6;
                case "ServiceLocationID":
                    return 7;
                case "ServiceLocationType":
                    return 8;
                case "MedicaidId":
                    return 8;
                default:
                    return 0;
            }
        }

        public static DataSet SelectTransactionIDsByRegID(int regID)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("REG_ID", DbType.Int32, regID, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SelectTransactionQueueIDByRegID", parameters, "TransactionQueueIDByRegID");
            ds.Tables[0].TableName = "TransactionQueueIDByRegID";

            return ds;
        }

        public static DataSet SelectTransactionDetailsByTransactionID(int transactionID)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("TransactionID", DbType.Int32, transactionID, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SelectTransactionDetailsByTransactionID", parameters, "TransactionDetailsByTransactionID");
            ds.Tables[0].TableName = "TransactionDetailsByTransactionID";

            return ds;
        }

        public static DataSet SelectRescentTransactionIDByRegID(int regID)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("REG_ID", DbType.Int32, regID, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SelectRescentTransactionQueueIDByRegID", parameters, "RescentTranQueueIDByRegID");
            ds.Tables[0].TableName = "RescentTranQueueIDByRegID";

            return ds;
        }

        public static DataSet SearchTransactions(string transactionStatus, string regId, string medicaidID, string fromDate, string toDate, string sortBy, int pageSize, int pageNumber, bool asc, string SubscriberFailed, out int totalResultCount)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            string outValue;
            totalResultCount = 0;

            if (!string.IsNullOrWhiteSpace(transactionStatus))
            {
                parameters.Add(SqlParms.CreateParameter("TransactionStatus", DbType.String, transactionStatus, true));
            }
            if (!string.IsNullOrWhiteSpace(regId))
            {
                parameters.Add(SqlParms.CreateParameter("RegID", DbType.String, regId, true));
            }
            if (!string.IsNullOrWhiteSpace(medicaidID))
            {
                parameters.Add(SqlParms.CreateParameter("MedicaidID", DbType.String, medicaidID, true));
            }
            if (!string.IsNullOrWhiteSpace(fromDate))
            {
                parameters.Add(SqlParms.CreateParameter("FromDate", DbType.String, fromDate, true));
            }
            if (!string.IsNullOrWhiteSpace(toDate))
            {
                parameters.Add(SqlParms.CreateParameter("ToDate", DbType.String, toDate, true));
            }
            parameters.Add(SqlParms.CreateParameter("SortBy", DbType.String, sortBy, true));
            parameters.Add(SqlParms.CreateParameter("PageNumber", DbType.Int32, pageNumber, true)); 
            parameters.Add(SqlParms.CreateParameter("RowsPerPage", DbType.Int32, pageSize, true));
            parameters.Add(SqlParms.CreateParameter("ASC", DbType.Boolean, asc, true));
            parameters.Add(SqlParms.CreateParameter("SubscriberFailed", DbType.String, SubscriberFailed, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SearchTransactionCustom", parameters, "TotalResultCount", SqlDbType.Int, out outValue, 0);
            ds.Tables[0].TableName = "TQ";
            if (!string.IsNullOrEmpty(outValue))
            {
                totalResultCount = Convert.ToInt32(outValue);
            }

            return ds;
        }

        public static DataSet SearchTransactionsMonitor(string regId, string medicaidID, string fromDate, string toDate,
    string sortBy, int pageSize, int pageNumber, bool asc, bool nwffailures, out int totalResultCount)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            string outValue;
            totalResultCount = 0;

            if (!string.IsNullOrWhiteSpace(regId))
            {
                parameters.Add(SqlParms.CreateParameter("RegID", DbType.String, regId, true));
            }
            if (!string.IsNullOrWhiteSpace(medicaidID))
            {
                parameters.Add(SqlParms.CreateParameter("MedicaidID", DbType.String, medicaidID, true));
            }
            if (!string.IsNullOrWhiteSpace(fromDate))
            {
                parameters.Add(SqlParms.CreateParameter("FromDate", DbType.String, fromDate, true));
            }
            if (!string.IsNullOrWhiteSpace(toDate))
            {
                parameters.Add(SqlParms.CreateParameter("ToDate", DbType.String, toDate, true));
            }


            parameters.Add(SqlParms.CreateParameter("SortBy", DbType.String, sortBy, true));
            parameters.Add(SqlParms.CreateParameter("PageNumber", DbType.Int32, pageNumber, true));
            parameters.Add(SqlParms.CreateParameter("RowsPerPage", DbType.Int32, pageSize, true));
            parameters.Add(SqlParms.CreateParameter("ASC", DbType.Boolean, asc, true));
            parameters.Add(SqlParms.CreateParameter("NWffailures", DbType.Boolean, nwffailures, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SearchTransactionCustom2", parameters, "TotalResultCount", SqlDbType.Int, out outValue, 0);
            ds.Tables[0].TableName = "TQ";
            if (!string.IsNullOrEmpty(outValue))
            {
                totalResultCount = Convert.ToInt32(outValue);
            }

            return ds;
        }

        public static DataSet GetTransactionsMonitorCounts()
        {          
            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_TransactionMonitorCounts");
            ds.Tables[0].TableName = "TQCounts";
            return ds;
        }

        public static DataSet SearchByREGID(string regId, string tableName, string tableType, int pageSize, int pageNumber, string medId=null)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            string outValue;
            parameters.Add(SqlParms.CreateParameter("REG_ID", DbType.String, regId, true));
            parameters.Add(SqlParms.CreateParameter("TableName", DbType.String, tableName , true));
            parameters.Add(SqlParms.CreateParameter("TableType", DbType.String, tableType, true));
            parameters.Add(SqlParms.CreateParameter("Med_ID", DbType.String, medId, true));
            parameters.Add(SqlParms.CreateParameter("PageNumber", DbType.Int32, pageNumber, true));
            parameters.Add(SqlParms.CreateParameter("RowsPerPage", DbType.Int32, pageSize, true));


            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_GetResultsByObject", parameters, "TotalResultCount", SqlDbType.Int, out outValue, 0);
            if(ds.Tables.Count > 0)
                ds.Tables[0].TableName = "TableResults";
            return ds;
        }


        public static void UpdateTransactionAssignedStatus(int transactionQueueID, string assignedStatus, string userId)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("TRANSACTION_QUEUE_ID", DbType.Int32, transactionQueueID , true));
            parameters.Add(SqlParms.CreateParameter("AssignedStatus", DbType.String, assignedStatus, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, DateTime .Now, true));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, userId , true));
            DataAccess.ExecuteStoredProcedure("UpdateTransactionAssignedStatus", parameters);
        }

        public static bool CheckIfDocumentStaged(int transactionQueueID, string documentTitle)
        {
            bool checkIf = false;
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("TransactionQueueID", DbType.Int32, transactionQueueID, true));
            parameters.Add(SqlParms.CreateParameter("SECTION_TITLE", DbType.String, documentTitle, true));
            
            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_CheckIfDocumentStaged", parameters, "TQ");
            ds.Tables[0].TableName = "TQ";
            if (ObjectControllerHelper.HasRows(ds))
            {
                checkIf = true;
            }
            return checkIf;
        }
        // MQSearch -- AP
        public static DataSet SearchMQSearch(out int totalCount, int que, DateTime? fromDate, DateTime? toDate)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            string outValue;
            totalCount = 0;
            parameters.Add(SqlParms.CreateParameter("que", DbType.Int32, que, true));
            parameters.Add(SqlParms.CreateParameter("fromDate", DbType.DateTime, fromDate, true));
            parameters.Add(SqlParms.CreateParameter("toDate", DbType.DateTime, toDate, true));


            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SearchMQ", parameters, "ResultCount", SqlDbType.Int, out outValue, 0);
            ds.Tables[0].TableName = "TQ";
            if (!string.IsNullOrEmpty(outValue))
            {
                totalCount = Convert.ToInt32(outValue);
            }

            return ds;
        }

        public static DataSet SearchMQSearchData(out int totalCount, int que, DateTime? fromDate, DateTime? toDate,
            string RegId, string MedicaidId)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            string outValue;
            totalCount = 0;
            parameters.Add(SqlParms.CreateParameter("que", DbType.Int32, que, true));
            parameters.Add(SqlParms.CreateParameter("fromDate", DbType.DateTime, fromDate, true));
            parameters.Add(SqlParms.CreateParameter("toDate", DbType.DateTime, toDate, true));
            parameters.Add(SqlParms.CreateParameter("regId", DbType.String, RegId, true));
            parameters.Add(SqlParms.CreateParameter("medicaidId", DbType.String, MedicaidId, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_SearchMQ", parameters, "ResultCount", SqlDbType.Int, out outValue, 0);
            ds.Tables[0].TableName = "TQ";
            if (!string.IsNullOrEmpty(outValue))
            {
                totalCount = Convert.ToInt32(outValue);
            }

            return ds;
        }

        //GetSearchMQSearch(int logId)
        public static DataSet GetSearchMQMessage(int logId)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
          
            parameters.Add(SqlParms.CreateParameter("logId", DbType.Int32, logId, true));

            DataSet ds = new DataSet();
            ds = DataAccess.ExecuteStoredProcedure("usp_GET_SearchMQ_Message", parameters, "MQ");

            ds.Tables[0].TableName = "MQ";


            return ds;
        }

        public static void UpdateTransactionQueueSIResponse(int transactionQueueId, string responseCode, string responseType, string responseMessage, DateTime modifiedDate, Guid modifiedBy)
        { 
            try
            {
                List<SqlParameter> parameters = new List<SqlParameter>();

                parameters.Add(SqlParms.CreateParameter("TRANSACTION_QUEUE_ID", DbType.Int32, transactionQueueId, true));
                parameters.Add(SqlParms.CreateParameter("SI_RESPONSE_CODE", DbType.String, responseCode, true));
                parameters.Add(SqlParms.CreateParameter("SI_RESPONSE_TYPE", DbType.String, responseType, true));
                parameters.Add(SqlParms.CreateParameter("SI_RESPONSE_MESSAGE", DbType.String, responseMessage, true));

                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.DateTime, modifiedDate, true));
                parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, modifiedBy, true));

                DataAccess.ExecuteStoredProcedure("usp_UpdatePNMErrorTransactionResponse", parameters);
            }
            catch (Exception ex)
            {
                throw CoreException.ThrowException(ex);
            }
        }

        public static DataSet GetRegAddressHospitalNoByRegIdOrMedicaidId(int regId, string medicaidID)
        {
            DataSet ds = new DataSet();

            // create parameters objects and fill with values
            List<SqlParameter> parameters = new List<SqlParameter>();
            if(regId > 0)
            {
                parameters.Add(SqlParms.CreateParameter("REG_ID", DbType.Int32, regId, true));
            }
            if (!string.IsNullOrEmpty(medicaidID))
            {
                parameters.Add(SqlParms.CreateParameter("MED_ID", DbType.String, medicaidID, true));
            }
            ds = DataAccess.ExecuteStoredProcedure("usp_GetRegAddressHospitalNoWithMCPNFacilityNumbers", parameters, "RegAddressHospitalNoResults");
            ds.Tables[0].TableName = "RegAddressHospitalNoResults";
            
            return ds;
        }

        public static void InsertRegAddressHospitalNo(int regId, string facilityNumberType, int regAddressId, DateTime lastModifiedDateTime, string lastModifiedUser)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(SqlParms.CreateParameter("REG_ID", DbType.Int32, regId, false));
            parameters.Add(SqlParms.CreateParameter("REG_ADDRESS_ID", DbType.Int32, regAddressId, false));
            parameters.Add(SqlParms.CreateParameter("Facility_Number_Type", DbType.String, facilityNumberType, false));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_DATE_TIME", DbType.String, lastModifiedDateTime, false));
            parameters.Add(SqlParms.CreateParameter("LAST_MODIFIED_USER", DbType.Guid, lastModifiedUser, false));

            DataAccess.ExecuteStoredProcedure("usp_AddFacilityNumberToRegAddressHospitalNo", parameters);
        }

    }
}
