<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
 
    <PackageReference Include="AWSSDK.S3" Version="4.0.0.6" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.0.6" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.0.4" />
    <PackageReference Include="AWSSDK.SecretsManager.Caching" Version="2.0.0" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Web.Services3" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.0" />
    <PackageReference Include="Polybioz.HtmlRenderer.PdfSharp.Core" Version="1.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.5" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Private.ServiceModel" Version="4.10.3" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.4.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CoreLibraries\AppSettings\AppSettings.csproj" />
    <ProjectReference Include="..\ObjectControllers\ObjectControllers.csproj" />
    <ProjectReference Include="..\ReportingService\ReportingService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AppSettings">
      <HintPath>..\..\CoreLibraries\AppSettings\bin\Release\AppSettings.dll</HintPath>
    </Reference>
    <Reference Include="Common">
      <HintPath>..\..\CoreLibraries\Common\bin\Release\Common.dll</HintPath>
    </Reference>
    <Reference Include="DataAccess">
      <HintPath>..\..\CoreLibraries\DataAccess\bin\Release\DataAccess.dll</HintPath>
    </Reference>
    <Reference Include="Logging">
      <HintPath>..\..\CoreLibraries\Logging\bin\Release\Logging.dll</HintPath>
    </Reference>
    <Reference Include="ObjectControllers">
      <HintPath>..\ObjectControllers\bin\Release\ObjectControllers.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.ApplicationServices">
      <HintPath>bin\System.Web.ApplicationServices.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
