//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Corp.Core.Libraries.AcknowledgmentReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="acknowledgmentSoap", Namespace="http://mes.gov/acknowledgment")]
    public partial class AcknowledgmentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback targetVendorResponseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AcknowledgmentService() {
            this.Url = global::Corp.Core.Libraries.Properties.Settings.Default.Common_AcknowledgmentReference_AcknowledgmentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event targetVendorResponseCompletedEventHandler targetVendorResponseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mes.gov/targetVendorResponse", RequestElementName="TargetVendorResponse", RequestNamespace="http://mes.gov/acknowledgment", ResponseElementName="TargetVendorResponse", ResponseNamespace="http://mes.gov/acknowledgment", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void targetVendorResponse(ref TargetVendorResponseRequestorSystem RequestorSystem, ref string RequestorSystemId, ref TargetVendorResponseTargetSystem TargetSystem, ref string TargetSystemId, ref string SITransactionKey, ref TargetVendorResponseResponseCode ResponseCode, ref string ResponseType, ref string ResponseMessage, ref string TimeStamp, ref string ModuleTransactionId, ref string AdditionalModuleTransactionId) {
            object[] results = this.Invoke("targetVendorResponse", new object[] {
                        RequestorSystem,
                        RequestorSystemId,
                        TargetSystem,
                        TargetSystemId,
                        SITransactionKey,
                        ResponseCode,
                        ResponseType,
                        ResponseMessage,
                        TimeStamp,
                        ModuleTransactionId,
                        AdditionalModuleTransactionId});
            RequestorSystem = ((TargetVendorResponseRequestorSystem)(results[0]));
            RequestorSystemId = ((string)(results[1]));
            TargetSystem = ((TargetVendorResponseTargetSystem)(results[2]));
            TargetSystemId = ((string)(results[3]));
            SITransactionKey = ((string)(results[4]));
            ResponseCode = ((TargetVendorResponseResponseCode)(results[5]));
            ResponseType = ((string)(results[6]));
            ResponseMessage = ((string)(results[7]));
            TimeStamp = ((string)(results[8]));
            ModuleTransactionId = ((string)(results[9]));
            AdditionalModuleTransactionId = ((string)(results[10]));
        }
        
        /// <remarks/>
        public void targetVendorResponseAsync(TargetVendorResponseRequestorSystem RequestorSystem, string RequestorSystemId, TargetVendorResponseTargetSystem TargetSystem, string TargetSystemId, string SITransactionKey, TargetVendorResponseResponseCode ResponseCode, string ResponseType, string ResponseMessage, string TimeStamp, string ModuleTransactionId, string AdditionalModuleTransactionId) {
            this.targetVendorResponseAsync(RequestorSystem, RequestorSystemId, TargetSystem, TargetSystemId, SITransactionKey, ResponseCode, ResponseType, ResponseMessage, TimeStamp, ModuleTransactionId, AdditionalModuleTransactionId, null);
        }
        
        /// <remarks/>
        public void targetVendorResponseAsync(TargetVendorResponseRequestorSystem RequestorSystem, string RequestorSystemId, TargetVendorResponseTargetSystem TargetSystem, string TargetSystemId, string SITransactionKey, TargetVendorResponseResponseCode ResponseCode, string ResponseType, string ResponseMessage, string TimeStamp, string ModuleTransactionId, string AdditionalModuleTransactionId, object userState) {
            if ((this.targetVendorResponseOperationCompleted == null)) {
                this.targetVendorResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OntargetVendorResponseOperationCompleted);
            }
            this.InvokeAsync("targetVendorResponse", new object[] {
                        RequestorSystem,
                        RequestorSystemId,
                        TargetSystem,
                        TargetSystemId,
                        SITransactionKey,
                        ResponseCode,
                        ResponseType,
                        ResponseMessage,
                        TimeStamp,
                        ModuleTransactionId,
                        AdditionalModuleTransactionId}, this.targetVendorResponseOperationCompleted, userState);
        }
        
        private void OntargetVendorResponseOperationCompleted(object arg) {
            if ((this.targetVendorResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.targetVendorResponseCompleted(this, new targetVendorResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/acknowledgment")]
    public enum TargetVendorResponseRequestorSystem {
        
        /// <remarks/>
        PNM,
        
        /// <remarks/>
        PSM,
        
        /// <remarks/>
        PCW,
        
        /// <remarks/>
        MITS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/acknowledgment")]
    public enum TargetVendorResponseTargetSystem {
        
        /// <remarks/>
        PNM,
        
        /// <remarks/>
        PSM,
        
        /// <remarks/>
        PCW,
        
        /// <remarks/>
        MITS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/acknowledgment")]
    public enum TargetVendorResponseResponseCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1000")]
        Item1000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1001")]
        Item1001,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void targetVendorResponseCompletedEventHandler(object sender, targetVendorResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class targetVendorResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal targetVendorResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TargetVendorResponseRequestorSystem RequestorSystem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TargetVendorResponseRequestorSystem)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RequestorSystemId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public TargetVendorResponseTargetSystem TargetSystem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TargetVendorResponseTargetSystem)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string TargetSystemId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string SITransactionKey {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public TargetVendorResponseResponseCode ResponseCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TargetVendorResponseResponseCode)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string ResponseType {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public string TimeStamp {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[8]));
            }
        }
        
        /// <remarks/>
        public string ModuleTransactionId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[9]));
            }
        }
        
        /// <remarks/>
        public string AdditionalModuleTransactionId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[10]));
            }
        }
    }
}

#pragma warning restore 1591