//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMSWebAPI.VendorAckService
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mes.gov/acknowledgment")]
    public partial class VendorAcknowledgmentRequest : System.ComponentModel.INotifyPropertyChanged
    {

        private MessageHeader messageHeaderField;

        private Response[] responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MessageHeader MessageHeader
        {
            get
            {
                return this.messageHeaderField;
            }
            set
            {
                this.messageHeaderField = value;
                this.RaisePropertyChanged("MessageHeader");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response", Order = 1)]
        public Response[] Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mes.gov/acknowledgment")]
    public partial class MessageHeader : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string businessFlowField;

        private string requestorSystemField;

        private string requestorSystemIdField;

        private string requestorTransactionIdField;

        private string targetSystemField;

        private string targetTransactionIdField;

        private string moduleTransactionIdField;

        private string additionalModuleTransactionIdField;

        private string sITransactionKeyField;

        private string timeStampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BusinessFlow
        {
            get
            {
                return this.businessFlowField;
            }
            set
            {
                this.businessFlowField = value;
                this.RaisePropertyChanged("BusinessFlow");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string RequestorSystem
        {
            get
            {
                return this.requestorSystemField;
            }
            set
            {
                this.requestorSystemField = value;
                this.RaisePropertyChanged("RequestorSystem");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string RequestorSystemId
        {
            get
            {
                return this.requestorSystemIdField;
            }
            set
            {
                this.requestorSystemIdField = value;
                this.RaisePropertyChanged("RequestorSystemId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string RequestorTransactionId
        {
            get
            {
                return this.requestorTransactionIdField;
            }
            set
            {
                this.requestorTransactionIdField = value;
                this.RaisePropertyChanged("RequestorTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string TargetSystem
        {
            get
            {
                return this.targetSystemField;
            }
            set
            {
                this.targetSystemField = value;
                this.RaisePropertyChanged("TargetSystem");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string TargetTransactionId
        {
            get
            {
                return this.targetTransactionIdField;
            }
            set
            {
                this.targetTransactionIdField = value;
                this.RaisePropertyChanged("TargetTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string ModuleTransactionId
        {
            get
            {
                return this.moduleTransactionIdField;
            }
            set
            {
                this.moduleTransactionIdField = value;
                this.RaisePropertyChanged("ModuleTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string AdditionalModuleTransactionId
        {
            get
            {
                return this.additionalModuleTransactionIdField;
            }
            set
            {
                this.additionalModuleTransactionIdField = value;
                this.RaisePropertyChanged("AdditionalModuleTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string SITransactionKey
        {
            get
            {
                return this.sITransactionKeyField;
            }
            set
            {
                this.sITransactionKeyField = value;
                this.RaisePropertyChanged("SITransactionKey");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mes.gov/acknowledgment")]
    public partial class VendorAcknowledgmentResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string businessFlowField;

        private string requestorSystemField;

        private string requestorSystemIdField;

        private string requestorTransactionIdField;

        private string targetSystemField;

        private string targetTransactionIdField;

        private string moduleTransactionIdField;

        private string additionalModuleTransactionIdField;

        private string sITransactionKeyField;

        private string timeStampField;

        private VendorAcknowledgmentResponseResponse[] responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BusinessFlow
        {
            get
            {
                return this.businessFlowField;
            }
            set
            {
                this.businessFlowField = value;
                this.RaisePropertyChanged("BusinessFlow");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string RequestorSystem
        {
            get
            {
                return this.requestorSystemField;
            }
            set
            {
                this.requestorSystemField = value;
                this.RaisePropertyChanged("RequestorSystem");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string RequestorSystemId
        {
            get
            {
                return this.requestorSystemIdField;
            }
            set
            {
                this.requestorSystemIdField = value;
                this.RaisePropertyChanged("RequestorSystemId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string RequestorTransactionId
        {
            get
            {
                return this.requestorTransactionIdField;
            }
            set
            {
                this.requestorTransactionIdField = value;
                this.RaisePropertyChanged("RequestorTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string TargetSystem
        {
            get
            {
                return this.targetSystemField;
            }
            set
            {
                this.targetSystemField = value;
                this.RaisePropertyChanged("TargetSystem");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string TargetTransactionId
        {
            get
            {
                return this.targetTransactionIdField;
            }
            set
            {
                this.targetTransactionIdField = value;
                this.RaisePropertyChanged("TargetTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string ModuleTransactionId
        {
            get
            {
                return this.moduleTransactionIdField;
            }
            set
            {
                this.moduleTransactionIdField = value;
                this.RaisePropertyChanged("ModuleTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string AdditionalModuleTransactionId
        {
            get
            {
                return this.additionalModuleTransactionIdField;
            }
            set
            {
                this.additionalModuleTransactionIdField = value;
                this.RaisePropertyChanged("AdditionalModuleTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string SITransactionKey
        {
            get
            {
                return this.sITransactionKeyField;
            }
            set
            {
                this.sITransactionKeyField = value;
                this.RaisePropertyChanged("SITransactionKey");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response", Order = 10)]
        public VendorAcknowledgmentResponseResponse[] Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/acknowledgment")]
    public partial class VendorAcknowledgmentResponseResponse
    {

        private string sequenceNumberField;

        private string responseCodeField;

        private string responseTypeField;

        private string responseMessageField;

        private string responseDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SequenceNumber
        {
            get
            {
                return this.sequenceNumberField;
            }
            set
            {
                this.sequenceNumberField = value;
                this.RaisePropertyChanged("SequenceNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ResponseType
        {
            get
            {
                return this.responseTypeField;
            }
            set
            {
                this.responseTypeField = value;
                this.RaisePropertyChanged("ResponseType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ResponseDetails
        {
            get
            {
                return this.responseDetailsField;
            }
            set
            {
                this.responseDetailsField = value;
                this.RaisePropertyChanged("ResponseDetails");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mes.gov/acknowledgment")]
    public partial class Response :  System.ComponentModel.INotifyPropertyChanged
    {

        private string sequenceNumberField;

        private string responseCodeField;

        private string responseTypeField;

        private string responseMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SequenceNumber
        {
            get
            {
                return this.sequenceNumberField;
            }
            set
            {
                this.sequenceNumberField = value;
                this.RaisePropertyChanged("SequenceNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ResponseType
        {
            get
            {
                return this.responseTypeField;
            }
            set
            {
                this.responseTypeField = value;
                this.RaisePropertyChanged("ResponseType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://mes.gov/acknowledgment", ConfigurationName = "dsad.AcknowledgmentSoapPortType")]
    public interface AcknowledgmentSoapPortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://mes.gov/vendorAcknowledgmentReqRes", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PDMSWebAPI.VendorAckService.VendorAcknowledgmentRequest), Action = "http://mes.gov/vendorAcknowledgmentReqRes", Name = "VendorAcknowledgmentRequest")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VendorAcknowledgmentResponse))]
        PDMSWebAPI.VendorAckService.vendorAcknowledgmentResponse1 vendorAcknowledgment(PDMSWebAPI.VendorAckService.vendorAcknowledgmentRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://mes.gov/vendorAcknowledgmentReqRes", ReplyAction = "*")]
        System.Threading.Tasks.Task<PDMSWebAPI.VendorAckService.vendorAcknowledgmentResponse1> vendorAcknowledgmentAsync(PDMSWebAPI.VendorAckService.vendorAcknowledgmentRequest1 request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "VendorAcknowledgmentRequest", WrapperNamespace = "http://mes.gov/acknowledgment", IsWrapped = true)]
    public partial class vendorAcknowledgmentRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 0)]
        public PDMSWebAPI.VendorAckService.MessageHeader MessageHeader;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("Response")]
        public PDMSWebAPI.VendorAckService.Response[] Response;

        public vendorAcknowledgmentRequest1()
        {
        }

        public vendorAcknowledgmentRequest1(PDMSWebAPI.VendorAckService.MessageHeader MessageHeader, PDMSWebAPI.VendorAckService.Response[] Response)
        {
            this.MessageHeader = MessageHeader;
            this.Response = Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "VendorAcknowledgmentResponse", WrapperNamespace = "http://mes.gov/acknowledgment", IsWrapped = true)]
    public partial class vendorAcknowledgmentResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 0)]
        public string BusinessFlow;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 1)]
        public string RequestorSystem;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 2)]
        public string RequestorSystemId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 3)]
        public string RequestorTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 4)]
        public string TargetSystem;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 5)]
        public string TargetTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 6)]
        public string ModuleTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 7)]
        public string AdditionalModuleTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 8)]
        public string SITransactionKey;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 9)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/acknowledgment", Order = 10)]
        [System.Xml.Serialization.XmlElementAttribute("Response")]
        public PDMSWebAPI.VendorAckService.VendorAcknowledgmentResponseResponse[] Response;

        public vendorAcknowledgmentResponse1()
        {
        }

        public vendorAcknowledgmentResponse1(string BusinessFlow, string RequestorSystem, string RequestorSystemId, string RequestorTransactionId, string TargetSystem, string TargetTransactionId, string ModuleTransactionId, string AdditionalModuleTransactionId, string SITransactionKey, string TimeStamp, PDMSWebAPI.VendorAckService.VendorAcknowledgmentResponseResponse[] Response)
        {
            this.BusinessFlow = BusinessFlow;
            this.RequestorSystem = RequestorSystem;
            this.RequestorSystemId = RequestorSystemId;
            this.RequestorTransactionId = RequestorTransactionId;
            this.TargetSystem = TargetSystem;
            this.TargetTransactionId = TargetTransactionId;
            this.ModuleTransactionId = ModuleTransactionId;
            this.AdditionalModuleTransactionId = AdditionalModuleTransactionId;
            this.SITransactionKey = SITransactionKey;
            this.TimeStamp = TimeStamp;
            this.Response = Response;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AcknowledgmentSoapPortTypeChannel : PDMSWebAPI.VendorAckService.AcknowledgmentSoapPortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcknowledgmentSoapPortTypeClient : System.ServiceModel.ClientBase<PDMSWebAPI.VendorAckService.AcknowledgmentSoapPortType>, PDMSWebAPI.VendorAckService.AcknowledgmentSoapPortType
    {

        public AcknowledgmentSoapPortTypeClient()
        {
        }

        public AcknowledgmentSoapPortTypeClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public AcknowledgmentSoapPortTypeClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public AcknowledgmentSoapPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public AcknowledgmentSoapPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public PDMSWebAPI.VendorAckService.vendorAcknowledgmentResponse1 vendorAcknowledgment(PDMSWebAPI.VendorAckService.vendorAcknowledgmentRequest1 request)
        {
            return base.Channel.vendorAcknowledgment(request);
        }

        public System.Threading.Tasks.Task<PDMSWebAPI.VendorAckService.vendorAcknowledgmentResponse1> vendorAcknowledgmentAsync(PDMSWebAPI.VendorAckService.vendorAcknowledgmentRequest1 request)
        {
            return base.Channel.vendorAcknowledgmentAsync(request);
        }
    }
}
