//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Corp.Core.Libraries.LTC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="costReportSoap", Namespace="http://mes.gov/costreports")]
    public partial class costReportsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback submitCostReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitCostSettlementReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback costReportSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback costReportDueDateSearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public costReportsService() {
            this.Url = global::Corp.Core.Libraries.Properties.Settings.Default.Common_LTC_costReportsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event submitCostReportCompletedEventHandler submitCostReportCompleted;
        
        /// <remarks/>
        public event submitCostSettlementReportCompletedEventHandler submitCostSettlementReportCompleted;
        
        /// <remarks/>
        public event costReportSearchCompletedEventHandler costReportSearchCompleted;
        
        /// <remarks/>
        public event costReportDueDateSearchCompletedEventHandler costReportDueDateSearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mes.gov/submitCostReport", RequestElementName="SubmitCostReportRequest", RequestNamespace="http://mes.gov/costreports", ResponseElementName="SubmitCostReportResponse", ResponseNamespace="http://mes.gov/costreports", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePayload")]
        public cSubmitCostReportResponse submitCostReport(MessageHeader MessageHeader, cSubmitCostReportRequest Payload) {
            object[] results = this.Invoke("submitCostReport", new object[] {
                        MessageHeader,
                        Payload});
            return ((cSubmitCostReportResponse)(results[0]));
        }
        
        /// <remarks/>
        public void submitCostReportAsync(MessageHeader MessageHeader, cSubmitCostReportRequest Payload) {
            this.submitCostReportAsync(MessageHeader, Payload, null);
        }
        
        /// <remarks/>
        public void submitCostReportAsync(MessageHeader MessageHeader, cSubmitCostReportRequest Payload, object userState) {
            if ((this.submitCostReportOperationCompleted == null)) {
                this.submitCostReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitCostReportOperationCompleted);
            }
            this.InvokeAsync("submitCostReport", new object[] {
                        MessageHeader,
                        Payload}, this.submitCostReportOperationCompleted, userState);
        }
        
        private void OnsubmitCostReportOperationCompleted(object arg) {
            if ((this.submitCostReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitCostReportCompleted(this, new submitCostReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mes.gov/submitCostSettlementReport", RequestElementName="SubmitCostSettlementReportRequest", RequestNamespace="http://mes.gov/costreports", ResponseElementName="SubmitCostSettlementReportResponse", ResponseNamespace="http://mes.gov/costreports", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePayload")]
        public cSubmitCostSettlementReportResponse submitCostSettlementReport(MessageHeader MessageHeader, cSubmitCostSettlementReportRequest Payload) {
            object[] results = this.Invoke("submitCostSettlementReport", new object[] {
                        MessageHeader,
                        Payload});
            return ((cSubmitCostSettlementReportResponse)(results[0]));
        }
        
        /// <remarks/>
        public void submitCostSettlementReportAsync(MessageHeader MessageHeader, cSubmitCostSettlementReportRequest Payload) {
            this.submitCostSettlementReportAsync(MessageHeader, Payload, null);
        }
        
        /// <remarks/>
        public void submitCostSettlementReportAsync(MessageHeader MessageHeader, cSubmitCostSettlementReportRequest Payload, object userState) {
            if ((this.submitCostSettlementReportOperationCompleted == null)) {
                this.submitCostSettlementReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitCostSettlementReportOperationCompleted);
            }
            this.InvokeAsync("submitCostSettlementReport", new object[] {
                        MessageHeader,
                        Payload}, this.submitCostSettlementReportOperationCompleted, userState);
        }
        
        private void OnsubmitCostSettlementReportOperationCompleted(object arg) {
            if ((this.submitCostSettlementReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitCostSettlementReportCompleted(this, new submitCostSettlementReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mes.gov/costReportSearch", RequestElementName="CostReportSearchRequest", RequestNamespace="http://mes.gov/costreports", ResponseElementName="CostReportSearchResponse", ResponseNamespace="http://mes.gov/costreports", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePayload")]
        public cCostReportSearchResponse[] costReportSearch(MessageHeader MessageHeader, cCostReportSearchRequest Payload) {
            object[] results = this.Invoke("costReportSearch", new object[] {
                        MessageHeader,
                        Payload});
            return ((cCostReportSearchResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void costReportSearchAsync(MessageHeader MessageHeader, cCostReportSearchRequest Payload) {
            this.costReportSearchAsync(MessageHeader, Payload, null);
        }
        
        /// <remarks/>
        public void costReportSearchAsync(MessageHeader MessageHeader, cCostReportSearchRequest Payload, object userState) {
            if ((this.costReportSearchOperationCompleted == null)) {
                this.costReportSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OncostReportSearchOperationCompleted);
            }
            this.InvokeAsync("costReportSearch", new object[] {
                        MessageHeader,
                        Payload}, this.costReportSearchOperationCompleted, userState);
        }
        
        private void OncostReportSearchOperationCompleted(object arg) {
            if ((this.costReportSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.costReportSearchCompleted(this, new costReportSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mes.gov/CostReportDueDateSearch", RequestElementName="CostReportDueDateSearchRequest", RequestNamespace="http://mes.gov/costreports", ResponseElementName="CostReportDueDateSearchResponse", ResponseNamespace="http://mes.gov/costreports", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePayload")]
        public cCostReportDueDateSearchResponse costReportDueDateSearch(MessageHeader MessageHeader, cCostReportDueDateSearchRequest Payload) {
            object[] results = this.Invoke("costReportDueDateSearch", new object[] {
                        MessageHeader,
                        Payload});
            return ((cCostReportDueDateSearchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void costReportDueDateSearchAsync(MessageHeader MessageHeader, cCostReportDueDateSearchRequest Payload) {
            this.costReportDueDateSearchAsync(MessageHeader, Payload, null);
        }
        
        /// <remarks/>
        public void costReportDueDateSearchAsync(MessageHeader MessageHeader, cCostReportDueDateSearchRequest Payload, object userState) {
            if ((this.costReportDueDateSearchOperationCompleted == null)) {
                this.costReportDueDateSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OncostReportDueDateSearchOperationCompleted);
            }
            this.InvokeAsync("costReportDueDateSearch", new object[] {
                        MessageHeader,
                        Payload}, this.costReportDueDateSearchOperationCompleted, userState);
        }
        
        private void OncostReportDueDateSearchOperationCompleted(object arg) {
            if ((this.costReportDueDateSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.costReportDueDateSearchCompleted(this, new costReportDueDateSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/costreports")]
    public partial class MessageHeader {
        
        private MessageHeaderBusinessFlow businessFlowField;
        
        private string stateCodeField;
        
        private string requestorSystemField;
        
        private string subscriberSystemField;
        
        private string moduleTransactionIdField;
        
        private string additionalModuleTransactionIdField;
        
        private string requestTimestampField;
        
        private string sITransactionKeyField;
        
        public MessageHeader() {
            this.stateCodeField = "OH";
            this.requestorSystemField = "PNM";
        }
        
        /// <remarks/>
        public MessageHeaderBusinessFlow BusinessFlow {
            get {
                return this.businessFlowField;
            }
            set {
                this.businessFlowField = value;
            }
        }
        
        /// <remarks/>
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestorSystem {
            get {
                return this.requestorSystemField;
            }
            set {
                this.requestorSystemField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberSystem {
            get {
                return this.subscriberSystemField;
            }
            set {
                this.subscriberSystemField = value;
            }
        }
        
        /// <remarks/>
        public string ModuleTransactionId {
            get {
                return this.moduleTransactionIdField;
            }
            set {
                this.moduleTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalModuleTransactionId {
            get {
                return this.additionalModuleTransactionIdField;
            }
            set {
                this.additionalModuleTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTimestamp {
            get {
                return this.requestTimestampField;
            }
            set {
                this.requestTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string SITransactionKey {
            get {
                return this.sITransactionKeyField;
            }
            set {
                this.sITransactionKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/costreports")]
    public enum MessageHeaderBusinessFlow {
        
        /// <remarks/>
        SubmitCostReport,
        
        /// <remarks/>
        SubmitCostSettlementReport,
        
        /// <remarks/>
        CostReportSearch,
        
        /// <remarks/>
        CostReportDueDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cCostReportDueDateSearchResponse {
        
        private string idProviderField;
        
        private string currentCostReportEffectiveDateField;
        
        private string currentCostReportEndDateField;
        
        private string currentCostReportDueDateField;
        
        private string previousCostReportEffectiveDateField;
        
        private string previousCostReportEndDateField;
        
        private string previousCostReportDueDateField;
        
        private cSIResponse responseField;
        
        /// <remarks/>
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentCostReportEffectiveDate {
            get {
                return this.currentCostReportEffectiveDateField;
            }
            set {
                this.currentCostReportEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentCostReportEndDate {
            get {
                return this.currentCostReportEndDateField;
            }
            set {
                this.currentCostReportEndDateField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentCostReportDueDate {
            get {
                return this.currentCostReportDueDateField;
            }
            set {
                this.currentCostReportDueDateField = value;
            }
        }
        
        /// <remarks/>
        public string PreviousCostReportEffectiveDate {
            get {
                return this.previousCostReportEffectiveDateField;
            }
            set {
                this.previousCostReportEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string PreviousCostReportEndDate {
            get {
                return this.previousCostReportEndDateField;
            }
            set {
                this.previousCostReportEndDateField = value;
            }
        }
        
        /// <remarks/>
        public string PreviousCostReportDueDate {
            get {
                return this.previousCostReportDueDateField;
            }
            set {
                this.previousCostReportDueDateField = value;
            }
        }
        
        /// <remarks/>
        public cSIResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cSIResponse {
        
        private string sITransactionKeyField;
        
        private string responseTypeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public string SITransactionKey {
            get {
                return this.sITransactionKeyField;
            }
            set {
                this.sITransactionKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cCostReportDueDateSearchRequest {
        
        private string idProviderField;
        
        /// <remarks/>
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cCostReportSearchResponse {
        
        private string idProviderField;
        
        private string sITransactionKeyField;
        
        private string providerTypeField;
        
        private string submissionDateField;
        
        private string submissionStatusField;
        
        private string mITSTrackingNumberField;
        
        private string costReportTypeField;
        
        private string crDocumentNumberField;
        
        private string cRFromDateField;
        
        private string cRToDateField;
        
        private string cRFiscalYearField;
        
        private string settleTypeField;
        
        private string settlementAmtField;
        
        private string preparerFNField;
        
        private string preparerLNField;
        
        private string preparerIDField;
        
        private string preparerPhoneField;
        
        private string preparerEmailIDField;
        
        private string submitterIDField;
        
        private string submitterPhoneField;
        
        private string submitterEmailIDField;
        
        private string submitterFNField;
        
        private string submitterLNField;
        
        private string reviewerNameField;
        
        private string disapprovalReasonField;
        
        private cCostReportSearchResponseResponses[] responsesField;
        
        private cSIResponse responseField;
        
        /// <remarks/>
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
            }
        }
        
        /// <remarks/>
        public string SITransactionKey {
            get {
                return this.sITransactionKeyField;
            }
            set {
                this.sITransactionKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ProviderType {
            get {
                return this.providerTypeField;
            }
            set {
                this.providerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SubmissionDate {
            get {
                return this.submissionDateField;
            }
            set {
                this.submissionDateField = value;
            }
        }
        
        /// <remarks/>
        public string SubmissionStatus {
            get {
                return this.submissionStatusField;
            }
            set {
                this.submissionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string MITSTrackingNumber {
            get {
                return this.mITSTrackingNumberField;
            }
            set {
                this.mITSTrackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CostReportType {
            get {
                return this.costReportTypeField;
            }
            set {
                this.costReportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CrDocumentNumber {
            get {
                return this.crDocumentNumberField;
            }
            set {
                this.crDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CRFromDate {
            get {
                return this.cRFromDateField;
            }
            set {
                this.cRFromDateField = value;
            }
        }
        
        /// <remarks/>
        public string CRToDate {
            get {
                return this.cRToDateField;
            }
            set {
                this.cRToDateField = value;
            }
        }
        
        /// <remarks/>
        public string CRFiscalYear {
            get {
                return this.cRFiscalYearField;
            }
            set {
                this.cRFiscalYearField = value;
            }
        }
        
        /// <remarks/>
        public string SettleType {
            get {
                return this.settleTypeField;
            }
            set {
                this.settleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementAmt {
            get {
                return this.settlementAmtField;
            }
            set {
                this.settlementAmtField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerFN {
            get {
                return this.preparerFNField;
            }
            set {
                this.preparerFNField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerLN {
            get {
                return this.preparerLNField;
            }
            set {
                this.preparerLNField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerID {
            get {
                return this.preparerIDField;
            }
            set {
                this.preparerIDField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerPhone {
            get {
                return this.preparerPhoneField;
            }
            set {
                this.preparerPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerEmailID {
            get {
                return this.preparerEmailIDField;
            }
            set {
                this.preparerEmailIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterID {
            get {
                return this.submitterIDField;
            }
            set {
                this.submitterIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterPhone {
            get {
                return this.submitterPhoneField;
            }
            set {
                this.submitterPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterEmailID {
            get {
                return this.submitterEmailIDField;
            }
            set {
                this.submitterEmailIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterFN {
            get {
                return this.submitterFNField;
            }
            set {
                this.submitterFNField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterLN {
            get {
                return this.submitterLNField;
            }
            set {
                this.submitterLNField = value;
            }
        }
        
        /// <remarks/>
        public string ReviewerName {
            get {
                return this.reviewerNameField;
            }
            set {
                this.reviewerNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisapprovalReason {
            get {
                return this.disapprovalReasonField;
            }
            set {
                this.disapprovalReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Responses")]
        public cCostReportSearchResponseResponses[] Responses {
            get {
                return this.responsesField;
            }
            set {
                this.responsesField = value;
            }
        }
        
        /// <remarks/>
        public cSIResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/costreports")]
    public partial class cCostReportSearchResponseResponses {
        
        private string responseTypeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public string ResponseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cCostReportSearchRequest {
        
        private cCostReportSearchRequestIdProvider[] idProviderField;
        
        private cCostReportSearchRequestCostreportdetail costreportdetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdProvider")]
        public cCostReportSearchRequestIdProvider[] IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
            }
        }
        
        /// <remarks/>
        public cCostReportSearchRequestCostreportdetail Costreportdetail {
            get {
                return this.costreportdetailField;
            }
            set {
                this.costreportdetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/costreports")]
    public partial class cCostReportSearchRequestIdProvider {
        
        private string idProviderField;
        
        /// <remarks/>
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/costreports")]
    public partial class cCostReportSearchRequestCostreportdetail {
        
        private string providerTypeField;
        
        private string preparerIDField;
        
        private string submitterIDField;
        
        private string submissionDateField;
        
        private string submissionStatusField;
        
        private string cRFiscalYearField;
        
        private string mITSTrackingNumberField;
        
        private string recordsToReturnField;
        
        private string costReportTypeField;
        
        private string cRFromDateField;
        
        private string cRtoDateField;
        
        private string settlementTypeField;
        
        private string settlementAmtField;
        
        private string crDocumentNumberField;
        
        /// <remarks/>
        public string ProviderType {
            get {
                return this.providerTypeField;
            }
            set {
                this.providerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerID {
            get {
                return this.preparerIDField;
            }
            set {
                this.preparerIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterID {
            get {
                return this.submitterIDField;
            }
            set {
                this.submitterIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubmissionDate {
            get {
                return this.submissionDateField;
            }
            set {
                this.submissionDateField = value;
            }
        }
        
        /// <remarks/>
        public string SubmissionStatus {
            get {
                return this.submissionStatusField;
            }
            set {
                this.submissionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CRFiscalYear {
            get {
                return this.cRFiscalYearField;
            }
            set {
                this.cRFiscalYearField = value;
            }
        }
        
        /// <remarks/>
        public string MITSTrackingNumber {
            get {
                return this.mITSTrackingNumberField;
            }
            set {
                this.mITSTrackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RecordsToReturn {
            get {
                return this.recordsToReturnField;
            }
            set {
                this.recordsToReturnField = value;
            }
        }
        
        /// <remarks/>
        public string CostReportType {
            get {
                return this.costReportTypeField;
            }
            set {
                this.costReportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CRFromDate {
            get {
                return this.cRFromDateField;
            }
            set {
                this.cRFromDateField = value;
            }
        }
        
        /// <remarks/>
        public string CRtoDate {
            get {
                return this.cRtoDateField;
            }
            set {
                this.cRtoDateField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementType {
            get {
                return this.settlementTypeField;
            }
            set {
                this.settlementTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementAmt {
            get {
                return this.settlementAmtField;
            }
            set {
                this.settlementAmtField = value;
            }
        }
        
        /// <remarks/>
        public string CrDocumentNumber {
            get {
                return this.crDocumentNumberField;
            }
            set {
                this.crDocumentNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cSubmitCostSettlementReportResponse {
        
        private cSIResponse responseField;
        
        private cAttachmentData[] attachmentDataField;
        
        /// <remarks/>
        public cSIResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentData")]
        public cAttachmentData[] AttachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cAttachmentData {
        
        private string attachmentIDField;
        
        private string attachmentTypeField;
        
        /// <remarks/>
        public string AttachmentID {
            get {
                return this.attachmentIDField;
            }
            set {
                this.attachmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string AttachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cSubmitCostSettlementReportRequest {
        
        private string idProviderField;
        
        private string costReportTypeField;
        
        private string costReportFromDateField;
        
        private string costReportToDateField;
        
        private string costReportFiscalYearField;
        
        private string submissionDateField;
        
        private cSubmitCostSettlementReportRequestAttachmentInfo attachmentInfoField;
        
        /// <remarks/>
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
            }
        }
        
        /// <remarks/>
        public string CostReportType {
            get {
                return this.costReportTypeField;
            }
            set {
                this.costReportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CostReportFromDate {
            get {
                return this.costReportFromDateField;
            }
            set {
                this.costReportFromDateField = value;
            }
        }
        
        /// <remarks/>
        public string CostReportToDate {
            get {
                return this.costReportToDateField;
            }
            set {
                this.costReportToDateField = value;
            }
        }
        
        /// <remarks/>
        public string CostReportFiscalYear {
            get {
                return this.costReportFiscalYearField;
            }
            set {
                this.costReportFiscalYearField = value;
            }
        }
        
        /// <remarks/>
        public string SubmissionDate {
            get {
                return this.submissionDateField;
            }
            set {
                this.submissionDateField = value;
            }
        }
        
        /// <remarks/>
        public cSubmitCostSettlementReportRequestAttachmentInfo AttachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/costreports")]
    public partial class cSubmitCostSettlementReportRequestAttachmentInfo {
        
        private string documentIDField;
        
        private string documentTypeField;
        
        private string documentNameField;
        
        private string firstAccessDateField;
        
        private string readIndicatorField;
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstAccessDate {
            get {
                return this.firstAccessDateField;
            }
            set {
                this.firstAccessDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReadIndicator {
            get {
                return this.readIndicatorField;
            }
            set {
                this.readIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cSubmitCostReportResponse {
        
        private string mITSTrackingNumberField;
        
        private cSIResponse responseField;
        
        private cAttachmentData[] attachmentDataField;
        
        /// <remarks/>
        public string MITSTrackingNumber {
            get {
                return this.mITSTrackingNumberField;
            }
            set {
                this.mITSTrackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public cSIResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentData")]
        public cAttachmentData[] AttachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.gov/costreports")]
    public partial class cSubmitCostReportRequest {
        
        private string idProviderField;
        
        private string costReportTypeField;
        
        private string cRFromDateField;
        
        private string cRToDateField;
        
        private string cRFiscalYearField;
        
        private string settlementAmtField;
        
        private string settleTypeCodeField;
        
        private string submissionStatusField;
        
        private string submissionDateField;
        
        private string preparerFNField;
        
        private string preparerLNField;
        
        private string preparerIDField;
        
        private string preparerPhoneField;
        
        private string preparerEmailIDField;
        
        private string submitterFNField;
        
        private string submitterLNField;
        
        private string submitterIDField;
        
        private string submitterPhoneField;
        
        private string submitterEmailIDField;
        
        private string mITSTrackingNumberField;
        
        private cSubmitCostReportRequestAttachmentInfo[] attachmentInfoField;
        
        /// <remarks/>
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
            }
        }
        
        /// <remarks/>
        public string CostReportType {
            get {
                return this.costReportTypeField;
            }
            set {
                this.costReportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CRFromDate {
            get {
                return this.cRFromDateField;
            }
            set {
                this.cRFromDateField = value;
            }
        }
        
        /// <remarks/>
        public string CRToDate {
            get {
                return this.cRToDateField;
            }
            set {
                this.cRToDateField = value;
            }
        }
        
        /// <remarks/>
        public string CRFiscalYear {
            get {
                return this.cRFiscalYearField;
            }
            set {
                this.cRFiscalYearField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementAmt {
            get {
                return this.settlementAmtField;
            }
            set {
                this.settlementAmtField = value;
            }
        }
        
        /// <remarks/>
        public string SettleTypeCode {
            get {
                return this.settleTypeCodeField;
            }
            set {
                this.settleTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SubmissionStatus {
            get {
                return this.submissionStatusField;
            }
            set {
                this.submissionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SubmissionDate {
            get {
                return this.submissionDateField;
            }
            set {
                this.submissionDateField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerFN {
            get {
                return this.preparerFNField;
            }
            set {
                this.preparerFNField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerLN {
            get {
                return this.preparerLNField;
            }
            set {
                this.preparerLNField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerID {
            get {
                return this.preparerIDField;
            }
            set {
                this.preparerIDField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerPhone {
            get {
                return this.preparerPhoneField;
            }
            set {
                this.preparerPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string PreparerEmailID {
            get {
                return this.preparerEmailIDField;
            }
            set {
                this.preparerEmailIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterFN {
            get {
                return this.submitterFNField;
            }
            set {
                this.submitterFNField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterLN {
            get {
                return this.submitterLNField;
            }
            set {
                this.submitterLNField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterID {
            get {
                return this.submitterIDField;
            }
            set {
                this.submitterIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterPhone {
            get {
                return this.submitterPhoneField;
            }
            set {
                this.submitterPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitterEmailID {
            get {
                return this.submitterEmailIDField;
            }
            set {
                this.submitterEmailIDField = value;
            }
        }
        
        /// <remarks/>
        public string MITSTrackingNumber {
            get {
                return this.mITSTrackingNumberField;
            }
            set {
                this.mITSTrackingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentInfo")]
        public cSubmitCostReportRequestAttachmentInfo[] AttachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mes.gov/costreports")]
    public partial class cSubmitCostReportRequestAttachmentInfo {
        
        private string documentIDField;
        
        private string documentTypeField;
        
        private string documentNameField;
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void submitCostReportCompletedEventHandler(object sender, submitCostReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitCostReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitCostReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cSubmitCostReportResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cSubmitCostReportResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void submitCostSettlementReportCompletedEventHandler(object sender, submitCostSettlementReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitCostSettlementReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitCostSettlementReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cSubmitCostSettlementReportResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cSubmitCostSettlementReportResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void costReportSearchCompletedEventHandler(object sender, costReportSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class costReportSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal costReportSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cCostReportSearchResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cCostReportSearchResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void costReportDueDateSearchCompletedEventHandler(object sender, costReportDueDateSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class costReportDueDateSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal costReportDueDateSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cCostReportDueDateSearchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cCostReportDueDateSearchResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591