/****** Object:  StoredProcedure [dbo].[DCConv_Stage_PTAXIDTB]    Script Date: 2/1/2017  ******/

BEGIN TRY
	BEGIN TRANSACTION;		

	IF object_id('[dbo].[MED_SANCTIONS]','U') is not null
		DROP TABLE [dbo].[MED_SANCTIONS]

	CREATE TABLE [dbo].[MED_SANCTIONS]
	(
		LASTNAME  VARCHAR(20), 
		FIRSTNAME  VARCHAR(15), 
		MIDNAME  VARCHAR(15), 
		SUFFIX  VARCHAR(10), 
		BUSNAME  VARCHAR(30), 
		GENERAL  VARCHAR(20), 
		SPECIALTY  VARCHAR(20), 
		UPIN  VARCHAR(6), 
		DOB  VARCHAR(8), 
		SSN  VARCHAR(9), 
		ADDRESS  VARCHAR(30), 
		CITY  VARCHAR(20), 
		STATE  VARCHAR(2), 
		ZIP  VARCHAR(9), 
		COUNTRY  VARCHAR(21), 
		SANCTYPE  VARCHAR(9), 
		SANCDATE  VARCHAR(8), 
		REINDATE  VARCHAR(8), 
		DATEOFDEAT  VARCHAR(8), 
		OSCARNUMBE  VARCHAR(10), 
		NSCNUMBER  VARCHAR(10), 
		EINNUMBER  VARCHAR(9), 
		INTERMEDIA  VARCHAR(8), 
		CARRIERNUM  VARCHAR(6), 
		MEDASSIGNE  VARCHAR(9), 
		RECORDTYPE  VARCHAR(4), 
		NPI  VARCHAR(10), 
		FILLER  VARCHAR(6) 
	)

	IF object_id('[dbo].[MED_REINSTATEMENTS]','U') is not null
		DROP TABLE [dbo].[MED_REINSTATEMENTS]

	CREATE TABLE [dbo].[MED_REINSTATEMENTS]
	(
		LASTNAME  VARCHAR(20), 
		FIRSTNAME  VARCHAR(15), 
		MIDNAME  VARCHAR(15), 
		SUFFIX  VARCHAR(10), 
		BUSNAME  VARCHAR(30), 
		GENERAL  VARCHAR(20), 
		SPECIALTY  VARCHAR(20), 
		UPIN  VARCHAR(6), 
		DOB  VARCHAR(8), 
		SSN  VARCHAR(9), 
		ADDRESS  VARCHAR(30), 
		CITY  VARCHAR(20), 
		STATE  VARCHAR(2), 
		ZIP  VARCHAR(9), 
		COUNTRY  VARCHAR(21), 
		SANCTYPE  VARCHAR(9), 
		SANCDATE  VARCHAR(8), 
		REINDATE  VARCHAR(8), 
		DATEOFDEAT  VARCHAR(8), 
		OSCARNUMBE  VARCHAR(10), 
		NSCNUMBER  VARCHAR(10), 
		EINNUMBER  VARCHAR(9), 
		INTERMEDIA  VARCHAR(8), 
		CARRIERNUM  VARCHAR(6), 
		MEDASSIGNE  VARCHAR(9), 
		RECORDTYPE  VARCHAR(4), 
		NPI  VARCHAR(10), 
		FILLER  VARCHAR(6)
	)

	IF object_id('[dbo].[MED_WAIVERS]','U') is not null
		DROP TABLE [dbo].[MED_WAIVERS]

	CREATE TABLE [dbo].[MED_WAIVERS]
	(
		LASTNAME  VARCHAR(20), 
		FIRSTNAME  VARCHAR(15), 
		MIDNAME  VARCHAR(15), 
		SUFFIX  VARCHAR(10), 
		BUSNAME  VARCHAR(30), 
		DOB  VARCHAR(10), 
		SSN_EIN  VARCHAR(9), 
		NPI  VARCHAR(10), 
		MEDASSIGNEDID  VARCHAR(9), 
		WAIVEREFFDT  VARCHAR(10), 
		WAIVERENDDT  VARCHAR(10), 
		WAIVERNOTES  VARCHAR(2000), 
	)

	BULK INSERT [dbo].[MED_SANCTIONS] 
	FROM  'C:\MED_Conversion\CUMULATIVE_MED_SANCTIONS.TXT' 
	WITH (FORMATFILE = 'C:\MED_Conversion\SanctionAndReinstatementImportFormat.xml');

	BULK INSERT [dbo].[MED_REINSTATEMENTS] 
	FROM  'C:\MED_Conversion\CUMULATIVE_MED_REINSTATEMENTS.TXT' 
	WITH (FORMATFILE = 'C:\MED_Conversion\SanctionAndReinstatementImportFormat.xml');

	BULK INSERT [dbo].[MED_WAIVERS] 
	FROM  'C:\MED_Conversion\MED_WAIVERS.TXT' 
	WITH (FORMATFILE = 'C:\MED_Conversion\WaiverImportFormat.xml');

	COMMIT TRANSACTION;
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION;
	DECLARE @ErrorMessage NVARCHAR(4000);
	DECLARE @ErrorLine int;
	DECLARE @ErrorSeverity INT;
	DECLARE @ErrorState INT;
	DECLARE @ErrorNumber int;
	DECLARE @ErrorProcedure varchar(128);

	SELECT 
		@ErrorMessage = ERROR_MESSAGE(),
		@ErrorLine = ERROR_LINE(),
		@ErrorSeverity = ERROR_SEVERITY(),
		@ErrorState = ERROR_STATE(),
		@ErrorNumber = ERROR_NUMBER(),
		@ErrorProcedure = ERROR_PROCEDURE();

	-- this will be a fatal error
	RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH

