//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://mes.gov/incidentmanagement", ClrNamespace = "mes.gov.incidentmanagement")]


namespace PDMSWebAPI.IncidentManagement
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string faultcodeField;

        private string faultstringField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string faultcode
        {
            get
            {
                return this.faultcodeField;
            }
            set
            {
                this.faultcodeField = value;
                this.RaisePropertyChanged("faultcode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string faultstring
        {
            get
            {
                return this.faultstringField;
            }
            set
            {
                this.faultstringField = value;
                this.RaisePropertyChanged("faultstring");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mes.gov/incidentmanagement")]
    public partial class UpdateProviderIncidentStatusInfo : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string medicaidProviderIDField;

        private string providerNameField;

        private object providerStatusField;

        private string pAOMailedDateField;

        private object pAIUnclaimedField;

        private string hearingRequestedDateField;

        private string hearingRequestDueDateField;

        private string settlementReachedDateField;

        private string aODateIssuedField;

        private string iMSAssociateIDField;

        private string iMSCaseNumberField;

        private string pNMNODIDField;

        private object actionByDepartmentField;

        private string dateNODIssuedField;

        private string planOfCorrectionDueDateField;

        private string planOfCorrectionReceivedDateField;

        private string planOfCorrectionAcceptedDateField;

        private string revisedPlanOfCorrectionDateField;

        private string revisedPlanOfCorrectionDueDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MedicaidProviderID
        {
            get
            {
                return this.medicaidProviderIDField;
            }
            set
            {
                this.medicaidProviderIDField = value;
                this.RaisePropertyChanged("MedicaidProviderID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ProviderName
        {
            get
            {
                return this.providerNameField;
            }
            set
            {
                this.providerNameField = value;
                this.RaisePropertyChanged("ProviderName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public object ProviderStatus
        {
            get
            {
                return this.providerStatusField;
            }
            set
            {
                this.providerStatusField = value;
                this.RaisePropertyChanged("ProviderStatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string PAOMailedDate
        {
            get
            {
                return this.pAOMailedDateField;
            }
            set
            {
                this.pAOMailedDateField = value;
                this.RaisePropertyChanged("PAOMailedDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public object PAIUnclaimed
        {
            get
            {
                return this.pAIUnclaimedField;
            }
            set
            {
                this.pAIUnclaimedField = value;
                this.RaisePropertyChanged("PAIUnclaimed");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string HearingRequestedDate
        {
            get
            {
                return this.hearingRequestedDateField;
            }
            set
            {
                this.hearingRequestedDateField = value;
                this.RaisePropertyChanged("HearingRequestedDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string HearingRequestDueDate
        {
            get
            {
                return this.hearingRequestDueDateField;
            }
            set
            {
                this.hearingRequestDueDateField = value;
                this.RaisePropertyChanged("HearingRequestDueDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string SettlementReachedDate
        {
            get
            {
                return this.settlementReachedDateField;
            }
            set
            {
                this.settlementReachedDateField = value;
                this.RaisePropertyChanged("SettlementReachedDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string AODateIssued
        {
            get
            {
                return this.aODateIssuedField;
            }
            set
            {
                this.aODateIssuedField = value;
                this.RaisePropertyChanged("AODateIssued");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string IMSAssociateID
        {
            get
            {
                return this.iMSAssociateIDField;
            }
            set
            {
                this.iMSAssociateIDField = value;
                this.RaisePropertyChanged("IMSAssociateID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string IMSCaseNumber
        {
            get
            {
                return this.iMSCaseNumberField;
            }
            set
            {
                this.iMSCaseNumberField = value;
                this.RaisePropertyChanged("IMSCaseNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string PNMNODID
        {
            get
            {
                return this.pNMNODIDField;
            }
            set
            {
                this.pNMNODIDField = value;
                this.RaisePropertyChanged("PNMNODID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public object ActionByDepartment
        {
            get
            {
                return this.actionByDepartmentField;
            }
            set
            {
                this.actionByDepartmentField = value;
                this.RaisePropertyChanged("ActionByDepartment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string DateNODIssued
        {
            get
            {
                return this.dateNODIssuedField;
            }
            set
            {
                this.dateNODIssuedField = value;
                this.RaisePropertyChanged("DateNODIssued");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string PlanOfCorrectionDueDate
        {
            get
            {
                return this.planOfCorrectionDueDateField;
            }
            set
            {
                this.planOfCorrectionDueDateField = value;
                this.RaisePropertyChanged("PlanOfCorrectionDueDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string PlanOfCorrectionReceivedDate
        {
            get
            {
                return this.planOfCorrectionReceivedDateField;
            }
            set
            {
                this.planOfCorrectionReceivedDateField = value;
                this.RaisePropertyChanged("PlanOfCorrectionReceivedDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string PlanOfCorrectionAcceptedDate
        {
            get
            {
                return this.planOfCorrectionAcceptedDateField;
            }
            set
            {
                this.planOfCorrectionAcceptedDateField = value;
                this.RaisePropertyChanged("PlanOfCorrectionAcceptedDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string RevisedPlanOfCorrectionDate
        {
            get
            {
                return this.revisedPlanOfCorrectionDateField;
            }
            set
            {
                this.revisedPlanOfCorrectionDateField = value;
                this.RaisePropertyChanged("RevisedPlanOfCorrectionDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string RevisedPlanOfCorrectionDueDate
        {
            get
            {
                return this.revisedPlanOfCorrectionDueDateField;
            }
            set
            {
                this.revisedPlanOfCorrectionDueDateField = value;
                this.RaisePropertyChanged("RevisedPlanOfCorrectionDueDate");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mes.gov/incidentmanagement")]
    public partial class SendProviderIncidentRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string medicaidProviderIDField;

        private string providerNameField;

        private string iMSCaseNumberField;

        private string caseSubmissionDateField;

        private string nODReferralDateField;

        private string reasonForNODField;

        private string referralSentByField;

        private SendProviderIncidentRequestIncidentDetails[] incidentDetailsField;

        /// <remarks/>
        [DataMember(IsRequired = true)]
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MedicaidProviderID
        {
            get
            {
                return this.medicaidProviderIDField;
            }
            set
            {
                this.medicaidProviderIDField = value;
                this.RaisePropertyChanged("MedicaidProviderID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ProviderName
        {
            get
            {
                return this.providerNameField;
            }
            set
            {
                this.providerNameField = value;
                this.RaisePropertyChanged("ProviderName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string IMSCaseNumber
        {
            get
            {
                return this.iMSCaseNumberField;
            }
            set
            {
                this.iMSCaseNumberField = value;
                this.RaisePropertyChanged("IMSCaseNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string CaseSubmissionDate
        {
            get
            {
                return this.caseSubmissionDateField;
            }
            set
            {
                this.caseSubmissionDateField = value;
                this.RaisePropertyChanged("CaseSubmissionDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string NODReferralDate
        {
            get
            {
                return this.nODReferralDateField;
            }
            set
            {
                this.nODReferralDateField = value;
                this.RaisePropertyChanged("NODReferralDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string ReasonForNOD
        {
            get
            {
                return this.reasonForNODField;
            }
            set
            {
                this.reasonForNODField = value;
                this.RaisePropertyChanged("ReasonForNOD");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string ReferralSentBy
        {
            get
            {
                return this.referralSentByField;
            }
            set
            {
                this.referralSentByField = value;
                this.RaisePropertyChanged("ReferralSentBy");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncidentDetails", Order = 7)]
        public SendProviderIncidentRequestIncidentDetails[] IncidentDetails
        {
            get
            {
                return this.incidentDetailsField;
            }
            set
            {
                this.incidentDetailsField = value;
                this.RaisePropertyChanged("IncidentDetails");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public partial class SendProviderIncidentRequestIncidentDetails : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string incidentCategoryField;

        private string incidentSubcategoryField;

        private string incidentTypeField;

        private string incidentIDField;

        private object substantiatedField;

        private string iMSAssociateIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IncidentCategory
        {
            get
            {
                return this.incidentCategoryField;
            }
            set
            {
                this.incidentCategoryField = value;
                this.RaisePropertyChanged("IncidentCategory");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string IncidentSubcategory
        {
            get
            {
                return this.incidentSubcategoryField;
            }
            set
            {
                this.incidentSubcategoryField = value;
                this.RaisePropertyChanged("IncidentSubcategory");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string IncidentType
        {
            get
            {
                return this.incidentTypeField;
            }
            set
            {
                this.incidentTypeField = value;
                this.RaisePropertyChanged("IncidentType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string IncidentID
        {
            get
            {
                return this.incidentIDField;
            }
            set
            {
                this.incidentIDField = value;
                this.RaisePropertyChanged("IncidentID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public object Substantiated
        {
            get
            {
                return this.substantiatedField;
            }
            set
            {
                this.substantiatedField = value;
                this.RaisePropertyChanged("Substantiated");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string IMSAssociateID
        {
            get
            {
                return this.iMSAssociateIDField;
            }
            set
            {
                this.iMSAssociateIDField = value;
                this.RaisePropertyChanged("IMSAssociateID");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://mes.gov/incidentmanagement", ConfigurationName = "IncidentManagementService.IncidentManagementSoapPortType")]
    public interface IncidentManagementSoapPortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://mes.gov/sendProviderIncident", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PDMSWebAPI.IncidentManagement.Fault), Action = "http://mes.gov/sendProviderIncident", Name = "Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UpdateProviderIncidentStatusInfo))]
        PDMSWebAPI.IncidentManagement.sendProviderIncidentResponse sendProviderIncident(PDMSWebAPI.IncidentManagement.sendProviderIncidentRequest1 request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "http://mes.gov/sendProviderIncident", ReplyAction = "*")]
        System.Threading.Tasks.Task<PDMSWebAPI.IncidentManagement.sendProviderIncidentResponse> sendProviderIncidentAsync(PDMSWebAPI.IncidentManagement.sendProviderIncidentRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://mes.gov/updateProviderIncidentStatus", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PDMSWebAPI.IncidentManagement.Fault), Action = "http://mes.gov/updateProviderIncidentStatus", Name = "Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UpdateProviderIncidentStatusInfo))]
        PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusResponse updateProviderIncidentStatus(PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "http://mes.gov/updateProviderIncidentStatus", ReplyAction = "*")]
        System.Threading.Tasks.Task<PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusResponse> updateProviderIncidentStatusAsync(PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public partial class MessageHeader : object, System.ComponentModel.INotifyPropertyChanged
    {

        private MessageHeaderBusinessFlow businessFlowField;

        private string stateCodeField;

        private MessageHeaderRequestorSystem requestorSystemField;

        private MessageHeaderSubscriber[] subscriberSystemField;

        private string moduleTransactionIdField;

        private string additionalModuleTransactionIdField;

        private string requestTimestampField;

        private string sITransactionKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MessageHeaderBusinessFlow BusinessFlow
        {
            get
            {
                return this.businessFlowField;
            }
            set
            {
                this.businessFlowField = value;
                this.RaisePropertyChanged("BusinessFlow");
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = true)]
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = true)]
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public MessageHeaderRequestorSystem RequestorSystem
        {
            get
            {
                return this.requestorSystemField;
            }
            set
            {
                this.requestorSystemField = value;
                this.RaisePropertyChanged("RequestorSystem");
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = true)]
        [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Subscriber", IsNullable = false)]
        public MessageHeaderSubscriber[] SubscriberSystem
        {
            get
            {
                return this.subscriberSystemField;
            }
            set
            {
                this.subscriberSystemField = value;
                this.RaisePropertyChanged("SubscriberSystem");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ModuleTransactionId
        {
            get
            {
                return this.moduleTransactionIdField;
            }
            set
            {
                this.moduleTransactionIdField = value;
                this.RaisePropertyChanged("ModuleTransactionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string AdditionalModuleTransactionId
        {
            get
            {
                return this.additionalModuleTransactionIdField;
            }
            set
            {
                this.additionalModuleTransactionIdField = value;
                this.RaisePropertyChanged("AdditionalModuleTransactionId");
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = true)]
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string RequestTimestamp
        {
            get
            {
                return this.requestTimestampField;
            }
            set
            {
                this.requestTimestampField = value;
                this.RaisePropertyChanged("RequestTimestamp");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string SITransactionKey
        {
            get
            {
                return this.sITransactionKeyField;
            }
            set
            {
                this.sITransactionKeyField = value;
                this.RaisePropertyChanged("SITransactionKey");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public enum MessageHeaderBusinessFlow
    {

        /// <remarks/>
        SendProviderIncident,

        /// <remarks/>
        UpdateProviderIncidentStatus,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public enum MessageHeaderRequestorSystem
    {

        /// <remarks/>
        PNM,

        /// <remarks/>
        IMS,

        /// <remarks/>
        HealthCheck,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public enum MessageHeaderSubscriber
    {

        /// <remarks/>
        PNM,

        /// <remarks/>
        IMS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public partial class SendProviderIncidentRequestPayload : object, System.ComponentModel.INotifyPropertyChanged
    {

        private SendProviderIncidentRequest sendProviderIncidentInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public SendProviderIncidentRequest SendProviderIncidentInfo
        {
            get
            {
                return this.sendProviderIncidentInfoField;
            }
            set
            {
                this.sendProviderIncidentInfoField = value;
                this.RaisePropertyChanged("SendProviderIncidentInfo");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public enum SendProviderIncidentResponseResponseType
    {

        /// <remarks/>
        Success,

        /// <remarks/>
        Failure,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SendProviderIncidentRequest", WrapperNamespace = "http://mes.gov/incidentmanagement", IsWrapped = true)]
    public partial class sendProviderIncidentRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 0)]
        public PDMSWebAPI.IncidentManagement.MessageHeader MessageHeader;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 1)]
        public PDMSWebAPI.IncidentManagement.SendProviderIncidentRequestPayload Payload;

        public sendProviderIncidentRequest1()
        {
        }

        public sendProviderIncidentRequest1(PDMSWebAPI.IncidentManagement.MessageHeader MessageHeader, PDMSWebAPI.IncidentManagement.SendProviderIncidentRequestPayload Payload)
        {
            this.MessageHeader = MessageHeader;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SendProviderIncidentResponse", WrapperNamespace = "http://mes.gov/incidentmanagement", IsWrapped = true)]
    public partial class sendProviderIncidentResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 0)]
        public string SITransactionKey;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 1)]
        public string ModuleTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 2)]
        public string AdditionalModuleTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 3)]
        public string ResponseCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 4)]
        public PDMSWebAPI.IncidentManagement.SendProviderIncidentResponseResponseType ResponseType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 5)]
        public string ResponseMessage;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 6)]
        public string ResponseDetails;

        public sendProviderIncidentResponse()
        {
        }

        public sendProviderIncidentResponse(string SITransactionKey, string ModuleTransactionId, string AdditionalModuleTransactionId, string ResponseCode, PDMSWebAPI.IncidentManagement.SendProviderIncidentResponseResponseType ResponseType, string ResponseMessage, string ResponseDetails)
        {
            this.SITransactionKey = SITransactionKey;
            this.ModuleTransactionId = ModuleTransactionId;
            this.AdditionalModuleTransactionId = AdditionalModuleTransactionId;
            this.ResponseCode = ResponseCode;
            this.ResponseType = ResponseType;
            this.ResponseMessage = ResponseMessage;
            this.ResponseDetails = ResponseDetails;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mes.gov/incidentmanagement")]
    public partial class UpdateProviderIncidentStatusRequestPayload : object, System.ComponentModel.INotifyPropertyChanged
    {

        private UpdateProviderIncidentStatusInfo updateProviderIncidentStatusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public UpdateProviderIncidentStatusInfo UpdateProviderIncidentStatusInfo
        {
            get
            {
                return this.updateProviderIncidentStatusInfoField;
            }
            set
            {
                this.updateProviderIncidentStatusInfoField = value;
                this.RaisePropertyChanged("UpdateProviderIncidentStatusInfo");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateProviderIncidentStatusRequest", WrapperNamespace = "http://mes.gov/incidentmanagement", IsWrapped = true)]
    [XmlRoot("UpdateProviderIncidentStatusRequest")]
    public partial class updateProviderIncidentStatusRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 0)]
        public PDMSWebAPI.IncidentManagement.MessageHeader MessageHeader;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 1)]
        public PDMSWebAPI.IncidentManagement.UpdateProviderIncidentStatusRequestPayload Payload;

        public updateProviderIncidentStatusRequest()
        {
        }

        public updateProviderIncidentStatusRequest(PDMSWebAPI.IncidentManagement.MessageHeader MessageHeader, PDMSWebAPI.IncidentManagement.UpdateProviderIncidentStatusRequestPayload Payload)
        {
            this.MessageHeader = MessageHeader;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateProviderIncidentStatusResponse", WrapperNamespace = "http://mes.gov/incidentmanagement", IsWrapped = true)]
    public partial class updateProviderIncidentStatusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 0)]
        public string SITransactionKey;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 1)]
        public string ModuleTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 2)]
        public string AdditionalModuleTransactionId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 3)]
        public string ResponseCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 4)]
        public string ResponseType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 5)]
        public string ResponseMessage;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://mes.gov/incidentmanagement", Order = 6)]
        public string ResponseDetails;

        public updateProviderIncidentStatusResponse()
        {
        }

        public updateProviderIncidentStatusResponse(string SITransactionKey, string ModuleTransactionId, string AdditionalModuleTransactionId, string ResponseCode, string ResponseType, string ResponseMessage, string ResponseDetails)
        {
            this.SITransactionKey = SITransactionKey;
            this.ModuleTransactionId = ModuleTransactionId;
            this.AdditionalModuleTransactionId = AdditionalModuleTransactionId;
            this.ResponseCode = ResponseCode;
            this.ResponseType = ResponseType;
            this.ResponseMessage = ResponseMessage;
            this.ResponseDetails = ResponseDetails;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IncidentManagementSoapPortTypeChannel : PDMSWebAPI.IncidentManagement.IncidentManagementSoapPortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncidentManagementSoapPortTypeClient : System.ServiceModel.ClientBase<PDMSWebAPI.IncidentManagement.IncidentManagementSoapPortType>, PDMSWebAPI.IncidentManagement.IncidentManagementSoapPortType
    {

        public IncidentManagementSoapPortTypeClient()
        {
        }

        public IncidentManagementSoapPortTypeClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public IncidentManagementSoapPortTypeClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public IncidentManagementSoapPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public IncidentManagementSoapPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDMSWebAPI.IncidentManagement.sendProviderIncidentResponse PDMSWebAPI.IncidentManagement.IncidentManagementSoapPortType.sendProviderIncident(PDMSWebAPI.IncidentManagement.sendProviderIncidentRequest1 request)
        {
            return base.Channel.sendProviderIncident(request);
        }

        public string sendProviderIncident(PDMSWebAPI.IncidentManagement.MessageHeader MessageHeader, PDMSWebAPI.IncidentManagement.SendProviderIncidentRequestPayload Payload, out string ModuleTransactionId, out string AdditionalModuleTransactionId, out string ResponseCode, out PDMSWebAPI.IncidentManagement.SendProviderIncidentResponseResponseType ResponseType, out string ResponseMessage, out string ResponseDetails)
        {
            PDMSWebAPI.IncidentManagement.sendProviderIncidentRequest1 inValue = new PDMSWebAPI.IncidentManagement.sendProviderIncidentRequest1();
            inValue.MessageHeader = MessageHeader;
            inValue.Payload = Payload;
            PDMSWebAPI.IncidentManagement.sendProviderIncidentResponse retVal = ((PDMSWebAPI.IncidentManagement.IncidentManagementSoapPortType)(this)).sendProviderIncident(inValue);
            ModuleTransactionId = retVal.ModuleTransactionId;
            AdditionalModuleTransactionId = retVal.AdditionalModuleTransactionId;
            ResponseCode = retVal.ResponseCode;
            ResponseType = retVal.ResponseType;
            ResponseMessage = retVal.ResponseMessage;
            ResponseDetails = retVal.ResponseDetails;
            return retVal.SITransactionKey;
        }

        public System.Threading.Tasks.Task<PDMSWebAPI.IncidentManagement.sendProviderIncidentResponse> sendProviderIncidentAsync(PDMSWebAPI.IncidentManagement.sendProviderIncidentRequest1 request)
        {
            return base.Channel.sendProviderIncidentAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusResponse PDMSWebAPI.IncidentManagement.IncidentManagementSoapPortType.updateProviderIncidentStatus(PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusRequest request)
        {
            return base.Channel.updateProviderIncidentStatus(request);
        }

        public string updateProviderIncidentStatus(PDMSWebAPI.IncidentManagement.MessageHeader MessageHeader, PDMSWebAPI.IncidentManagement.UpdateProviderIncidentStatusRequestPayload Payload, out string ModuleTransactionId, out string AdditionalModuleTransactionId, out string ResponseCode, out string ResponseType, out string ResponseMessage, out string ResponseDetails)
        {
            PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusRequest inValue = new PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusRequest();
            inValue.MessageHeader = MessageHeader;
            inValue.Payload = Payload;
            PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusResponse retVal = ((PDMSWebAPI.IncidentManagement.IncidentManagementSoapPortType)(this)).updateProviderIncidentStatus(inValue);
            ModuleTransactionId = retVal.ModuleTransactionId;
            AdditionalModuleTransactionId = retVal.AdditionalModuleTransactionId;
            ResponseCode = retVal.ResponseCode;
            ResponseType = retVal.ResponseType;
            ResponseMessage = retVal.ResponseMessage;
            ResponseDetails = retVal.ResponseDetails;
            return retVal.SITransactionKey;
        }

        public System.Threading.Tasks.Task<PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusResponse> updateProviderIncidentStatusAsync(PDMSWebAPI.IncidentManagement.updateProviderIncidentStatusRequest request)
        {
            return base.Channel.updateProviderIncidentStatusAsync(request);
        }
    }
}
